### PR TITLE
chore(suite): remove ConnectDevicePromptManager

### LINKED ISSUE #13399: Remove ConnectDevicePromptManager
Remove last remaining uses of `ConnectDevicePromptManager` and replace them with `PrerequisitesGuide`, to avoid unnecessary code duplication
This affects `FirmwareModal`, `FirmwareStep`, `FirmwareInitial`

### PR DESCRIPTION
**Pull request by martykan**
## Description

Remove last remaining uses of `ConnectDevicePromptManager` and replace them with `PrerequisitesGuide`. 
This affects `FirmwareModal`, `FirmwareStep`, `FirmwareInitial` 

## Related Issue

Resolve #13399

### CODE REVIEW

**Comment by mroz22** [comment]
please create an issue and then close it with this PR :D this way it should notify QA to test it 🙏 am I right? @MiroslavProchazka

**Comment by martykan** [comment]
Issue is here https://github.com/trezor/trezor-suite/issues/13399

**Comment by MiroslavProchazka** [comment]
QA will test it once the respective issue will be closed and automation (or someone) will change its status to Needs QA. If you need to test it before closing the issue, simply change the status manually.

**Review by mroz22 — APPROVED** [review]
good, please @trezor/qa test firmware update for possible regressions

**Pull request merged**
