### PR TITLE
fix: deselected device after onboarding

### PR DESCRIPTION
**Pull request by mroz22**
this seems to be fixing #4250 (on my machine :joy_cat: )

### CODE REVIEW

**Comment by tsusanka** [comment]
This works on my machine as well! :)

Btw sorry for bike-shedding but what is the point of keeping commented-out code in the codebase? I personally really hate it :), we have `git` for that don't we?

URL for QA: https://suite.corp.sldev.cz/suite-web/fix-deselected-device-after-onboarding/web/

**Comment by matejkriz** [comment]
works for me even with other device remembered when updating FW from 10.0.1, but when I tried to setup device without FW (`trezorctl device wipe --bootloader`) I got stucked after FW instalation :-/ 

image
image
reconnecting the right trezor didn't help

On current production (21.8.1) the same flow works fine. 

Maybe instead of deleting that part completely just add condition if there is some other device remembered?

**Comment by tsusanka** [comment]
Surprisingly what @matejkriz is describing does not happen to me. Tried twice.

- Bridge v2.0.31
- Firefox 90.0.2

**Comment by marekrjpolak** [comment]
Also couldn't reproduce. Neither in Chrome/WebUsb, nor in Firefox/Bridge.

**Comment by matejkriz** [comment]
Do you have another device remembered?

1. Connect some initialized trezor
2. Mark as remembered
3. Connect other trezor without FW and start to set it up
...

**Comment by marekrjpolak** [comment]
Now it happened to me as well. (Firefox/Bridge)

**Comment by bosomt** [comment]
tested with last commit 8d0632e5 in fix-.... branch
https://gitlab.com/satoshilabs/trezor/trezor-suite/-/pipelines/368100596

OS: updated Windows 10 

1) empty device without FW
2) empty device with 1.10.1 FW
3) empty device without FW + remembered device
4) empty device without FW + remembered device + connected model T
5) empty device without FW + empty device model T without FW + remembered device

5x onboarding of model one went without any-kind of problem :feelsgood:

**Comment by mroz22** [comment]
this branch contains only "core" fixes for happy path. #4258 is based on this branch and is more elaborated. so we will decide which one we are going to merge.

**Comment by tomasklim** [comment]
Merged with #4258

**Pull request closed without merging**
