### PR TITLE
connect and dependencies: npm versioning

### PR DESCRIPTION
**Pull request by mroz22**
We need to talk!

We need some mechanism how to avoid forgetting releasing connect dependencies. In monorepo, we don't care about npm, we have everything locally. But it will be very easy to forget to release lets say `@trezor/blockchain-link`. Anybody installing connect from npm relies on the fact that the code v @trezor/connect npm package works with the code of `@trezor/blockchain-link` package that is download from npm. 

Should we, with every release of connet, bump version of all connect dependencies to the same version? 

- 2c63f0da50a253704631c00aea3f0e5acedca597 sets all connect related packages to one version. this will work most likely but does not feel convenient.

### CODE REVIEW

**Comment by matejkriz** [comment]
I don't think we need to bump version of all connect dependencies with every Connect release. 

Maybe we could just set up the release process for Connect more strict to not forget? Trying to install Connect from NPM should be part of the releasing it, shouldn’t it?

And maybe we could add some script to check if the related dependencies been published to NPM?

**Comment by mroz22** [comment]
> I don't think we need to bump version of all connect dependencies with every Connect release.

technically, we don't need to release those that did not change

> Maybe we could just set up the release process for Connect more strict to not forget?

yes, but I am 100% sure that without automation we will forget to do that some day

> Trying to install Connect from NPM should be part of the releasing it

It would need to be outside of monorepo. Either another project or maybe remove all package dependencies from local checkout? 

> And maybe we could add some script to check if the related dependencies been published to NPM?

Yes, this could work. It would need to create local builds, generate checksums and compare them with checksums in yarn.lock file. Something like that. https://github.com/yarnpkg/yarn/blob/master/src/integrity-checker.js

**Comment by mroz22** [comment]
OK, I accidentally created `@trezor/utils` version `9.0.0` in npm registery. Lessons learned `yarn publish --dry-run` does not support dry-run probably. I just wanted to check whether --dry-run output might contain anything useful for comparing local and remote (npm) version. 

I also tried to "unpublish" this version using 
```
npm unpublish @trezor/utils@9.0.0

```
but had no luck doing that 
```
npm ERR! code E405
npm ERR! 405 Method Not Allowed - PUT https://registry.npmjs.org/@trezor%2futils/-rev/4-8e2e868f2501f8b6be01380c2298ab49 - You can no longer unpublish this package.
npm ERR! Failed criteria: 
npm ERR! has dependent packages in the registry
npm ERR! 
npm ERR! Please deprecate it instead:
npm ERR! npm deprecate -f '@trezor/utils@9.0.0' "this package has been deprecated"

```

Also sent a support ticket to npm. Maybe they can remove it somehow..

**Comment by matejkriz** [comment]
you could unpublish it before it's used:

```
npm unpublish @trezor/utils@9.0.0
```

>Even if you unpublish a package version, that specific name and version combination can never be reused. In order to publish the package again, you must use a new version number.

I hope it will allow us to publish version below 9...

**Comment by szymonlesisz** [comment]
> generate checksums and compare them with checksums in yarn.lock file

me like it :)

> I hope it will allow us to publish version below 9...

i'm afraid it will not :( npm is quite restrictive when it comes to versioning. let's hope im wrong

edit: after some reading `npm publish --tag latest` might help, but 9.0.0 is lost (reserved) for good

**Pull request closed without merging**
