### PR TITLE
Add Japanese to Trezor Suite

### PR DESCRIPTION
**Pull request by fujicoin**
This file was downloaded from the link below at 19:51 (JST) on January 14, 2022.
https://crowdin.com/project/trezor-suite/ja
----------------------------------------------------------------------------------

I have translated all Trezor Sute English into Japanese on crowdin.com.
The original translations are referenced in the following order.
First priority:
Trezor repository en.json
https://github.com/trezor/trezor-suite/blob/develop/packages/suite-data/files/translations/en.json
Second:
English text of crowdin.com
https://crowdin.com/translate/trezor-suite/

There are two lines in en.json of Trezor repository that do not exist in crowdin, but I decided not to adopt it because there seems to be a misspelling in the variable name.
   "TR_GUIDE_FEEDACK_OR_SUGGESTION": "Report Bug & Feedback",
   "TR_HELP_TREZOR_SUITE": "Help us improve Trezor Suite \ n",

If you download directly from crowdin, you do not need to adopt this PR.

Thanks,
motty
fujicoin.org

### CODE REVIEW

**Comment by mroz22** [comment]
Wow, great work!

**Comment by fujicoin** [comment]
I actually tried to display it in Japanese, but I found that there were some problems.

There is a part that has a strange display.
suite_ja1


It seems that it is necessary to adjust the number of characters in the part where the display space is fixed.
suite_ja2


I will continue to improve the translation, including other issues. I'll let you know when it's done.

**Comment by fujicoin** [comment]
This part is strangely displayed even if the number of characters is reduced.
There is no choice but to leave the translation in English for the time being.
If possible, improve the code to display double-byte characters properly.
suite_ja3

**Comment by fujicoin** [comment]
I modified the Japanese translation file.
This is an improvement of the translation after implementing it in Trezor Sute and checking the actual display.
Download date and time from crowdin.com: January 15, 2022 7:16 (JST)
------------------------------------------------------------------------------------------------

This translation is completely natural even when read by a native Japanese user.
Implement it in Trezor Sute with confidence. Or I think it's a good idea to have a Japanese distributor check the pre-release version.

Thanks!


suite_ja4


suite_ja5

**Comment by fujicoin** [comment]
My translation of this time is fixed above.
For the following, I would like to deal with untranslated cases on crowdin.com. Basically, I can think that the translation file is automatically imported from crowdin.com, right? Or should I be watching the changes in the repository en.json?
It doesn't matter if you ask me for it at your convenience.


suite_desctop0

suite_desctop1

suite_desctop2

suite_desctop3

suite_desctop4

**Comment by fujicoin** [comment]
I tried Suite version 22.1.
The red frame in the figure below is not translated.
The code is supposed to use `id = "TR_LOG_DESCRIPTION"`, but it doesn't exist in the translation files.
https://gitlab.com/satoshilabs/trezor/trezor-suite/-/blob/develop/packages/suite/src/views/settings/index.tsx#L373

suite_desctop5


I added "TR_LOG_DESCRIPTION" to ja.json.
As a result, it was translated correctly.

suite_desctop6


However, there are now three identical words in the translation file.
```
  "TR_SHOW_LOG_DESCRIPTION": "サポートチームと連絡を取った場合、そこには必要な全ての技術情報の記録があります。",
  "LOG_DESCRIPTION": "サポートチームと連絡を取った場合、そこには必要な全ての技術情報の記録があります。",
  "TR_LOG_DESCRIPTION": "サポートチームと連絡を取った場合、そこには必要な全ての技術情報の記録があります。",
```

Translation relations are confused overall. I think it's better to organize the whole thing once.

**Comment by fujicoin** [comment]
I thought about where to put the origin when translating. As a result, I thought that `packages/suite/src/support/messages.ts` should be the origin.

So I made a reference `refarence.json` file from version 22.1 `messages.ts`.
https://gitlab.com/satoshilabs/trezor/trezor-suite/-/blob/release/22.1/packages/suite/src/support/messages.ts

[reference.json.txt](https://github.com/trezor/trezor-suite/files/7878380/reference.json.txt)

I compared this with the current `ja.json` to see the difference.
Things that exist in the reference but not in `ja.json`:
```
AMOUNT_NOT_ENOUGH_CURRENCY_FEE
BACKUP_BACKUP_ALREADY_FINISHED_HEADING
TR_BACKUP_FAILED
TR_EXCHANGE_APPROVAL_SEND_TO
TR_EXCHANGE_DETAIL_KYC_BUTTON
TR_EXCHANGE_DEX_OFFER_FEE_INFO
TR_TROUBLESHOOTING_TIP_BRIDGE_INSTALL_TITLE
TR_TROUBLESHOOTING_TIP_BRIDGE_USE_TITLE
```

Something in `ja.json` but not in the reference:
```
AMOUNT_ENOUGH_CURRENCY_FEE
BACKUP_BACKUP_ALREADY_FINISHED
BACKUP_FAILED
TR_EXCHANGE_DEX_FEE_INFO
TR_GUIDE_FEEDACK_OR_SUGGESTION
TR_HELP_TREZOR_SUITE
TR_SHOW_LOG_DESCRIPTION
TR_TOUBLESHOOTING_TIP_BRIDGE_INSTALL_TITLE
TR_TOUBLESHOOTING_TIP_BRIDGE_USE_TITLE
```

The reason for this difference is that the translation file contains key names that are not used in the actual code.

**Comment by fujicoin** [comment]
In the `messages.ts` file, the name of the primary key and the value of "id" are different as follows. 
It seems that mistakes will not occur if the value of "id" is corrected.
```
TR_EXCHANGE_DEX_OFFER_FEE_INFO                  TR_EXCHANGE_DEX_FEE_INFO
TR_EXCHANGE_DETAIL_KYC_BUTTON                   TR_EXCHANGE_DETAIL_ERROR_BUTTON
TR_EXCHANGE_APPROVAL_SEND_TO                    TR_EXCHANGE_SEND_TO
TR_LOG_DESCRIPTION                              TR_SHOW_LOG_DESCRIPTION
BACKUP_BACKUP_ALREADY_FINISHED_HEADING          BACKUP_BACKUP_ALREADY_FINISHED
AMOUNT_NOT_ENOUGH_CURRENCY_FEE                  AMOUNT_ENOUGH_CURRENCY_FEE
TR_BACKUP_FAILED                                BACKUP_FAILED
TR_TROUBLESHOOTING_TIP_BRIDGE_INSTALL_TITLE     TR_TOUBLESHOOTING_TIP_BRIDGE_INSTALL_TITLE
TR_TROUBLESHOOTING_TIP_BRIDGE_USE_TITLE         TR_TOUBLESHOOTING_TIP_BRIDGE_USE_TITLE
```

**Comment by fujicoin** [comment]
I wrote python code to create a `master.json` file from a` messages.ts` file with little manual effort. Only the `,` at the end of the output file should be manually removed.
Attach this code and output. Please verify it there.

messages2master.json.zip --- Removed!

I think it's a good idea to have a new `master.json` uploaded to crowdin.com each time a phrase is added or updated.

**Comment by fujicoin** [comment]
Finaly I deleted the following translations that are not used.
This result is an exact match with `messages.ts`.
```
AMOUNT_ENOUGH_CURRENCY_FEE
BACKUP_BACKUP_ALREADY_FINISHED
BACKUP_FAILED
TR_EXCHANGE_DEX_FEE_INFO
TR_GUIDE_FEEDACK_OR_SUGGESTION
TR_HELP_TREZOR_SUITE
TR_SHOW_LOG_DESCRIPTION
TR_TOUBLESHOOTING_TIP_BRIDGE_INSTALL_TITLE
TR_TOUBLESHOOTING_TIP_BRIDGE_USE_TITLE
```

**Comment by fujicoin** [comment]
I fixed messages2master.json.py.
- Changed the part where the value is enclosed in single quotes to double quotes.
- Along with that, an appropriate escape process was added.
- Removed `,` at the end of the last line.

Attach a modified version:
[messages2master.json.zip](https://github.com/trezor/trezor-suite/files/7884924/messages2master.json.zip)

**Comment by fujicoin** [comment]
I think the following explanation about OP_RETURN is inappropriate. No one would try to use this feature in the current description.
https://github.com/trezor/trezor-suite/blob/c37673e9266250beffdb010493e4f77f251f08c9/packages/suite/src/support/messages.ts#L5474

The source of the citation is presumed to be the next page.
https://en.bitcoin.it/wiki/OP_RETURN

If you quote from this page, I think you should rather adopt the following wording.
```
OP_RETURN can be used for digital asset proof-of-ownership, and has at times been used to convey additional information needed to send transactions.
```

**Comment by fujicoin** [comment]
I think it is inappropriate to use en.json to modify the English text of Trezor Suite. Why not modify messages.ts?
I tried to extract the difference between the English texts of en.json and messages.ts. Please refer to the attached file and modify messages.ts.
Since the json file is read and processed, "\ n" is actually a line break in the print.

[updated_items.txt](https://github.com/trezor/trezor-suite/files/7888528/updated_items.txt)

**Comment by fujicoin** [comment]
I have brushed up the Japanese translation.

- Unification of terminology
- Easy-to-understand translations
- Easily esoteric content
- Some typos

@alex-jerechinsky 
What is the procedure for this translation to be adopted?

**Comment by fujicoin** [comment]
@tomasklim @matejkriz @alex-jerechinsky 
Japanese translation in crowdin is complete. You can download it at any time and integrate it into Trezor Suite.

Thanks!

**Pull request closed without merging**
