### PR TITLE
upgrade to ts 3.7

### LINKED ISSUE #768: Upgrade typescript (3.7)
we need to make sure that there is support for new TS syntax in eslint, prettier,...

~~Currently blocked by https://github.com/prettier/prettier/issues/6595~~
Currently blocked by broken types in ripple-lib, waiting for a new release with a fix

### PR DESCRIPTION
**Pull request by slowbackspace**
close https://github.com/trezor/trezor-suite/issues/768

recommended reading:
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#optional-chaining
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#nullish-coalescing

### CODE REVIEW

**Comment by mroz22** [comment]
Tada! Blocker merged!

**Comment by slowbackspace** [comment]
> Tada! Blocker merged!

yup, but there still isn't new version in npm with the merged fix released (last release was 26 days ago)

**Comment by mroz22** [comment]
released!!! :rocket:

**Comment by mroz22** [comment]
rebased and updated ripple-lib

**Comment by slowbackspace** [comment]
> rebased and updated ripple-lib

shouldn't we also bump version in blockchain-link?

**Comment by slowbackspace** [comment]
huh weird issue. jest fails the unit test because it doesn't understand new syntax... but afaik we are using ts-jest which should just use TS, not babel as log for the gitlab job suggests (the only reason why there is babel config is l10n extraction process, ts-jest should not use babel at all until it is explicitly told to).  @mroz22 help needed

**Comment by mroz22** [comment]
got stuck on this too. found a issue targeting this with a hint to run this againts node v14, as this optional chaining is available only there under feature flag, BUT still ts-jest should handle transpilation process ofc.

**Comment by mroz22** [comment]
we have `target: "ESNext"` in tsconfig and it seems like our node.js version does not understand the syntax. Setting it to `"target": "ES2020"` makes it work.

**Pull request merged**
