### PR TITLE
test(suite-desktop): add running bridge version assertion

### PR DESCRIPTION
**Pull request by mroz22**
just a tiny update of spawn-bridge test in desktop.  the only notable addition is that it now asserts expected bridge version.

### CODE REVIEW

**Review by vdovhanych — APPROVED** [review]

**Comment by mroz22** [comment]
@karliatto could you please test it out on your machine? the spawn-bridge test? 🙏 

```
yarn workspace @trezor/suite-desktop-core test:e2e spawn-brige
```
should do the trigger. you should have trezor-user-env running but everything off (no external bridge). suite run by tests should starts its own bridge, tests should validate it and exit with success. oh and you need to build app before running this test.

**Comment by karliatto** [comment]
> @karliatto could you please test it out on your machine? the spawn-bridge test? 🙏
> 

It did not work for me when having:
* trezor-user-env running with no emulator nor bridge
* Building the desktop app
* Running - `yarn workspace @trezor/suite-desktop-core test:e2e spawn-bridge`

I am getting error:

```
  Error: websocket_error_message: KeyError - '2'

       at ../../../trezor-user-env-link/src/websocket-client.ts:157

      155 |                 if (!success) {
      156 |                     dfd.reject(
    > 157 |                         new Error(`websocket_error_message: ${resp.error.message || resp.error}`),
          |                         ^
      158 |                     );
      159 |                 } else {
      160 |                     dfd.resolve(resp);
```

And in trezor-user-env:

```
trezor-user-env.unix       | BRIDGE: WARNING: Attempting to stop a brige, but it is not running
trezor-user-env.unix       | BRIDGE PROXY: Stopping
trezor-user-env.unix       | BRIDGE PROXY: WARNING: Attempting to stop a bridge proxy, but it is not running
trezor-user-env.unix       | BRIDGE: Is bridge running - False
trezor-user-env.unix       | BRIDGE: Is bridge proxy running - False
trezor-user-env.unix       | CONTROLLER: Response: {'response': 'Stopping bridge + stopping bridge proxy', 'id': 0, 'success': True}
trezor-user-env.unix       | CONTROLLER: Request: {'id': 1, 'type': 'emulator-start', 'model': 'T2T1', 'version': '2-latest', 'wipe': True}
trezor-user-env.unix       | CONTROLLER: Traceback (most recent call last):
trezor-user-env.unix       |   File "/trezor-user-env/src/controller.py", line 98, in get_response
trezor-user-env.unix       |     command_response = self.run_command_and_get_its_response()
trezor-user-env.unix       |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
trezor-user-env.unix       |   File "/trezor-user-env/src/controller.py", line 133, in run_command_and_get_its_response
trezor-user-env.unix       |     return self.run_emulator_command()
trezor-user-env.unix       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
trezor-user-env.unix       |   File "/trezor-user-env/src/controller.py", line 174, in run_emulator_command
trezor-user-env.unix       |     version = binaries.get_latest_release_version(model)
trezor-user-env.unix       |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
trezor-user-env.unix       |   File "/trezor-user-env/src/binaries.py", line 47, in get_latest_release_version
trezor-user-env.unix       |     return list(FIRMWARES[model].keys())[1]
trezor-user-env.unix       |                 ~~~~~~~~~^^^^^^^
trezor-user-env.unix       | KeyError: '2'
```

I can try to get deeper to see why it fails.

Edit: I just realize that looks like emulator model missing on my side.

**Comment by mroz22** [comment]
don't you have an old trezor-user-env image?

**Comment by karliatto** [comment]
> don't you have an old trezor-user-env image?

I had to update, my bad. I updated and now tests pass for me.

**Comment by mroz22** [comment]
Thats interesting. Unfortunately, they do not pass in the CI so @karliatto if I may please ask you. Would you please rebase it and push the version that works for you? And if it still does not pass the CI, could you please take a quick look what is wrong with it?

**Comment by mroz22** [comment]
@karliatto are you sure that it works? https://github.com/trezor/trezor-suite/actions/runs/10767618975/job/29855264672?pr=13984#step:7:614

**Comment by karliatto** [comment]
> @karliatto are you sure that it works? https://github.com/trezor/trezor-suite/actions/runs/10767618975/job/29855264672?pr=13984#step:7:614

You are totally right. I changed it to check the error types and now it is not passing, for some reason Bridge is not running.
Anyway I got frustrated enough and when I get frustrated I simplify. So I started new PR with some of the testing scope of this PR just checking the version of bridge https://github.com/trezor/trezor-suite/pull/14236

Once that new PR is merged I will extend the test with the rest of the scope of this PR and finally close this one.

**Comment by karliatto** [comment]
Clossing this PR since it has been done in different PRs completing the scope of it with https://github.com/trezor/trezor-suite/pull/14241

**Pull request closed without merging**
