### PR TITLE
Feat/udev install

### LINKED ISSUE #3664: Install udev rules via AppImage automatically (Linux)
It should be possible to install udev rules by fiddling with the `AppRun` script. 

We could first check whether the udev rules are installed and offer installing them if not. Something among this lines:

``` bash
if [ \! -f /etc/udev/rules.d/51-trezor.rules ] ; then
  pkexec cp -a $SUITE_RESOURCES/51-trezor.rules /etc/udev/rules.d/51-trezor.rules
fi
```

and only run Electron after this code has run.

### PR DESCRIPTION
**Pull request by szymonlesisz**
fix https://github.com/trezor/trezor-suite/issues/3664

@trezor/qa scenarios

1. remove udev rules from linux machine:
`pkexec rm /etc/udev/rules.d/51-trezor.rules` or `sudo rm /etc/udev/rules.d/51-trezor.rules`

2. run suite app, connect Trezor

3. click "install rules automatically` 

3. a) if you cancel Troubleshooting tips should unfold automatically offering you alternative: packages to download

3. b) if you succeed Troubleshooting tips should change to "reconnect device"

4. check if offerred packages are corresponding with your linux distribution (rpm/deb)

suite-web is not able to do automatic install therefore it only offers packages to download

Screenshot from 2021-08-25 16-36-07
Screenshot from 2021-08-25 16-36-25
Screenshot from 2021-08-25 16-36-56

### CODE REVIEW

**Comment by szymonlesisz** [comment]
tagging @prusnak to have a look at the first commit 698e15d  how `pkexec` is used to copy rules. 
file: packages/suite-desktop/src-electron/modules/udev-install.ts

**Review by prusnak — APPROVED** [review]
haven't tested it, but the code looks great!

**Review by tomasklim — APPROVED** [review]
Code LGTM. Maybe you could show us how it looks in the app after standup.

**Comment by sorooris** [comment]
**QA OK**
Tested with Mint 19.3, you will be shocked by the details in [this totally not shady link](https://satoshilabs.ontestpad.com/script/368/report/?auth=d6c0f8527ac360c445ffa20b65bca3e).

Suite: app 21.9.0 a7fc3731db3e9f58e066a5af970832519b6699f4
OS: Linux Mint 19.3 Cinnamon
Devices: model One 1.10.2, model T 2.4.1

**Comment by sorooris** [comment]
Reported a trivial issue found during testing this here: https://github.com/trezor/trezor-suite/issues/4183

**Pull request merged**
