### PR TITLE
Feat: coinjoin unify coordinator requests with WalletWasabi

### PR DESCRIPTION
**Pull request by szymonlesisz**
## Description

1. `WalletWasabi` is using PascalCase in objects sent to coordinator
2. adding missing conditional usage of `input-unregistration` same as WalletWasabi does https://github.com/zkSNACKs/WalletWasabi/blob/master/WalletWasabi/WabiSabi/Client/AliceClient.cs#L97
3. update coinjoin middleware version 14.1
   commit https://github.com/trezor/WalletWasabi/commit/b2a02e2d1a2eda3f3552a0d83e1d03c30ed57578
    - Fixed select-inputs-for-round
    - Support empty amountToRequest (used only by outputRegistration process)
    - Use PascalCase in credentials sent to coordinator
    - Increase max inputs registrable by suite to 20
 4. use `127.0.0.1` instead of `localhost` in coinjoin config (regtest case)
    i was pretty sure that i've fixed it long time ago turns out i only stashed it. `localhost` is not resolved properly on linux+docker (coinjoin-backend) - similar case as with `trezor-user-env`
    
 ## Related Issue
 
 follow up for https://github.com/trezor/trezor-suite/issues/7182

### CODE REVIEW

**Comment by szymonlesisz** [comment]
@vdovhanych pls sign macos binaries

**Comment by vdovhanych** [comment]
> @vdovhanych pls sign macos binaries

Done @szymonlesisz

**Comment by szymonlesisz** [comment]
the code itself is ready to review but unfortunately i've found some issue in the middleware so it will be probably updated once more :/

**Review by matejkriz — APPROVED** [review]
makes sense and work as expected on testnet for me

**Pull request merged**
