### PR TITLE
fix(suite-desktop): force set value for undefined APPIMAGE env variable

### LINKED ISSUE #2962: Autoupdate failing on NixOS
Part of #2916. Throws `Error: Error: APPIMAGE env is not defined` during an update.

```
Trezor-Suite-20.10.1-linux.AppImage installed in /home/tsusanka//.cache/appimage-run/ed08ffd7c4d64cbd0729d34476963cdf37d68961142120f0ea52737b2b7ff43a
Checking for update
Found version 20.11.2 (url: Trezor-Suite-20.11.2-linux.AppImage)
Downloading update from Trezor-Suite-20.11.2-linux.AppImage
updater cache dir: /home/tsusanka/.cache/@trezorsuite-desktop-updater
Error: Error: APPIMAGE env is not defined
    at newError (/home/tsusanka/.cache/appimage-run/ed08ffd7c4d64cbd0729d34476963cdf37d68961142120f0ea52737b2b7ff43a/resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/out/index.js:212:17)
    at Object.task (/home/tsusanka/.cache/appimage-run/ed08ffd7c4d64cbd0729d34476963cdf37d68961142120f0ea52737b2b7ff43a/resources/app.asar/node_modules/electron-updater/out/AppImageUpdater.js:108:52)
    at AppImageUpdater.executeDownload (/home/tsusanka/.cache/appimage-run/ed08ffd7c4d64cbd0729d34476963cdf37d68961142120f0ea52737b2b7ff43a/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:756:25)
(node:5475) UnhandledPromiseRejectionWarning: Error: APPIMAGE env is not defined
    at newError (/home/tsusanka/.cache/appimage-run/ed08ffd7c4d64cbd0729d34476963cdf37d68961142120f0ea52737b2b7ff43a/resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/out/index.js:212:17)
    at Object.task (/home/tsusanka/.cache/appimage-run/ed08ffd7c4d64cbd0729d34476963cdf37d68961142120f0ea52737b2b7ff43a/resources/app.asar/node_modules/electron-updater/out/AppImageUpdater.js:108:52)
    at AppImageUpdater.executeDownload (/home/tsusanka/.cache/appimage-run/ed08ffd7c4d64cbd0729d34476963cdf37d68961142120f0ea52737b2b7ff43a/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:756:25)
(node:5475) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:5475) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### PR DESCRIPTION
**Pull request by keraf**
Should fix #2962 (if anyone on NixOS could test please! cc @prusnak @trezor/qa)

### CODE REVIEW

**Comment by mroz22** [comment]
bupmed into this yesterday, may be useful https://docs.appimage.org/packaging-guide/testing.html#using-the-docker-based-appimage-testsuite (it is not really nixos related though)

**Comment by prusnak** [comment]
I am almost positive this does not work as intended for NixOS. `process.execPath` will be somewhere in `~/.cache/appimage-run/hash` while the AppImage file can be anywhere on the filesystem. I think other OSes also run the process from $APPDIR (place where extracted contents of AppImage are placed), thus `process.execPath` never contains the directory where the AppImage file is placed in.

I don't think we should try to fix this in our code (and rather patch the appimage-run in NixOS to correctly set the APPIMAGE variable).

**Comment by keraf** [comment]
@prusnak Do you know if this issue is already being looked at/tracked on the Nixos repo? Should we keep this PR/issue open?

**Comment by prusnak** [comment]
I think we should close this.

The AppImage matter is much more complicated for NixOS and we'll solve this by providing the package for NixOS via nixpkgs.

**Comment by prusnak** [comment]
However, we might disable the whole autoupdater feature `if (process.platform === 'linux' && process.env.APPIMAGE === undefined)`.

Electron updater assumes this is set and does some stuff with the variable, so it makes sense to prevent the autoupdater accessing the var if it's not set.

**Comment by keraf** [comment]
@prusnak Good point! Closing this PR in favor of #3290

**Comment by bosomt** [comment]
maybe we can close this one as well ?
https://github.com/trezor/trezor-suite/issues/2962

**Pull request closed without merging**
