### PR TITLE
Feat/cj request headers

### LINKED ISSUE #7182: Make the requests from Suite to WabiSabi coordinator looks the same as those from Wasabi wallet
- We need to remove HTTP headers that node-fetch automatically add to requests in request filter before request and add them back to response (so node-fetch doesn't fail). Or we can consider some node-fetch alternative that would not add those headers.
- Check all requests to WabiSabi coordinator a complare those from Suite and Wasabi wallet (headers, params, ordering, delays, ...).
  -  How to do it - run Wasabi wallet, regtest, set localhost:8081/backend (our proxy) and log the request. Do the same with Suite. Compare. Align.

### PR DESCRIPTION
**Pull request by szymonlesisz**
## Description

To avoid disclosure that the request was sent by trezor-suite
remove headers added by underlying libs before they are sent to the server.
1. nodejs http always(!) adds "Connection: close" header
    https://github.com/nodejs/node/blob/e48763840625c037282681456ecd1e1cb034f636/lib/_http_outgoing.js#L508-L510
2. node-fetch always(!) adds "User-Agent", "Accept", "Connection"...
   https://github.com/node-fetch/node-fetch/blob/7b86e946b02dfdd28f4f8fca3d73a022cbb5ca1e/src/request.js#L226

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/7182

### CODE REVIEW

**Comment by matejkriz** [comment]
> Not sure about the naming for custom header (X-WabiSabi-Allowed-Headers). any suggestions?

It's not necessarily related to WabiSabi, is it? Right now we'll just use it for that, but theoretically it's applicable to any request. So what about just `X-Allowed-Headers` or `X-Allow-Headers` (similar to CORS headers)? 

Very nitpicky and rather philosophical - I just found out that `X-` prefix is kind of deprecated https://www.rfc-editor.org/rfc/rfc6648 so we can also use something like `Allow-Headers`.

**Comment by szymonlesisz** [comment]
cool, i've changed header name to `Allowed-Headers`, added some e2e tests to request manager (e2e tests are not running in the CI, you need to test it locally), rebased and forcepushed

**Review by marekrjpolak — APPROVED** [review]
After struggling with dev `console.log` using monkeypatched `net.Socket` as well which created strange recursion errors for me, I'm convinced this PR is actually correct.

The only thing is whether we want to log `INTERCEPTED_HEADERS` event or not, otherwise :shipit:

**Comment by szymonlesisz** [comment]
even if we do it could (and should) be done as standalone commit in suite-desktop, merging without it and i will added if we decide it's needed

**Pull request merged**
