### PR TITLE
Remove (defunct) option to create coinjoin account without Tor

### LINKED ISSUE #10287: Cannot add coinjoin account without Tor in dev mode
Adding coinjoin account in dev mode is allowed without running Tor. However, when I try to do it, there is an error in console and the account is then loading forever.

Skipping Tor:
Screenshot 2023-12-11 at 16 51 56

Console error:
Screenshot 2023-12-11 at 16 48 12

### PR DESCRIPTION
**Pull request by komret**
## Description

Creating coinjoin account without Tor does not work and it looks like no one is going to fix it. Removing useless code and misleading UI elements (button and debug settings switch).

The button is used in a [test](https://github.com/trezor/trezor-suite/blob/23267cce850d997d9d1f32f75d0735cabdc16878/packages/suite-desktop-core/e2e/tests/coinjoin.test.ts#L78), but I think the test does not work and never runs.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/10287

## Screenshots:
Screenshot 2024-02-13 at 13 25 49
Screenshot 2024-02-13 at 13 25 24

### CODE REVIEW

**Review by karliatto — CHANGES_REQUESTED** [review]
I think if we remove this that is used in test you mentioned https://github.com/trezor/trezor-suite/blob/23267cce850d997d9d1f32f75d0735cabdc16878/packages/suite-desktop-core/e2e/tests/coinjoin.test.ts#L78 we should either update the test and make it run at least nightly or totally remove the test if we consider it does not provide any value.

**Comment by mroz22** [comment]
I spent some time building this test 😿 . Maybe making it work would be better option 😹

**Comment by komret** [comment]
Blocked by https://www.notion.so/satoshilabs/Fix-coinjoin-test-9732a267572a48c7a479ca03e1792dc4.

**Comment by komret** [comment]
The test is not going to be fixed and since this PR is just removing code, I believe we can merge it, @karliatto.

**Comment by karliatto** [comment]
> The test is not going to be fixed and since this PR is just removing code, I believe we can merge it, @karliatto.

Ok. My only issue is with dead testing code https://github.com/trezor/trezor-suite/blob/23267cce850d997d9d1f32f75d0735cabdc16878/packages/suite-desktop-core/e2e/tests/coinjoin.test.ts#L78
If that code cannot run without this functionality we should get rid of it. It does not make sense to have code for tests that cannot be run and it is never run.

@komret why don't we remove the testing code and merge this PR?

**Comment by komret** [comment]
@karliatto, done.

**Review by karliatto — APPROVED** [review]

**Pull request merged**
