### PR TITLE
Coin control follow-up

### PR DESCRIPTION
**Pull request by komret**
Coin control improvements

## Description

- [x] add comments and tiny refactoring e01e2121c8308b6e7029e18589ca5c27d732a00d
- [x] hide "missing to your input" message when the amount is too big 06a62c58fd4e58cb08ede21df1137c1a4e58529f
- [x]hide "missing to your input" message when there is an error in the amount field other than "Not enough funds selected" 910ca36d019c5532c5f723cc4914ce6db55ee0a5
- [x] fix behaviour of the check-all checkbox when dust is involved 4a3db2c07f58439773b24587384651c72ad3767b
- [x] replace the "change address" message with an icon+tooltip

## Related Issue
#2770

**QA:** So far, this should only fix bugs reported by @bosomt and @STew790 on Slack. Plus there is a small UI change in how change address is displayed.

### CODE REVIEW

**Comment by STew790** [comment]
**QA OK**
`Missing to your input` message now hides correctly. `Check all` checkbox now behaves correctly with dust involved.
Checked on the coin-control-followup branch.

**Info:**
 - Suite version: web 22.9.0 (4a3db2c07f58439773b24587384651c72ad3767b)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.79 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.5.2 Universal (revision 0d87b55ba4fed7eecc72bf2a94ee473830b095e9)
 - Transport: bridge 2.0.32

**Comment by komret** [comment]
I added the "change address" icon. Let's review & merge.

**Review by matejkriz — APPROVED** [review]
👍

**Comment by komret** [comment]
@STew790 Regarding field validation with multiple recipients:
This is not directly related to Coin control. The reason validation behaves differently here is that the error comes from `utxo-lib` which composes the transaction. Every time any of the amounts change, all errors are cleared and `utxo-lib` attempts to compose a new transaction. If it results to an error, it is only linked to the last edited field. This behaviour can be observed even without Coin control enabled:
Screenshot 2022-09-09 at 14 05 45

This is how it has been working for some time now, I suggest keeping it as is. There are some cases when the error should be linked to multiple fields, but I think it is not a big deal because it is visible anyway.

**Pull request merged**
