### PR TITLE
chore: move version utils to @trezor/utils

### PR DESCRIPTION
**Pull request by mroz22**
This PR moves version utils from @trezor/rollout into @trezor/utils package.
There shouldn't be anything controversional. Mybe just that `version.ts` now contains multiple exports (like it did before). But @Nodonisko suggested that we should have one export per file - so I would like to see your opinion on this on.

### CODE REVIEW

**Comment by Nodonisko** [comment]
I would prefer solution where in index.ts >>
```ts
export * as versionUtils from './versionUtils.ts'
```

and then usage

```ts
import { versionUtils } from '@trezor/utils'

versionUtils.something();

or

const { something } = versionUtils;
something();
```

I also want to avoid direct import `from @trezor/utils/lib/...`  as much as possible, since we should maintain some public api of module exposed using `index.ts` because then we can easily refactor stucture of modules later and don't worry about breaking anything if we keep exposed function in `index.ts` same. This is like general good practice that is not only applying to `@trezor/utils` but all packages.

Also rename file to `versionUtils.ts` makes sense to me since it will be more obvious there is more that one function `version` in this file.

**Comment by mroz22** [comment]
sounds reasonable to me. please check fixup [f96a924](https://github.com/trezor/trezor-suite/pull/4870/commits/f96a924e27027a5f9cffe250607b3bf7f022cbbc)

**Comment by Nodonisko** [comment]
Also don't worry about including unused code in bundle, I will have ready PR that will make tree shaking for utils package perfectelly working.

**Comment by Nodonisko** [comment]
Looks great @mroz22

**Review by Nodonisko — APPROVED** [review]

**Pull request merged**
