### PR TITLE
feat(connect-common): add firmware binaries 1.10.4/2.4.3

### PR DESCRIPTION
**Pull request by vdovhanych**
This pr updates firmware binaries to the latest version.

### CODE REVIEW

**Review by mroz22 — APPROVED** [review]
looks similar to prev commit doing the same so probably alright 
https://github.com/trezor/trezor-suite/pull/4225/files

**Review by matejkriz — APPROVED** [review]
The binaries' fingerprints are equal to the fingerprints of binaries provided by stick 👌

**Comment by prusnak** [comment]
Let's not forget to send the same PR to the https://github.com/trezor/webwallet-data repo

**Comment by prusnak** [comment]
> Let's not forget to send the same PR to the https://github.com/trezor/webwallet-data repo

Done in https://github.com/trezor/webwallet-data/pull/32

**Pull request merged**
