### PR TITLE
chore(all): update to nodejs version 16

### PR DESCRIPTION
**Pull request by vdovhanych**
Update to `nodejs_16` 

React native build - I had to fork and build the react-native-android docker image as the upstream project is still on node14 and they do not want to update to 16 right now. Until they do let's use a fork. the issue here - https://github.com/react-native-community/docker-android/issues/172#event-6719133934

### CODE REVIEW

**Review by Nodonisko — APPROVED** [review]

**Comment by vdovhanych** [comment]
Not sure we can merge this, there are some connect tests on node version 14. Would that be something we can update so its runs with node16 as well?

**Comment by szymonlesisz** [comment]
afaik there are some 3rd party implementations using node 14 or [even lower](https://github.com/trezor/connect/pull/841#issuecomment-915123192), we should definitely test this.

however i think we can test it in separated environment, like testing only connect and connect-web npm package without whole monorepo setup.
i guess it's related to one of the subtask of #5505 (come up with a solution how not make sure we do not forget to release some of @trezor/connect dependencies.)

**Comment by vdovhanych** [comment]
This is ready for review and merge. All [connect tests on GitHub](https://github.com/trezor/trezor-suite/actions/runs/2535879691) are working, and all the builds are also working after the update. Node version in nix-shell is 16.15.0, and electron is 18.1.0

**Review by mroz22 — APPROVED** [review]

**Comment by mroz22** [comment]
Ha, it is breaking one e2e tests. I have an idea what might be going on there

**Comment by vdovhanych** [comment]
So this now works as expected, there is still one test failing, but I don't think it's related to this pr, right @mroz22?

**Pull request merged**
