### PR TITLE
chore(repo): upgrade to latest Node 22 LTS

### PR DESCRIPTION
**Pull request by Nodonisko**
## Related Issue

Resolve

### CODE REVIEW

**Comment by Nodonisko** [comment]
Can someone from Connect team fix that one failing build? @trezor/suite-connect

**Comment by mroz22** [comment]
yes. soon (days, not hours)

**Comment by mroz22** [comment]
I am not sure how this problem is related with update to the next node version and we are not seeing it in current builds. It looks like next.js is not able to prepare static builds because there are imports from react-lottie (via @trezor/components) that depend on `document` object.

```
ReferenceError: document is not defined
    at createTag (/Users//repos/trezor-suite/node_modules/lottie-web/build/player/lottie.js:30:5)
    at <unknown> (/Users//repos/trezor-suite/node_modules/lottie-web/build/player/lottie.js:1316:20)
    at <unknown> (/Users//repos/trezor-suite/node_modules/lottie-web/build/player/lottie.js:1323:6)
    at <unknown> (/Users//repos/trezor-suite/node_modules/lottie-web/build/player/lottie.js:1540:4)
    at <unknown> (/Users//repos/trezor-suite/node_modules/lottie-web/build/player/lottie.js:2:83)
    at Object.<anonymous> (/Users//repos/trezor-suite/node_modules/lottie-web/build/player/lottie.js:5:3)
   Collecting page data  .ReferenceError: document is not defined
    at createTag (/Users//repos/trezor-suite/node_modules/lottie-web/build/player/lottie.js:30:5)
    at <unknown> (/Users//repos/trezor-suite/node_modules/lottie-web/build/player/lottie.js:1316:20)
    at <unknown> (/Users//repos/trezor-suite/node_modules/lottie-web/build/player/lottie.js:1323:6)
    at <unknown> (/Users//repos/trezor-suite/node_modules/lottie-web/build/player/lottie.js:1540:4)
    at <unknown> (/Users//repos/trezor-suite/node_modules/lottie-web/build/player/lottie.js:2:83)
    at Object.<anonymous> (/Users//repos/trezor-suite/node_modules/lottie-web/build/player/lottie.js:5:3)

> Build error occurred

```

 Not sure, do we need to import everything from @trezor/components dynamically? 

```
import dynamic from 'next/dynamic';

const {Button }  = dynamic(() => import('@trezor/components'), { ssr: false });
```
? cc @martykan

**Comment by martykan** [comment]
I don't think dynamic imports would be a nice solution for this.

Seems like they are working on some fix in Lottie, but it's not released yet https://github.com/Gamote/lottie-react/issues/101
I would try the workaround with `NODE_OPTIONS="--no-experimental-global-navigator"`

**Review by mroz22 — APPROVED** [review]

**Pull request merged**
