### PR TITLE
chore(suite): remove cross-fetch, we dont need it as we use node18 everywhere

### LINKED ISSUE #10146: Remove cross-fetch lib as we use Node18 everywhere
- remove `cross-fetch`
- BEWARE of Timeout Issue. SEE: https://github.com/trezor/trezor-suite/pull/11820
- beware of https://github.com/trezor/trezor-suite/pull/10137

### PR DESCRIPTION
**Pull request by peter-sanderson**
## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/10146

### CODE REVIEW

**Comment by mroz22** [comment]
doesn't it break bridge communication for long lasting `/call` calls?

**Comment by martykan** [comment]
Yeah it had to be reverted last time (after a bunch of painful troubleshooting) 
https://github.com/trezor/trezor-suite/pull/11820

**Comment by peter-sanderson** [comment]
Ouch, lets wait for Node 19 then.

**Comment by marekrjpolak** [comment]
> Ouch, lets wait for Node 19 then.

And what will 19 change? What we need is unlimited timeout by default.

**Comment by peter-sanderson** [comment]
@marekrjpolak I was following on Komars message on Slack that we may try again when we upgrade node. 

> We can try removing cross-fetch again when we upgrade node.

**Pull request closed without merging**
