### PR TITLE
feat(suite): change the default target anonymity level to 5

### LINKED ISSUE #7730: Set default desired anonymity level to 5
We are conservative with anonymity calculation. Middleware will be changed to consider only taproot outputs for anonymity calculation, although Wasabi users will have randomised output scrip types (segwit/taproot)...
- We are aligning this default setting to Wasabi.

### PR DESCRIPTION
**Pull request by dahaca**
## Description

*  change the default target anonymity level to 5

I was considering writing a migration for remembered CJ accounts but there's no way to determine if `10` was the default one or the one users actually wanted.

## Related Issue

Resolve #7730

### CODE REVIEW

**Comment by matejkriz** [comment]
@dahaca could you please also update the colors of the slider as discussed in the issue https://github.com/trezor/trezor-suite/issues/7730#issuecomment-1449935609? 🙏

**Comment by matejkriz** [comment]
I believe there is no need for the migration.

**Comment by dahaca** [comment]
> @dahaca could you please also update the colors of the slider as discussed in the issue [#7730 (comment)](https://github.com/trezor/trezor-suite/issues/7730#issuecomment-1449935609)? 🙏

613cf877b

**Review by matejkriz — APPROVED** [review]
beware of the possible (small) conflict with https://github.com/trezor/trezor-suite/pull/7743

**Pull request merged**
