### PR TITLE
feat(connect-example): add serviceworker proxy to mv3 example

### PR DESCRIPTION
**Pull request by martykan**
## Description

Added webextension-proxy as an inline output. 
Updated the `webextension-mv3-sw` example to showcase the use of the proxy.

### CODE REVIEW

**Review by martykan — COMMENTED** [review]
I also think we could get rid of `webextension-mv3`

**Comment by mroz22** [comment]
> I also think we could get rid of webextension-mv3

probably yes, but maybe lets start with drafting documentation and we will see what kind of examples we want to refer actually

**Comment by martykan** [comment]
We could merge `webextension-mv3` and `webextension-mv3-sw` together, so it would have both the service worker proxy and iframe, just under another page. Main benefit is to simplify QA, would be 4 builds instead of 6

**Review by mroz22 — APPROVED** [review]

**Comment by martykan** [comment]
Found out we can't really combine those due to content script behavior, so I'd leave it for now as is

**Comment by karliatto** [comment]
> We could merge `webextension-mv3` and `webextension-mv3-sw` together, so it would have both the service worker proxy and iframe, just under another page. Main benefit is to simplify QA, would be 4 builds instead of 6

I think for QA the way to go should be to use the `connect-explorer/src-webextension`  and we can keep those examples here as simpler examples, that are easier to understand for developers.

**Comment by martykan** [comment]
Ok that makes sense

**Comment by martykan** [comment]
@mroz22 ok to merge now?

**Comment by martykan** [comment]
Oh I actually see the new release is not branched yet, I will merge it after

**Review by mroz22 — APPROVED** [review]

**Pull request merged**
