### PR TITLE
feat(desktop): maximize window with double click

### LINKED ISSUE #3796: MacOS: Resizing window with double-click
The double-click on the (black) navbar on MacOS desktop should enter full screen. Another double-click will resize the window back to the original size.

### PR DESCRIPTION
**Pull request by tomexx**
fixes #3796

### CODE REVIEW

**Comment by szymonlesisz** [comment]
i've noticed that double click works on Linux out of the box, @trezor/qa does it work on windows? 
i think this new code should it be only for macos in this case

**Review by tomasklim — COMMENTED** [review]
Works on MacOS. (Did not work without this feature) As @szymonlesisz says please confirm that it does not break Linux and Windows, or limit this feature to ```process.platform === 'darwin'```

**Comment by tomexx** [comment]
Please also check Windows.

**Comment by bosomt** [comment]
Works as expected in Windows 10 versions of Suite 21.3.2 and 21.5.1

**Comment by bosomt** [comment]
and works as expected in Mint Linux versions of Suite 21.3.2 and 21.5.1

**Review by tomasklim — APPROVED** [review]

**Pull request merged**
