### PR TITLE
Pr/ltc bech32

### LINKED ISSUE #3399: Litecoin - support for Bech32 address (native segwit)
**Is your feature request related to a problem? Please describe.**
Bech32 (native segwit) is supported for bitcoin in trezor-suite (thanks for this) but litecoin is sadly not yet supported, so it's not possible to use accounts starting with ltc prefix without using third party software.

**Describe the solution you'd like**
Support for Bech32 for litecoin in trezor-suite

**Describe alternatives you've considered**
Third party sw (electrum-ltc), but I really like trezor suite much more

### PR DESCRIPTION
**Pull request by szymonlesisz**
closes #3399

#### WEB MIGRATION
- open develop branch https://suite.corp.sldev.cz/suite-web/develop/web/accounts/#/ltc/0
- load LTC accounts
- remember device
- open current branch https://suite.corp.sldev.cz/suite-web/pr/ltc-bech32/web/accounts/#/ltc/0

Expected result: 
Accounts should be re-loaded (discovery progress bar visible)
`Litecoin #1` account is no longer the same, old one is moved to "segwit" section while new one addresses starts with `ltc1`

NOTE: your data should be gone if you open develop branch again

#### DESKTOP MIGRATION
similar to web
- open official release, load LTC accounts, remember device, close
- download installers from job artifact: https://gitlab.com/satoshilabs/trezor/trezor-suite/-/pipelines/278875204
- open downloaded app

#### SENDING
https://suite.corp.sldev.cz/suite-web/pr/ltc-bech32/web/accounts/#/ltc/0
- send from bech32 to segwit and legacy
- send from segwit and legacy to bech32
- try to use LTC1 addresses in upper case in send form (transformation should be offered)

### CODE REVIEW

**Comment by mcudev** [comment]
I reviewed these changes and tested the web migration. It looks good to me, and works as described/expected. I did my testing by switching branches in my local dev environment. I also verified that the migraton code is necessary. Without it, the accounts that should be only in the segwit section are in both the new normal/bech32 and segwit section, which would be confusing to users. Thanks for catching that!

**Comment by mcudev** [comment]
In my testing, the only thing I came across that made me think twice for a second was during the web migration tests, if i unplugged the device in between clicking to remember it and reloading the page to run the updated code, then the "normal" section was not populated with any accounts. This is reproducible with the mnemonic `all all all all all all all all all all all all` with the current transaction history. Since the device was unplugged, I shrugged it off (if it's a bug, it's minor -- I'm not sure it is, depends on user expectations for account discovery when the device is unplugged) and after I plugged it in, the account with no transaction history showed up. See the the screenshots below for an example of what I saw:

This is what I see after I unplug the device just before I reload the page to run the new code (this is all good):
Screenshot from 2021-03-30 12-02-54

Immediately after I run the new code with the device still unplugged, we can see that the normal section does not get an account populated (likely because there is no transaction history in it right now):
Screenshot from 2021-03-30 12-03-36

Here we can see that the other accounts were migrated correctly (the difference between this and the last screenshot is that I expanded the segwit and legacy account type sections to show them):
Screenshot from 2021-03-30 12-03-56

After I plug in the device and unlock it + enter passphrase, the new normal section populates as normally expected and then everything is totally normal:
Screenshot from 2021-03-30 12-04-24

**Comment by szymonlesisz** [comment]
from the architecture point of view this behavior is legit, account requested by url does not exist (yet)

i think this case is so rare that it does not require more fallbacks.
you have to use direct link `/ltc/X` do get here and "segwit" accounts are collapsed because of 0 balance.
assuming that you are a user with some coins on your account you will see them in "segwit" section immediately without need to expand it 

good catch tho :)

**Comment by mcudev** [comment]
I also just tested the desktop migration. Looks good to me. The only difference from the web migration that I noticed was that in the case where the user runs the updated code and then goes back to the previous version, the desktop app gets stuck at a white screen on startup and needs to be restarted before the wallet resets to being empty again. The web version worked without any extra step. This is probably not worth more changes. Just figured that I'd mention the observed difference (my desktop tests were done between the current develop and pr/ltc-bech32 branches in my dev environment).

**Comment by bosomt** [comment]
**QA OK**

Suite version 47f38ff53cb28c8d1e2953758b13140d81598cfa
Browser: firefox + app kubuntu 
Device 2.3.6 + 1.9.4

**Review by keraf — APPROVED** [review]

**Review by slowbackspace — APPROVED** [review]

**Pull request merged**
