### PR TITLE
fix(blockchain-link): check if available balance is zero before marki…

### LINKED ISSUE #3402: "Previous account is empty" despite non zero balance
**Describe the bug**
Suite won't discover additional accounts even though previous accounts are non empty and have transactions.

**Info:**
 - Suite Version: Desktop 21.2.2, [21.3.0](https://github.com/trezor/trezor-suite/tree/853dd4256ec7967501b97016d3fe46693ae374b5)
 - OS: NixOS unstable
 - Firmware Version: Model T, 2.3.4

**Steps to reproduce:**
1. Have ETH sitting in an account originating from a smart contract
2. Try to add additional accounts 

**Expected result:**
Addional accounts should be allowed to be added/discovered

**Actual result:**
Suite complains that previous accounts are empty

**Screenshots:**
Trezor_previous_empty

### PR DESCRIPTION
**Pull request by slowbackspace**
…ng account as empty

I believe something like this could fix https://github.com/trezor/trezor-suite/issues/3402

more testing needed

### CODE REVIEW

**Comment by shimunn** [comment]
Just tried 67a9c91 but no improvement:
Screenshot at 2021-02-16 15-47-43

**Comment by slowbackspace** [comment]
@shimunn This change is in a lib called blockchain-link which is used by trezor-connect (https://github.com/trezor/connect), simple checkout won't do the trick. If you want to try it on your own before it it'll be released, then you need to run connect locally, set suite to use this connect and manually link new updated dependency.

@szymonlesisz btw, confirmed that account.empty is really set to true.

**Review by szymonlesisz — APPROVED** [review]

**Comment by szymonlesisz** [comment]
yes, i've discussed with @martinboehm about that.
blockbook is not able to read inner smart contract transfers therefore account history is empty

**Comment by slowbackspace** [comment]
@szymonlesisz just fyi there is already an issue for that https://github.com/trezor/trezor-suite/issues/3057

**Pull request merged**
