### PR TITLE
fix(components): do not use camelCase props with animated.div

### LINKED ISSUE #4035: Unrecognized props on a DOM element
Resolve the warnings in dev mode:

> Warning: React does not recognize the `maxWidth` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `maxwidth` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

### PR DESCRIPTION
**Pull request by szymonlesisz**
fix https://github.com/trezor/trezor-suite/issues/4035

removes annoying console error

### CODE REVIEW

**Review by dimasivan — APPROVED** [review]
:+1:

**Comment by szymonlesisz** [comment]
i've added another commit which fix a new (not reported yet i guess it's related to `thuss-next`) react render error
Screenshot from 2021-08-05 14-39-10

cc: @pingpwned

**Comment by matejkriz** [comment]
cameCase props are not the real issue, the real issue is passing down props that are meant to be consumed only by styled-components and not the DOM node. 

There are couple of solutions for that, the newest and very easy to use is this:
https://styled-components.com/docs/api#transient-props

The other solution is this convention:
```javascript
// isActive prop will not be passed to Header component
const Title =
  styled <
  { isActive: boolean } >
  (({ isActive, ...rest }) => <Header {...rest} />)`
  color: ${(props) => (props.isActive ? props.theme.primaryColor : props.theme.secondaryColor)}
`;
```

**Comment by szymonlesisz** [comment]
thanks @matejkriz i didnt knew about `transient-props`, updated and force-pushed

**Review by matejkriz — APPROVED** [review]
🎉

**Pull request merged**
