### PR TITLE
fix(native-suite): bump expo from 50.0.7 to 50.0.17

### PR DESCRIPTION
**Pull request by legobeat**
## Description

Bump expo dependencies to latest non-breaking for bugfixes.

### CODE REVIEW

**Comment by legobeat** [comment]
@vytick @matejcik @juriczech @Nodonisko @matejkriz :slightly_smiling_face:

**Comment by legobeat** [comment]
[Failing](https://github.com/trezor/trezor-suite/actions/runs/8877288372/job/24373684849?pr=12179) `build-web` seems unrelated to changes in this PR and just come from the fact that this PR is a branch from a different repo?

```
# Configure aws credentials
Run aws-actions/configure-aws-credentials@v4
  with:
    role-to-assume: arn:aws:iam::538326561891:role/gh_actions_trezor_suite_dev_deploy
    aws-region: eu-central-1
    audience: sts.amazonaws.com
  env:
    DEV_SERVER_URL: https://dev.suite.sldev.cz/
    STAGING_SUITE_SERVER_URL: https://staging-suite.trezor.io/
It looks like you might be trying to authenticate with OIDC. Did you mean to set the `id-token` permission? If you are not trying to authenticate with OIDC and the action is working successfully, you can ignore this message.
Error: Credentials could not be loaded, please check your action inputs: Could not load credentials from any providers
```

Related: #12063

@vdovhanych @Nodonisko @komret

**Comment by legobeat** [comment]
Failing CI jobs are unrelated to the contents of this PR and are addressed in:
- #12233

**Comment by matejkriz** [comment]
Thank you pro your contribution, @legobeat, but we have our process to check dependencies and it's easier for us to update  in our own pace.

**Pull request closed without merging**
