### PR TITLE
Change qr code styles and size

### LINKED ISSUE #4503: QR code generated in receiving address dialog must be bigger
QR code generated in receiving address dialog must be bigger.

Currently it is quite small (~2cm x ~2cm) and very hard to scan from an (Android) phone = you need to put your phone very close to the screen to fill in the necessary space, but then the camera can't get focus and is unable to read the blurry code.

There is plenty of space. We can even position the QR code above the address:

before:

Screenshot 2021-11-14 at 11 28 40

after:

Screenshot 2021-11-14 at 11 28 40-after

### PR DESCRIPTION
**Pull request by maciejrrr**
I passed bigger size(default 128) for better qr code quality and changed styles. It look good on desktop and mobile. This pr should be linked to [issue](https://github.com/trezor/trezor-suite/issues/4503)
Screenshot from 2022-01-20 16-14-09
Screenshot from 2022-01-20 16-15-11

### CODE REVIEW

**Comment by prusnak** [comment]
Nice! @mradziwon Please make the white border around the QR code wider - so it is at least the width of one box-pixel of the QR code. That's what the standard requires.

**Comment by maciejrrr** [comment]
@prusnak is it better now?
Screenshot from 2022-01-22 18-30-28

**Comment by prusnak** [comment]
> @prusnak is it better now?

Yes

**Comment by tomasklim** [comment]
Thank you for your contribution! I made some changes to unify the design of xpub and address QR modals
Screenshot 2022-01-24 at 13 10 23

**Comment by maciejrrr** [comment]
@tomasklim oops, sorry for breaking the commit convention. I'll stick to it next time :)

**Comment by tomasklim** [comment]
> @tomasklim oops, sorry for breaking the commit convention. I'll stick to it next time :)

Thank you! If you plan to contribute again in the near future, please also do not use `#` in the branch name. We found out that we have some issues with it in Cypress CI jobs and we need to investigate the problem

**Pull request closed without merging**
