### PR TITLE
Do not merge feat(connect): T3T1 colors revamp

### PR DESCRIPTION
**Pull request by MiroslavProchazka**
Updating colors of T3T1 based on instruction from HW team

### CODE REVIEW

**Review by mroz22 — APPROVED** [review]
@tomasklim didn't you intend to keep this information in trezor-common?

**Comment by MiroslavProchazka** [comment]
Please do not merge this yet, we need to revisit the btc-only FW logic. So this might need additional commits.

**Comment by MiroslavProchazka** [comment]
Aaaand we are turning back

**Comment by tomasklim** [comment]
@MiroslavProchazka what's wrong with this? We do not need to do that

**Comment by tomasklim** [comment]
@mroz22 yes but noone ever updated the trezor-common repo 😀

**Pull request closed without merging**
