### PR TITLE
IndexedDB migrations refactoring - part 1

### PR DESCRIPTION
**Pull request by marekrjpolak**
## Description

First part of long-sleeping migrations refactoring (previously in #6431).

Splitting the migrations into files and other possible improvements left for followups.

## Commits

- https://github.com/trezor/trezor-suite/pull/8684/commits/f7ba8f3b12e4020aa20c5c3b3f9f746ce4ad91e5 - create `updateAll` util for iterating over object stores; replace the recurring object store iteration pattern in migrations with `updateAll`
- https://github.com/trezor/trezor-suite/pull/8684/commits/cec9119e3954a9f68d0792af5f86446b155c394c - try to polish the migration to v28 a bit; it deletes and recreates `accounts`, `txs`, `graph` and `discovery` object stores; now it uses `store.getAll()` instead of reading one by one
- https://github.com/trezor/trezor-suite/pull/8684/commits/580a679aaa8edc84095b4510bb248e87fab896a1 - DB initialization is now equivalent to migrating from the oldest supported version, therefore duplicate `createObjectStore` etc. is not needed anymore.

## How to test
No idea. Have fun. :trollface:

### CODE REVIEW

**Review by mroz22 — APPROVED** [review]
I like the idea, therefore approve. Lets wait for CI and maybe @matejkriz could have a look too?

**Comment by matejkriz** [comment]
@marekrjpolak Can be tested by installing old Suite, remembering wallet, changing settings and then launching this version, right?

**Comment by mroz22** [comment]
best to test together with this https://github.com/trezor/trezor-suite/pull/8646
there are still some old release branches online https://suite.corp.sldev.cz/suite-web/release/ 
also there is e2e test but it tests only limited subset of migrated data https://gitlab.com/satoshilabs/trezor/trezor-suite/-/jobs/4462957695/artifacts/file/packages/suite-web/e2e/videos/database-migration.test.ts.mp4

**Comment by marekrjpolak** [comment]
> @marekrjpolak Can be tested by installing old Suite, remembering wallet, changing settings and then launching this version, right?

More or less, yes. But to test it exhaustively you'd have to a) migrate from all possible versions and b) have all the kinds of data stored from that versions (custom backends, metadata, txs with tokens, ...)

But it's probably ok to **QA OK** when migration from some arbitrarily chosen version with arbitrary data succeeds. :man_shrugging:

**Comment by bosomt** [comment]
@mroz22 please ping us when your PR is merged too so we can test it.
I will create Notion task.

**Comment by bosomt** [comment]
**QA OK**

https://www.notion.so/satoshilabs/IndexedDB-migrations-251bc11242b64fb5a5dd0d4e0de247b3?pvs=4

**Info:**
 - Suite version: desktop 23.7.0 (d81e7e2a7c127bc4e494b69375831cd4b0998bd8)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.7.0 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.6.1 Universal (revision c3f6e8f19fd647c73b414322e287ba23cf8a0c7c)
 - Transport: BridgeTransport 2.0.33

**Pull request merged**
