### PR TITLE
fix(connect): stream pollyfills

### PR DESCRIPTION
**Pull request by PeKne**
fix build error of `connect-web` and `connect-explorer` caused by `stream` pollyfills.

### CODE REVIEW

**Comment by martykan** [comment]
Do we know where this error was introduced? Seems like it worked until https://github.com/trezor/trezor-suite/commit/4cb98c8d51aa35675f54759aae5ffb2a27776d48 but I don't see changes that would affect connect?

**Comment by PeKne** [comment]
@martykan It is probably caused by `suite-common/validators` importing `wallet-utils`.

**Comment by martykan** [comment]
Ok, I see it probably got in through `@trezor/components`. Still a fail in the CI

**Comment by martykan** [comment]
A better fix would be to tree shake, so `wallet-utils` doesn't get into components where it doesn't need to be.
Eg. like this: 
Screenshot 2024-02-05 at 14 02 51

**Comment by mroz22** [comment]
@martykan points correctly that at the moment we might be bundling uneeded code into iframe. I would be keen to find differences in our bundle size https://github.com/trezor/trezor-suite/blob/develop/packages/connect-web/scripts/check-inline-build-size.sh#L0-L1

**Comment by PeKne** [comment]
@mroz22 Bundle size seems to be all right:
Screenshot 2024-02-05 at 13 26 38

If I run this on develop before merging the breaking commit, it shows the same size (232)

**Comment by martykan** [comment]
My main concern wasn't bundle size, I think it's better to fix it at the origin rather than patch it in webpack for a bunch of unrelated packages.

**Comment by Nodonisko** [comment]
> @martykan points correctly that at the moment we might be bundling uneeded code into iframe. I would be keen to find differences in our bundle size https://github.com/trezor/trezor-suite/blob/develop/packages/connect-web/scripts/check-inline-build-size.sh#L0-L1

If it's not builded package, it should be esmodule so it should be treeshaked correctly.

**Review by martykan — APPROVED** [review]
Build is green 👍

**Comment by PeKne** [comment]
After discussion with @Nodonisko I've decided to use the quick-fix proposed by @martykan. Even though it is not ideal, @Nodonisko will be doing some tree shaking improvements soon, so he will revisit this particular piece of code later.

**Pull request merged**
