### PR TITLE
@trezor/address-validator

### PR DESCRIPTION
**Pull request by mroz22**
this is far from complete but I'd like to open it anyway. 

lets move trezor-address-validator to monorepo. 

there is one test failing when in monorepo and passing in standalone repo. I don't get it 😱

### CODE REVIEW

**Comment by mroz22** [comment]
ok, finally found what was the problem = strict mode + [missing const](https://github.com/trezor/trezor-address-validator/blob/master/src/bitcoin_validator.js#L110)

now it should work. but I started questioning if it makes much sense to move it into the monorepo

cons:
- touching whats not broken
- touching something that we didn't need to touch for years
- diverging from the upstream more and more

pros: 
- when we need to touch it it will be easier to maintain

**Comment by mroz22** [comment]
@SocketSecurity ignore npm/envinfo@7.13.0 

this alert doesn't seem related to this PR at all

**Review by szymonlesisz — APPROVED** [review]
looks legit :+1:

**Pull request merged**
