### PR TITLE
Move deprecated Storybook option to config

### PR DESCRIPTION
**Pull request by komret**
## Description

Gets rid of a deprecation warning. Docs: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated---static-dir-cli-flag

### CODE REVIEW

**Comment by tomasklim** [comment]
> https://gitlab.com/satoshilabs/trezor/trezor-suite/-/jobs/4166667847

https://gitlab.com/satoshilabs/trezor/trezor-suite/-/jobs/4182387618
Screenshot 2023-04-27 at 15 13 09
still failing even after rebase

**Comment by komret** [comment]
@mroz22 can the rsync fail be related to the CI changes you have made recently?

**Comment by mroz22** [comment]
not very likely. after my changes components deploy job should run less often https://github.com/trezor/trezor-suite/pull/8197/files

**Comment by komret** [comment]
I re-ran it now, and it works 🤯 , @tomasklim

**Review by tomasklim — APPROVED** [review]

**Pull request merged**
