### PR TITLE
chore: remove unused messages

### PR DESCRIPTION
**Pull request by mroz22**
unused invity messages

### CODE REVIEW

**Comment by mroz22** [comment]
aha, 
they are not actually unused but created dynamically and detection script is not clever enought to tell

```
                    id={`TR_SAVINGS_OVERVIEW_WAITING_FOR_FIRST_${uppercasePaymentMethod}_PAYMENT_HEADER`}

```

**Comment by yanascz** [comment]
> aha, they are not actually unused but created dynamically and detection script is not clever enought to tell

That's correct, I added these yesterday.

**Comment by mroz22** [comment]
Imho there should be some kind of detection for unused strings so that we don't overload translators with unused messages. 

Should we: 
A] improve detection script somehow? 
or 
B] rewrite the code in more static manner?

**Comment by mroz22** [comment]
there is already one way to do it, mark them `dynamic: true` in messages.ts

**Comment by yanascz** [comment]
> there is already one way to do it, mark them `dynamic: true` in messages.ts

OK, thanks, will use this property next time. Is there any action needed from me now?

**Comment by mroz22** [comment]
nope, I wil lhandle it

**Review by matejkriz — APPROVED** [review]

**Pull request merged**
