### PR TITLE
fix(suite-native): send transaction detail redirect

### PR DESCRIPTION
**Pull request by PeKne**
## Description
- The redirect from the send review to the transaction detail happens after the transaction is processed by a backend. This fix prevents navigation to the transaction details before getting the transaction metadata from the backend, which leads to a blank screen being rendered.

## Demo
https://github.com/user-attachments/assets/aff7cf4a-c1d1-48f4-a07d-378fab4edcf1

### CODE REVIEW

**Review by vytick — APPROVED** [review]
lgtm 👍

**Comment by evgenysl** [comment]
Was sending POL and got white screen (2 out of 2 times) after this Pending screen.

Screenshot_20241113_143218_Trezor Suite Lite Develop


**Version**
24.11.1 https://github.com/trezor/trezor-suite/commit/35433e7d5213f924061bc36bb74edf017bd39db0

**Comment by evgenysl** [comment]
Retested on 24.11.2 (752) Last commit hash: 76f75ed71146a6c5624723bbf711482828111e44
Same bug.

**Comment by matejkriz** [comment]
@evgenysl Could you please retest this eventually?

**Comment by evgenysl** [comment]
sent POL, ended up on Confirmed screen
QA OK

**Info:**
25.3.1 ffe3145

**Pull request merged**
