### PR TITLE
Feat/new tx detail modal design

### PR DESCRIPTION
**Pull request by robertbrada**
Fix part of https://github.com/trezor/trezor-suite/issues/2326

New Transaction Detail modal design according to [Zeplin design](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/screen/5f58c5c02d9ce80796cda6ae)

### CODE REVIEW

**Review by keraf — APPROVED** [review]

**Comment by slowbackspace** [comment]
I faked some values and grid cols collapsed as each row is using separate grid. There should be only one grid definition as it will allow grid cols to automatically expand based on max width of all cells in a given column.
I think I'l let it pass since it is part of the "show fiat" workaround that I am not fan of 😬 and it will need proper design fix.
 
screenshot showing broken grid cols:
Screenshot 2020-09-24 at 12 39 06


screenshot showing that this workaround doesn't really work on mobile screens anyway.
Screenshot 2020-09-24 at 11 40 32

**Comment by slowbackspace** [comment]
fixed few things and synced intl (someone apparently manually edited generated language files and save them with different formatting, that's why there is a crazy number of diff lines).

**Review by slowbackspace — APPROVED** [review]

**Comment by slowbackspace** [comment]
@robertbrada you can decide if you want to fix the grid cols issue or we'll fix it once we get proper design for it. 😁

**Review by slowbackspace — APPROVED** [review]

**Comment by slowbackspace** [comment]
@keraf let's merge it!

**Pull request merged**
