### PR TITLE
`getFeatures` timeout fix

### PR DESCRIPTION
**Pull request by marekrjpolak**
## Description

Since we add `checkFirmwareHash`, `checkFirmwareRevision` and `changeLanguage` into `getFeatures` call, initial device acquiring often fails because of `GetFeatures timeout`, resulting in various issues. By moving this logic after the `getFeatures`/`initialize` call in `_runInner`, we could improve it a lot without (hopefully) changing anything else.

Example: With PIN-protected device, following happened:
- start Suite with webusb, unlock the device and let discovery finish
- lock the device and refresh Suite
- `checkFirmwareHash` inside `getFeatures` requires entering PIN, which cannot be done during the 3s timeout, resulting in recursive `_runInner` call and `initialize` call sent over other messages, which usually made device unreadable

### CODE REVIEW

**Review by mroz22 — COMMENTED** [review]
🤔  we just need to agree on that we don't need this logic to happen in the  "finalReload" of features after each call.

**Comment by marekrjpolak** [comment]
> we just need to agree on that we don't need this logic to happen in the "finalReload" of features after each call.

Right @mroz22. This is not 100% equivalent. Do you think it's possible that some of the three mentioned actions would fail before the inner fn call, but succeed afterwards? And if it does, that it poses a security risk to wait until the next device.run instead?

**Comment by mroz22** [comment]
not sure, I am more afraid of not doing something that  @Lemonexe  might be relying on. Lets ask him.

 Also #15675 is sort-of related because it might be attempt to fix something that this PR is preventing.

**Review by mroz22 — APPROVED** [review]
I am totally good with it as long as @Lemonexe confirms that it doesn't beak anything for him

**Review by Lemonexe — APPROVED** [review]
LGTM :rocket:
I have tested both hash  & revision check extensively, all cases work as before, I haven't noticed any issues :heavy_check_mark: 

Hash check
- `success` (physical T2T1, T1B1, T2B1 latest all the same time)
- `hash-mismatch` (user env T2T1 2.8.1, T1B1 1.12.1)
- `check-unsupported` (user env T2T1 2.7.2, 2.3.0, T1B1 1.10.5)
- `unknown-release` (user env 2-main, 1-main)


Revision check:
- `success` (physical T2T1, T1B1, T2B1 latest all the same time, several user env releases)
- `revision-mismatch` (user env T2T1 2.3.0)
- `firmware-version-unknown` (user env 2-main, 1-main)
- `other-error` (2-main without internet (should be `cannot-perform-check-offline` but that's a known bug))

**Comment by mroz22** [comment]
In that case :shipit:

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 25.1.0 (a552ac45e894db3cf8ab9dab49a040b3c98f7132)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.6 regular (revision 688bddc887b8bb660640cc6e40a99036f2e87f1f)
 - Transport: WebUsbTransport

**Pull request merged**
