### PR TITLE
chore(message-system): add banner for deprecated coins

### PR DESCRIPTION
**Pull request by MiroslavProchazka**
This PR  implements a message system banner that will inform users about the deprecation of Dash, Bitcoin Gold, Namecoin, Vertcoin, and DigiByte.

For the first time, this banner will also be included in the mobile app. I’ve set the minimum version as 24.9.1 @matejkriz, please confirm if that’s correct.

Some additional details:
	•	“priority”: 93
	•	“dismissible”: true
	•	“variant”: “warning”
	•	“category”: “banner”

Translations were proofread by ChatGPT o1, so they should be reliable. The “Learn more” link will direct users to KB article sitting on "https://trezor.io/learn/a/deprecated-coins", which is currently in preparation.

I've also lowered priority on POL banner as it was clashing between each other.

Tracked in Notion in [here](https://www.notion.so/satoshilabs/Suite-coins-deprecation-10cdc5260606807e92b2c3867ef9cf3d?pvs=4)

Tested on **`release-message-system-develop`** by QA, slack thread [here](https://satoshilabs.slack.com/archives/CKYFBT2C9/p1727352279546489)

Suite 
image

Mobile
image

### CODE REVIEW

**Comment by tomasklim** [comment]
How about creating one message mentioning all deprecating coins? This means that if user has all coins enabled, he will see 5 almost same messages

**Comment by MiroslavProchazka** [comment]
> How about creating one message mentioning all deprecating coins? This means that if user has all coins enabled, he will see 5 almost same messages

In that case we would need to display  all affected coins in the message, which will definitely prolong it. 

Also I'm not sure whether this would work (to have several coins in the settings, but I will try).

**Comment by vytick** [comment]
@MiroslavProchazka fyi: there is no intention to deploy that message to production. It was testing message

**Comment by tomasklim** [comment]
@MiroslavProchazka it should work
and you can use network symbols instead of names 

I would rather see `BTG` instead of `Bitcoin Gold`

**Review by vytick — APPROVED** [review]
lgtm :)

**Pull request merged**
