### PR TITLE
Feat/taproot

### PR DESCRIPTION
**Pull request by szymonlesisz**
- [x] wiki Taproot page

- [x] account banner copy
account-banner

- [x] "Add Account" Taproot copy (when available + when unavailable)
add-account

Screenshot from 2021-11-11 08-46-09

- [x] Taproot account details copy and account naming "Native Segwit v1" ?
aacount-details

- [x] Taproot address validation when unavailable (older FW)
send-to-tr-old-fw

### CODE REVIEW

**Comment by bosomt** [comment]
**QA OK**

_Bitcoin testnet_

FW branch 406371632
Suite branch 4ce460d759d6d27e88d101531245ed547406a8cd

Send tx - OK
Bump tx - OK
Lower amount via fee bump - OK
Finalize tx  - OK
Add account - OK
Receive address - OK
Show XPUB  - OK
Sign and verify - **NOK** - not implemented yet  - _Sign message error: Unsupported script type_
Account and add account Wiki info linked to https://wiki.trezor.io/Taproot - **NOK** - NA available yet
Info when taproot not available in old FW - OK

**Comment by bosomt** [comment]
**QA OK**

Bitcoin 

FW Branch 44ea5e41
SUITE BRANCH /suite-web/feat/taproot/web/

Send tx - OK
Bump tx - OK
Finalize tx - OK
Add account - OK
Receive address - OK
Show XPUB - OK

**Comment by szymonlesisz** [comment]
- sign/verify should be disabled for taproot accounts
- it should work with T1 from [this branch](https://github.com/trezor/trezor-firmware/tree/andrewkozlik/taproot-legacy)

**Comment by bosomt** [comment]
- Sign and verify disabled
 - receive, send,bump, lower amount, finalize **QA OK** 

**Info:**
 - Suite version: web 21.12.0 (ec355e323e5d6b06c685a59c7d3e8eb47487ec5f)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:94.0) Gecko/20100101 Firefox/94.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.10.4 regular

**Comment by szymonlesisz** [comment]
account xpub/bitcoin descriptor range changed from `{0,1}` to `<0;1>` compatible with bitcoind [proposed format](https://github.com/bitcoin/bitcoin/pull/22838)

**Comment by wendys-cats** [comment]
**T1 production test**
receive address OK bc1pullhyxt939nrdjlw9f2jwx69enhn0jk0s72859y08pqgcze53v6s5ge0tw
send (from tr to tr) OK here 
bump fee OK here 
finalise OK here 
Previous test results present [here](https://app.asana.com/0/0/1201359043943383/1201364774410883/f)

 - Suite version: web 21.12.0 (57e6ce95cb5dd5b3215885f7e6d2ea9ddb80d270)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
 - OS: Win32
 - Screen: 1920x1080
 - Device: model 1 1.10.4 regular

**Review by mroz22 — APPROVED** [review]

**Pull request merged**
