### PR TITLE
fix(connect): proceed with fw install even when language data fails t…

### PR DESCRIPTION
**Pull request by mroz22**
…o download

tested it by setting connect to download language data from some bogus url. it went through. 

image

is there an issue?

### CODE REVIEW

**Review by komret — APPROVED** [review]

**Comment by Hannsek** [comment]
Does user have to update the language manually or will it be automatic the next fw update?

**Comment by mroz22** [comment]
it will update automatically under the hood when he connects device next time, or maybe even triggers next connect call

**Comment by Hannsek** [comment]
Will the user have to confirm it? Confirm the installation of the language blob?

**Comment by bosomt** [comment]
Tested on 24.6.3 latest release candidate

**Comment by komret** [comment]
> Will the user have to confirm it? Confirm the installation of the language blob?

No, the update is silent.

**Comment by Hannsek** [comment]
So the language of the firmware will be changed automatically during the next fw update? This is not nice. :/

**Comment by komret** [comment]
No, it should never change. If an outdated blob is detected, it attempts to silently update to the same language. If there is no translation blob, nothing happens.

Not sure how much this was tested though.

**Comment by Hannsek** [comment]
Not sure if the firmware accepts the blob silently. @matejcik?

**Comment by matejcik** [comment]
what @komret says: Suite is always allowed to _silently_ update an outdated language blob to one matching the current language + version

**Pull request merged**
