### PR TITLE
WIP: Ci/optimize native e2e

### PR DESCRIPTION
**Pull request by PeKne**
## Description
Optimizes the android e2e ci pipeline so the .apk file is builded only if needed (when native dependecies change). In case that only JS code is changed, new JS is bundled and injected to the existing .apk.

This improvement reduces the duration of build step to only about 25%. Originally the build took [around 24 minutes](https://github.com/trezor/trezor-suite/actions/runs/12110362949). Now only about [6 minutes](https://github.com/trezor/trezor-suite/actions/runs/12160985660?pr=12630).

### CODE REVIEW

**Review by Nodonisko — APPROVED** [review]
Lgtm

**Comment by PeKne** [comment]
@SocketSecurity ignore npm/@react-native-community/cli@15.1.2

**Comment by PeKne** [comment]
https://github.com/SocketSecurity ignore npm/@react-native-community/cli-config-android@15.1.2

**Comment by PeKne** [comment]
@SocketSecurity ignore npm/@react-native-community/cli-config-android@15.1.2

**Pull request merged**
