### PR TITLE
Add support for .crypto resolution

### LINKED ISSUE #3498: Support Unstoppable Domains
I know some will prefer FIO or something else, but I would like to suggest adding support on integrating Unstoppable Domains

- Support .zil and .crypto addresses
- Ability to buy multiple unstoppable domains with crypto in the app 
- Ability to transfer multiple unstoppable domains to another address in the app
- Ability to add crypto addresses to multiple unstoppable domains in the app
- Ability to send crypto to an unstoppable domain address in the app

I prefer Unstoppable Domains since they are a one time purchase and you have it for life unlike FIO addresses, they are human readable and can help with adoption by being able to tell others were to send crypto to. Unstoppable domains can be used for other things like hosting IPFS stuff but I dont see a need for Trezor to support all of that, just for the ability to register, transfer domains and be able to easily accept crypto using a unstoppable domain.

Trezor will be a great wallet to store and manage your unstoppable domains securely

EDIT:
ZIL support is not really need as much since Unstoppable Domains now supports up to 9 different domain extensions that are available on the Ethereum blockchain which are

.crypto
.coin
.wallet
.bitcoin
.x
.888
.nft
.dao
.blockchain

### PR DESCRIPTION
**Pull request by sudoryan**
I’m submitting a pull request to add support for sending crypto via blockchain domains in Trezor Wallet. Trezor Wallet is consistently one of the most requested integrations by our users. You can find a list of wallets that currently support this functionality on our website - https://unstoppabledomains.com/. We have registered over 300,000 .crypto and .zil domains since last March. We are also happy to provide your team with a grant to compensate for any time you spend on this PR.

To test, enter brad.crypto into the address field when sending from Ethereum Wallet

This PR adds a single dependency for ABI encoding/decoding - @ethersproject/abi

### CODE REVIEW

**Comment by prusnak** [comment]
@sudoryan Do you think you'll be available to also add Pull Request to [Trezor Firmware](https://github.com/trezor/trezor-firmware) (`core` subfolder) ? It makes sense to show .crypto address also on Trezor, otherwise an user has no way to confirm the address on the device, which is quite unfortunate. Also Trezor needs to be able to validate the cryptography proof the address is indeed mapped to that .crypto name.

**Comment by DeRain** [comment]
@prusnak Is Trezor Firmware able to read from Ethereum Smart Contract? If yes - then adding this functionality won't take long. Add domain records are stored inside Smart Contract and you can read them directly. Should be enough to check the address validity.

> @sudoryan Do you think you'll be available to also add Pull Request to [Trezor Firmware](https://github.com/trezor/trezor-firmware) (`core` subfolder) ? It makes sense to show .crypto address also on Trezor, otherwise an user has no way to confirm the address on the device, which is quite unfortunate. Also Trezor needs to be able to validate the cryptography proof the address is indeed mapped to that .crypto name.

**Comment by prusnak** [comment]
> Is Trezor Firmware able to read from Ethereum Smart Contract?

Trezor is an offline device. You need to be able to fetch the data from smart contract and send it to Trezor, so it can verify the data's validity while staying offline.

**Comment by trymeouteh** [comment]
Please add support for other domains such as .wallet .nft .x .blockchain .coin

**Comment by hynek-jina** [comment]
This PR is out of sync for a long time. I’m closing it until further improvement.

**Comment by prusnak** [comment]
> This PR is out of sync for a long time. I’m closing it until further improvement.

Also it does not make sense without the counterpart implemented on the Trezor device - having domains resolution only in the Suite is false sense of security unless it is implemented also in the Trezor firmware and that is much bigger task.

**Pull request closed without merging**
