### PR TITLE
fix(dropbox): fix metadata files location for scoped app

### LINKED ISSUE #2636: Labels/metadata from the (old) web wallet are not present in the new Trezor Suite wallet
I'm just testing new beta 20.10.1 with model T updated to latest firmware. I was able to give the desktop app permissions to access my dropbox but I don't see existing labels.

1. I can see labels proper when visiting wallet.trezor.io with the same device
2. I don't see labels when using trezor suite wallet with connected dropbox

The suite desktop app in SETTINGS > LABELING shows:
```
Connected to Dropbox as <NAME>
Your labeling is synced with cloud storage provider. Your data are safe, only your Trezor can decrypt them.

[Disconnect]
```

I would expect the old labels to work. 
Or is there a reason to keep them separate? 
In that case I would appreciate some tool to convert labels to the new system. 
Thanks for clarification. I'm excited about this new development.

**Info:**
 - OS: macOS 10.15.7
 - Browser: N/A
 - Wallet Version: beta 20.10.1
 - Firmware Version: model T FW@2.3.4

btw. I can provide a log. I skimmed it briefly and it looks to me that the label metadata is not retrieved, only some new metadata was created related to `@account/create` events. I tried to close and open wallet app again. Same result.

### PR DESCRIPTION
**Pull request by prusnak**
Hopefully fixes https://github.com/trezor/trezor-suite/issues/2636

The error is caused by scoped vs unscoped Dropbox app

@mroz22 this is the idea for the fix I described:
* we look for the files both in in the `/` and `/Apps/TREZOR` folders while reading
* if it is in the first one => good, let's use this location
* if it's in the second one => ok, let's use this location
* if not found in any location =>  fail
* we always write to the `/` location, so eventually all files will be migrated from `/Apps/TREZOR` back to `/`

**This is completely untested, just sharing the draft with you - please comment, review and test. Thanks!**

### CODE REVIEW

**Comment by mroz22** [comment]
looks good! Let me finish it.

**Comment by tsusanka** [comment]
Shouldn't we rather migrate (copy the date) from the legacy location to the new one? That way we will be able to remove this code eventually.

**Comment by prusnak** [comment]
Please also inspect this possibility: https://github.com/trezor/trezor-suite/issues/2648

**Comment by mroz22** [comment]
> Shouldn't we rather migrate (copy the date) from the legacy location to the new one? That way we will be able to remove this code eventually.

Imho it makes no difference because you can't guarantee that the affected user would connect. Technically there is no way to both prevent possible data loss and remove the code some day in future.

**Comment by tsusanka** [comment]
> Imho it makes no difference because you can't guarantee that the affected user would connect. Technically there is no way to both prevent possible data loss and remove the code some day in future.

In theory I agree. But I think it is a fair thing to do in several years, because you can always ask the user to use older Suite to migrate. And then in 5 years when we rewrite Suite in yet another JS framework we will not have to deal with this obscurity :P. Just my five cents..

**Review by szymonlesisz — CHANGES_REQUESTED** [review]
pls squash the "fixup!" commit

**Review by keraf — APPROVED** [review]

**Review by szymonlesisz — APPROVED** [review]

**Pull request merged**
