### PR TITLE
suite-storage simultaneous db.addItem

### PR DESCRIPTION
**Pull request by mroz22**
fix unexpected concurrent initiation of db

### CODE REVIEW

**Comment by mroz22** [comment]
@marekrjpolak implemented proposed chagnes
not sure about this [791b387](https://github.com/trezor/trezor-suite/pull/8761/commits/791b387fae4dbee80433293a3ec5bfa461ccf060) better to make promise executor async and await getDb()?

**Comment by marekrjpolak** [comment]
> @marekrjpolak implemented proposed chagnes not sure about this [791b387](https://github.com/trezor/trezor-suite/pull/8761/commits/791b387fae4dbee80433293a3ec5bfa461ccf060) better to make promise executor async and await getDb()?

Fuuuuu, I forgot about this. You can try
<pre>getDB = () => {
    if (this.db) return <strong>Promise.resolve</strong>(this.db);
    ...
}
</pre>

**Comment by mroz22** [comment]
> 
> Fuuuuu, I forgot about this. You can try
> 
> getDB = () => {
>     if (this.db) return **Promise.resolve**(this.db);
>     ...
> }

good idea, it seems to work

**Review by marekrjpolak — APPROVED** [review]

**Pull request merged**
