### PR TITLE
Chore/icon cleanup

### PR DESCRIPTION
**Pull request by komret**
SVG icon cleanup

## Description

This PR follows up on changes introduced in #6223 and completes the SVG cleanup and optimisation.

- `README` in `@trezor/components` now has a brief manual on adding new SVGs 45b30eab3e46b3628220491e3d44a36ef6862fc3
- current components have been edited according to the manual (minified, cropped, stripped from unused properties, converted to fills wherever possible) 2259d2b627007b3b505f07e863dd96f030064d05
- four duplicated icons (near identical to another icon used in Suite) have been deleted f73e54c0b0665d43ae62d744e404259cb57a535a

**QA:** Apologies for doing this in two steps. Please check that no icons look broken - mostly in colour, size or alignment. There should be no meaningful changes in UI.

### CODE REVIEW

**Review by marekrjpolak — COMMENTED** [review]
What (and where) I've noticed so far (not necessarily bugs, may be intentional):

#### In local file manager:
- `article.svg` is gray
- `eyeClosed.svg` seems strangely transformed (there was some partial transparency before?)
- `shuffle.svg` is gray

#### in Storybook:
- `GITHUB` icon not visible
- `GOOGLE_DRIVE` icon looks cropped

**Comment by komret** [comment]
3249ab7811e52a14a738f2ec484f7230ab389528 should fix Google Drive, Dropbox and Github icons. The rest is defined by strokes and the converter is failing so I asked Ondra to fix them. Marking this issue as blocked until then.

**Review by dahaca — APPROVED** [review]

**Comment by komret** [comment]
Ondra supplied new icons so it should be all uniform now. @marekrjpolak please approve and I will merge it.

**Review by marekrjpolak — APPROVED** [review]
:shipit:

**Comment by bosomt** [comment]
Checking dev master.  Found few missing .png files.
Is it related of its part of different issue ?

**Info:**
 - Suite version: web 22.10.0 (af17a9477147f168d409e657d27a4af954fdf544)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:105.0) Gecko/20100101 Firefox/105.0
 - OS: MacIntel
 - Screen: 1848x1155
 - Device: model T 2.4.2 Universal (revision 9276b1702361f70e094286e2f89e919d8a230d5c)
 - Transport: bridge 2.0.32

404
https://suite.corp.sldev.cz/static/guide/assets/Settings_Change_PIN-highlight.png
https://suite.corp.sldev.cz/static/guide/assets/PIN_Change_OK.png
https://suite.corp.sldev.cz/static/guide/assets/FW-menu.png
https://suite.corp.sldev.cz/static/guide/assets/FW-menu-2.png
https://suite.corp.sldev.cz/static/guide/assets/EAP_icon_highlight.png
https://suite.corp.sldev.cz/static/guide/assets/Save_Bitcoin-HL.png
https://suite.corp.sldev.cz/static/guide/assets/First_time_prompt_cropped.png
https://suite.corp.sldev.cz/static/guide/assets/Go_to_account.png
https://suite.corp.sldev.cz/static/guide/assets/Suite_send-form.png
https://suite.corp.sldev.cz/static/guide/assets/Autofill_form_button.png
https://suite.corp.sldev.cz/static/guide/assets/SignVerify_highlight.png
https://suite.corp.sldev.cz/static/guide/assets/Format_Electrum.png
https://suite.corp.sldev.cz/static/guide/assets/SignVerify_highlight.png
https://suite.corp.sldev.cz/static/guide/assets/Send_Fee_2dp.png

**Comment by komret** [comment]
@bosomt No, this issue is only related to SVG files. The images in Guide are fetched by the `build:lib` script that is currently broken, @Nodonisko is working on it. At least I think it is related.

**Comment by Nodonisko** [comment]
It's broken only for one specific package `@trezor/message-types` other packages should work.

**Comment by Nodonisko** [comment]
Also Nx is used only for CI validation step, currently it has nothing to do with build of application where nothing is cached and everything is run, so it should not be cause of issue.

**Comment by tomasklim** [comment]
~~It is probably related to https://github.com/trezor/trezor-suite/pull/6406/commits/489bdfbd17acb42d254c06dd4c303322826da303 
I will check it on Monday, because locally it is working~~

The images address is incorrectly prefixed. I will check it on Monday

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 22.10.0 (1c1917c1f4fca65b408ea0abc35fc41b29f096b2)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:105.0) Gecko/20100101 Firefox/105.0
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model 1 1.8.3 Universal (revision df0963ec48f01f3d07ffca556e21ff0070cab099)
 - Transport: bridge 2.0.31

**Pull request merged**
