### PR TITLE
Update URL for Syscoin UTXO

### PR DESCRIPTION
**Pull request by fernando-syslabs**
New official URL for Syscoin UTXO:

## Related Issue

Also doing this one: https://github.com/trezor/trezor-firmware/pull/3612 (MERGED)

### CODE REVIEW

**Comment by mroz22** [comment]
Hi Fernando. I understand that outdated data should be probably updated. But still, could  you please explain what is your usecase for this syslcoin? are you personally using it?

**Comment by fernando-syslabs** [comment]
Thanks for asking @mroz22, I'm DevRel for Syscoin and we are winding down the old blockbook.elint.services which will make many clients unusable unless they update to the new official blockbook.syscoin.org.

You can validate my involvement with Syscoin over here: https://syscoin.org/news/behind-the-blockchain-fernando  My @develcuy account (that I use for commits) is linked in that article

**Comment by DevElCuy** [comment]
@mroz22, I confirm that @fernando-syslabs is my other account.

**Comment by fernando-syslabs** [comment]
Follow up, https://github.com/trezor/trezor-firmware/pull/3612 is merged for some time already. How can we help to get this one merged?

**Comment by mroz22** [comment]
ok, this change is not controversial I'd say. but could you please explain your motivation for it?

**Comment by fernando-syslabs** [comment]
@mroz22, the whole explorer and RPC at https://blockbook.elint.services will be shutdown soon since we have migrated to new infrastructure already. Also, we don't control that domain name and can't guarantee the accuracy of anything coming from there

**Review by mroz22 — APPROVED** [review]
I meant more like what makes you mantain some syscoin. 

but ok whatever, lets merge this.

**Comment by mroz22** [comment]
ah, sorry, I was too eager to click "update branch" could you please rebase and remove the merge commit?

**Pull request closed without merging**
