### PR TITLE
fix(suite-native): view only enabling for no biometrics allowed

### PR DESCRIPTION
**Pull request by vytick**
If device does not have available biometrics, do not wait for it to be resolved before showing EnableViewOnlyBottomSheet for the device

### CODE REVIEW

**Review by juriczech — APPROVED** [review]

**Review by matejkriz — CHANGES_REQUESTED** [review]
It breaks the e2e test, please fix the test 🙏

**Comment by matejkriz** [comment]
> It breaks the e2e test, please fix the test 🙏

Test fixed and global retries count for mobile E2E tests lowered on 2 so we don't need to wait so long and waste resources. If it fails 2 times, makes not much sense to retry more. cc @PeKne

**Review by matejkriz — APPROVED** [review]

**Comment by PeKne** [comment]
@matejkriz  Ok, let's see if the tests gonna be flakier now. But 5 retries was definitely overkill. 👍

**Comment by vytick** [comment]
Thanks for fixing the tests!

**Pull request merged**
