### PR TITLE
feat: fee per byte improvements

### LINKED ISSUE #5907: Fee rate has changed - notify user in transaction modal
Problem
1. user enters custom fee rate into send form
2. with given feerate an output lower than dust would need to be created so this output is omitted and actual fee rate is different
3. user still sees the same fee rate in transaction overview modal

Proposed solution
if we detect that the actual fee rate is different we should:
- do not change fee rate in user input
Custom Fee Entry

- do change fee rate shown in transaction overview modal
- show tooltip in transaction overview modal with an explanation why fee rate is different
Modal

### PR DESCRIPTION
**Pull request by mroz22**
This PR aims to solve inconsistency between fee rate displayed in suite and on device

## Description

- 261817b90075531f1be5bfd32e99eaceeafda661 removes code responsible for keeping the same fee rate which was typed into custom input 
- todo: explain to users why final fee rate does not match fee rate from the input. probably some tooltip? the reasons may be:
  - change output would be below dust limit.
  - there is not enough funds to create change output 
- todo: rounding in suite differs from rounding on device

## Related Issue

should resolve https://github.com/trezor/trezor-suite/issues/5907
related to https://github.com/trezor/trezor-firmware/issues/2438

cc @sime 

## Screenshots:

Before: 
image

image

After: 
image

image

### CODE REVIEW

**Comment by sime** [comment]
Design to inform the user about the increase in fee. https://www.figma.com/file/l0gG9XeRJ8FTDQ3cfb1wv9/Trezor-T%2C-Trezor-One?node-id=3539%3A10964

**Comment by sime** [comment]
Design and copy is done on Figma. (Original design has an info (i) icon which I just hid)

**Comment by dahaca** [comment]
Should the copy be changed from "fee rate" to "gas price" and "fee" for other comments or this blue notification will only be relevant for BTC?

**Comment by dahaca** [comment]
@b-irving The copy here seems off. @mroz22 could you comment on that?

image

**Review by dahaca — APPROVED** [review]

**Pull request merged**
