### PR TITLE
Update electron and node

### LINKED ISSUE #8876: Dependencies: electron-builder
electron-builder@24.4.0 breaks win build: https://gitlab.com/satoshilabs/trezor/trezor-suite/-/jobs/4605482050

https://github.com/electron-userland/electron-builder/issues/7652

### PR DESCRIPTION
**Pull request by tomasklim**
## Description

- updated electron to version 26
- electron 24 will be depracated next month and there are some security issues in the version we use https://github.com/trezor/trezor-suite/security/dependabot/182 so good to update anyway
- updated node to current LTS
- updated relevant electron/desktop app libs
- there was Electron type change between v24 and v25 
If you have better idea how to fix types, let me know, just create diff of ⬇️ 
[electron-typings.zip](https://github.com/trezor/trezor-suite/files/12646049/electron-typings.zip)

There should be no breaking changes relevant for us and no new features

https://www.electronjs.org/blog
https://nodejs.org/en/blog/release

## Related Issue

Closes https://github.com/trezor/trezor-suite/issues/8876
Partially https://github.com/trezor/trezor-suite/issues/9402
Closes #9480

### CODE REVIEW

**Comment by tomasklim** [comment]
@trezor/qa please test if desktop apps are working on windows/linux/macos before merging

@marekrjpolak please test that dev works on develop

**Comment by tomasklim** [comment]
After merge:
- [x] inform about node version change

**Comment by tomasklim** [comment]
@SocketSecurity ignore app-builder-lib@24.6.4
@SocketSecurity ignore electron-publish@24.5.0
@SocketSecurity ignore buffer-equal@1.0.1
@SocketSecurity ignore @types/glob@8.1.0
@SocketSecurity ignore @electron/asar@3.2.4
@SocketSecurity ignore dir-compare@3.3.0

**Comment by bosomt** [comment]
**QA OK**

tested on all platforms see

https://www.notion.so/satoshilabs/updated-electron-to-version-26-bf7458e4549e42afac91389cfd4a8a19?pvs=4

**Comment by marekrjpolak** [comment]
> @marekrjpolak please test that dev works on develop

Seems good.

**Review by vdovhanych — APPROVED** [review]

**Pull request merged**
