### PR TITLE
test(e2e): improve bridge page test

### PR DESCRIPTION
**Pull request by mroz22**

### CODE REVIEW

**Comment by mroz22** [comment]
I am curious if the snapshots I generated on my machine will match those captured by CI. Could you please run this for me @wendys-cats ?

**Comment by slowbackspace** [comment]
What I find weird is, how it is possible that it started being so glitchy just now? Nobody touched that ever, and for the past 2 days there were a lot of fails for this one. I am scared there is more into it.

**Comment by mroz22** [comment]
No idea what might have changed. It seems to me that the "loading" part is changing its height as the animation runs, so the screenshot may render different results depending on when its taken. Oddity of why it started to happen right now remains unanswered.

**Comment by mroz22** [comment]
https://gitlab.com/satoshilabs/trezor/trezor-suite/-/jobs/1066052435/artifacts/file/packages/integration-tests/projects/suite-web/snapshots/suite/bridge.test.ts/__diff_output__/udev%20rules%20modal.diff.png

Ah, thanks for runnig this https://gitlab.com/satoshilabs/trezor/trezor-suite/-/jobs/1065716360 I'll update snapshots later if you don't do it before me.

**Comment by mroz22** [comment]
please please could somebody trigger CI with those updated snapshots?

**Comment by slowbackspace** [comment]
> please please could somebody trigger CI with those updated snapshots?

https://gitlab.com/satoshilabs/trezor/trezor-suite/-/pipelines/266991308, hm install job is failing.

**Comment by mroz22** [comment]
Maybe adminkos could help.

**Comment by slowbackspace** [comment]
merged via https://github.com/trezor/trezor-suite/pull/3514 🎉

**Pull request closed without merging**
