### PR TITLE
fix(passphrase): fix behaviour of backspace/del if carret not at the end

### LINKED ISSUE #2807: Weird behavior in the passphrase input
Test case:

1. write some words

image

2. move cursor

image

3. click backspace

image

### PR DESCRIPTION
**Pull request by mroz22**
- should fix #2807 
- modified the passphrase e2e test to cover unexpected behavior in #2807

### CODE REVIEW

**Review by slowbackspace — CHANGES_REQUESTED** [review]
https://slack-files.com/T0J8V2YBY-F01EDPZJP6C-1001b1c817
😛

**Comment by mroz22** [comment]
Fixed and submitted QA request, let's see how it goes.

**Review by keraf — APPROVED** [review]

**Review by keraf — CHANGES_REQUESTED** [review]
Adding a character in the middle of a hidden passphrase will add the character in the correct place but then move the cursor to the end of the passphrase.

Not sure if that's clear enough but for example when I type 1234, then put the cursor in the middle, and type 5678, it shows 12534678.

**Comment by mroz22** [comment]
> Adding a character in the middle of a hidden passphrase will add the character in the correct place but then move the cursor to the end of the passphrase.

Thanks, looking at this. This is actually another bug, not a regression.

**Review by szymonlesisz — APPROVED** [review]

**Comment by mroz22** [comment]
Fixed (hopefully) all the reported cases. I needed to take control over the caret and set its position in useEffect as rerender that happend after switching from obfuscated view (dots) to normal view caused it to jump to the end. Maybe somebody can come with a better idea. So far it seems it works, at least according to the tests and some manual clicking by myself.

**Review by szymonlesisz — APPROVED** [review]

**Comment by sorooris** [comment]
**QA OK**

Couldn't replicate the issue, compared to suite.trezor.io (99959260d5639480dfb11e53a4f2ab1d789b0e7b) to observe the incorrect behavior.

Browser: Chromium 86.0.4240.111
OS: NixOS 20.09
Firmware Version: model T 2.3.4 50854b921

**Pull request merged**
