### PR TITLE
feat: add Trade to app menu with coming soon badge

### LINKED ISSUE #2552: Add new Account tab: Trade [SOON]
Note: The copy will likely change, add it to Crowdin please. 

- [ ]  Tab "Trade" (disabled of course)
- [ ]  Tag "SOON" as shown on the Exchange, Spend sub-tab 

[Zeplin](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/screen/5f7eeac0813e4db7e7d0eaef)

### PR DESCRIPTION
**Pull request by slowbackspace**
close https://github.com/trezor/trezor-suite/issues/2552

### CODE REVIEW

**Comment by tsusanka** [comment]
Is this intentionally a draft PR?

**Comment by slowbackspace** [comment]
@tsusanka yup, waiting for a CI to pass 😛

**Comment by tsusanka** [comment]
The misc job fails on :

```
$ ts-node ./test/test-same-svgs.ts
checking total svgs: 58
Detected that project includes multiple same svgs, exiting with 1
[ [ 'coinmarket-error.svg', 'uni-error.svg' ] ]
```

That sounds like smth worth fixing I guess? :)

**Comment by slowbackspace** [comment]
> The misc job fails on :
> 
> ```
> $ ts-node ./test/test-same-svgs.ts
> checking total svgs: 58
> Detected that project includes multiple same svgs, exiting with 1
> [ [ 'coinmarket-error.svg', 'uni-error.svg' ] ]
> ```
> 
> That sounds like smth worth fixing I guess? :)

That sounds like something out of scope for this PR, but we can fix it later :)

**Comment by tsusanka** [comment]
Ah apologies, I thought it was introduced by this PR. Now I see it was there in develop before already.

**Review by mroz22 — APPROVED** [review]
looks good

**Pull request merged**
