### PR TITLE
fix(blockchain-link): electrum txs pagination

### LINKED ISSUE #5512: Transactions do not show in account, but balance is correct/Custom Backend
Latest Transaction BTC is missing when connected to electrum server backend. When opening Suite web version or Trezor backend it shows correctly. Also total amount of BTC in that account is shown correctly. When i search for the transaction ID in Suite it shows up, but disappears again and doesnot show in my account. Whats up with this?

### LINKED ISSUE #5577: I don't see all transactions when connected to custom electrum server (umbrel)
**Describe the bug**
When I connect to any electrum server (umbrel, cryptoanarchy debian repository), I don't see the very recent transactions in Trezor Suite history. I don't experience this with Trezor backend.

I've found out that the .csv and .pdf export differs when using Trezor backend and my electrum server which I think may be cause by the same problem. The .csv is complete though but the order of transaction is not correct.

Using a Trezor backend the transaction order is from newest to oldest. When I use custom electrum server, the order seems pretty random which I think is the problem (not sure if the electrum server returns a wrong order of transactions or the Trezor suite does not sort it correctly).

**Info:**

-   Remembered Wallet: no
-   Suite Version: app, [v22.5.3](https://github.com/trezor/trezor-suite/releases/tag/v22.5.3)
-   OS: macOS, Monterey 12.4 (21F79)
-   Firmware Version: Trezor T, [version/commit](https://github.com/trezor/trezor-firmware/commit/85a26d2c9593bcdf858c2d718d79951ca927a0c3)

**How to reproduce**

1. Connect umbrel electrum server
2. Go to your Bitcoin account
3. Scroll down to transactions
4. See there are only a few, e.g. from 2021 or 2020 but not the very recent

**Expected behavior**
I would expect the same result when connecting electrum server as the Trezor backend.

**Screenshots**
Trezor backend (transaction dates)
trezor_suite_trezor_backend

Custom electrum backend (transaction dates)
trezor_suite_electrum_server

### PR DESCRIPTION
**Pull request by marekrjpolak**
Should fix #5512, should fix #5577 and other issues regarding transaction list with Electrum backend. 

The only thing changed is the pagination content returned in `getAccountInfo` response from `electrum` worker.

 __QA:__
Please, check that:
- the transaction lists (including order of transactions except for txs in the same block) are the same with Blockbook and custom Electrum backend, even on big accounts (>25 txs needed to test the pagination)
- nothing regarding txs list breaks when sending/receiving transactions with Electrum backend.
- tx exports and searching works as well

### CODE REVIEW

**Review by mroz22 — APPROVED** [review]

**Comment by Alex71btc** [comment]
I also noticed when custom backend is connected, there is only one transaction history page displayed at all, when connected to trezor backends, there are 5 pages of transaction history, but with custon, there is no option to browse further pages,the option of the green page numbers st the bottom is just missing. Could this be part of the issue?

**Comment by marekrjpolak** [comment]
> I also noticed when custom backend is connected, there is only one transaction history page displayed at all, when connected to trezor backends, there are 5 pages of transaction history, but with custon, there is no option to browse further pages,the option of the green page numbers st the bottom is just missing. Could this be part of the issue?

Hello @Funman2, it is indeed. There were in fact two unrelated issues. The first one regarding tx sorting had been fixed (but possibly not released) before you reported the issue. Today I merged fix for the second one regarding missing pagination. I hope it'll be tested and released soon.

**Comment by Alex71btc** [comment]
👍🙏👊

**Comment by Alex71btc** [comment]
All Issues are solved now by latest update! Thanks very much guys!

**Pull request merged**
