### PR TITLE
feat(coinmarket): rename exchange to swap

### LINKED ISSUE #14103: Split Trade button and rename Exchange to Swap
## Description
To follow industry standards where most self-custody wallets call coin-to-coin exchange a “swap”. Additionally, in testing, we saw a significant uplift in confidence and easier-to-find trade features when the navigation buttons were separate for fiat-crypto and coin-to-coin operations.
Add also an analytics event on Swap - `wallet-coinmarket-exchange` (`accounts/actions`)

## Solution
- Account detail - header: Split Trade button into “Buy & Sell” (it will lead to the Buy tab) and “Swap” (it will lead to the former Exchange tab)
- Account detail - trade box: Rename Exchange for Swap
- Trade screen tabs: Rename Exchange for Swap
- Rename input and transaction labels
- Update modal content for CEX and DEX

### Split buttons
image
### Replaced button title from `Exchange` to `Swap`
image
### Replaced label from `Exchange amount` to `Swap amount`
image
### Replaced tab title from `Exchange` to `Swap` and updated icon
image
### Replaced `Exchange` button title with `Swap`
image
### Replaced `exchange` strings with `swap` (CEX)
image
### Replaced `exchange` strings with `swap` (DEX)
image
### Replaced `Exchange` label with `Swap` (DEX)
image

### PR DESCRIPTION
**Pull request by adderpositive**
## Description
To follow industry standards where most self-custody wallets call coin-to-coin exchange a “swap”. Additionally, in testing, we saw a significant uplift in confidence and easier-to-find trade features when the navigation buttons were separate for fiat-crypto and coin-to-coin operations.
Add also an analytics event on Swap - `wallet-coinmarket-exchange` (`accounts/actions`)

## Solution
- Account detail - header: Split Trade button into “Buy & Sell” (it will lead to the Buy tab) and “Swap” (it will lead to the former Exchange tab)
- Account detail - trade box: Rename Exchange for Swap
- Trade screen tabs: Rename Exchange for Swap
- Rename input and transaction labels
- Update modal content for CEX and DEX

### Split buttons
image
### Replaced button title from `Exchange` to `Swap`
image
### Replaced label from `Exchange amount` to `Swap amount`
image
### Replaced tab title from `Exchange` to `Swap` and updated icon
image
### Replaced `Exchange` button title with `Swap`
image
### Replaced `exchange` strings with `swap` (CEX)
image
### Replaced `exchange` strings with `swap` (DEX)
image
### Replaced `Exchange` label with `Swap` (DEX)
image

## Related Issue
Resolve https://github.com/trezor/trezor-suite/issues/14103

### CODE REVIEW

**Review by komret — CHANGES_REQUESTED** [review]
Adding a new button to the account section needs to be backed by the product team. Otherwise all good.

**Comment by adderpositive** [comment]
> Adding a new button to the account section needs to be backed by the product team. Otherwise all good.

@marek-andrsk @MiroslavProchazka

**Review by LukasRada — APPROVED** [review]
LGTM but let's assign the button(s) to a relevant people.

> Adding a new button to the account section needs to be backed by the product team. Otherwise all good.

**Comment by marek-andrsk** [comment]
Should be cleared out, so we can proceed with merging this PR please 🙏

**Review by komret — APPROVED** [review]

**Pull request merged**
