### PR TITLE
Introduce docs directory and document versioning

### PR DESCRIPTION
**Pull request by tsusanka**
Introduce docs directory and document versioning. Fits a format that [mdbook](https://github.com/rust-lang/mdBook) is able to build into nice HTML. I will also file an issue to adminkos to build the docs to docs.trezor.io, the very same way we have it for [firmware](https://docs.trezor.io/trezor-firmware).

Some docs cleanup later would be nice as well.

### CODE REVIEW

**Comment by mroz22** [comment]
yeah, there are "tons" of docs scattered all over the project. Would be greate to have unified structure for this. This is a good start and we may migrate over time

**Comment by tsusanka** [comment]
Great. Is everyone okay with the versioning we are suggesting?

**Comment by keraf** [comment]
> Great. Is everyone okay with the versioning we are suggesting?

I understand the logic but I can't tell what's a beta or stable release just from looking at the version number. In your example, .1 and .2 are stable but following this logic I might think that .3 is stable too. We'll be probably labeling them as beta somewhere but I'd still favour a suffix for non-stable releases, makes it easier to identify from just looking at the file name for example.

**Comment by tsusanka** [comment]
I said the same but @prusnak was against.

**Comment by prusnak** [comment]
We also discussed this scheme:

```
- `20.10.1` first release on Oct 15th to stable
- `20.10.2` second release on Oct 22nd to stable
- `20.11.0` release on Oct 29th 2020 to beta
- `20.11.0` another release on Nov 5th to beta
- `20.11.1` public release on Nov 14th to stable
```

* every release on beta has `0` as the patch version - this has a drawback that you can't distinguish deployments by a version number, but beta testers should be able to read  and report the commit hash.
* beta has +1 MM version when compared to stable  - indicating this is upcoming release which will be deployed on stable next month
* only stable releases have patch version >1 and this increases with each stable release: 1, 2, 3, 4

**Comment by tsusanka** [comment]
@prusnak I like that. We could also do `20.11.0.[beta-version]` but it seems redundant. Suite also prints the commit hash so I think `.0` is just fine.

**Comment by tsusanka** [comment]
Agreed on Product meeting we will go with https://github.com/trezor/trezor-suite/pull/2427#issuecomment-701468379. I will amend this PR shortly.

**Comment by tsusanka** [comment]
Amended. @keraf @szymonlesisz @mroz22 please ACK (all you need to read is @prusnak's commit) and let's merge it.

**Review by szymonlesisz — APPROVED** [review]

**Pull request merged**
