### PR TITLE
fix(invity): Exchange Receiving address ExtraField requires interaction

### LINKED ISSUE #3037: Exchange Receiving address ExtraField requires interaction
**Describe the bug**

During Receiving address step in Exchange of certain coins/tokens (f.e. exchange to XMR, XML, XRP  - ones with additional info input field with name ExtraField) user needs to interact with ExtraField to continue with transaction. These additional input fields vary for each coin (f.e.Destination Tag, Memo ID and so on), but are usually described as "another way to indentify the transaction you will receive" and they are not supposed to be mandatory. 
User needs to either enter valid input into this field to enable Continue transaction, or can go around this issue by entering ANY input into the field (EVEN invalid) and then deleting it. 

**Info:**
 - Suite Version: web 20.12 96ed993c70f5597a37aef244e495e3f97dfff2f5
 - Browser: Chromium Version 86.0.4240.111 (Official Build) (64-bit)
 - OS: NixOS 21.03 Okapi
 - Firmware Version: 1.9.3 public

**Steps to reproduce:**
1. Choose account with reasonable balance
2. Go to Accounts > Trade > Exchange
3. Initiate exchange for a coin that allows the ExtraField

**Expected result:**

User should not be forced to tamper with a field input that is not mandatory. 

**Actual result:**

Transaction for an exchange that allows ExtraField will not be completed unless user tampers with ExtraField. 

**video:** https://drive.google.com/file/d/143xlE9eWJB8DkGKP6i1jjPd7m_WJ9fRl/view

**Screenshots:** ExtraField has the Payment ID nameplate here
image

### PR DESCRIPTION
**Pull request by martinboehm**
Fixes #3037.

### CODE REVIEW

**Review by tomexx — APPROVED** [review]

**Comment by keraf** [comment]
I'm a bit skeptical about this fix, I can't really see how that fixes the issue.

**Comment by martinboehm** [comment]
Great! I wanted to see if somebody notices! 

It is totally strange but it does fix the problem. When I was debugging it, just adding console.log(formState.isValid) to the component fixed the problem. There was actually nothing wrong in the code even before the fix, however in certain cases it did not rerender the component on the change of the formState.

I do not have time to investigate react or react-use-form quirks but if somebody would explain to me what is going on, I would really appreciate it.

**Comment by szymonlesisz** [comment]
`formState` [in use-form](https://github.com/react-hook-form/react-hook-form/blob/master/src/useForm.ts#L155) lib is a `ref` so react tree will not re-render on change

**Comment by martinboehm** [comment]
@szymonlesisz Thanks. In that case it explains, why the fix works.

**Review by szymonlesisz — APPROVED** [review]

**Pull request merged**
