### PR TITLE
chore(code): Deduplicate modules, reduce node_modules size by 50%

### LINKED ISSUE #4501: Investigate the use of yarn-deduplicate
Yarn v2 deduplicates automatically, but since we are stuck with Yarn v1 for now, we could investigate the use of [yarn-deduplicate](https://www.npmjs.com/package/yarn-deduplicate).

The reason why I started to look into this was the following fragment from `yarn.lock`:

```
electron@*:
  version "12.0.0"
  resolved "https://registry.yarnpkg.com/electron/-/electron-12.0.0.tgz#b3b1d88cc64622e59c637521da5a6b6ab4df4eb5"
  integrity sha512-p6oxZ4LG82hopPGAsIMOjyoL49fr6cexyFNH0kADA9Yf+mJ72DN7bjvBG+6V7r6QKhwYgsSsW8RpxBeVOUbxVQ==
  dependencies:
    "@electron/get" "^1.0.1"
    "@types/node" "^14.6.2"
    extract-zip "^1.0.3"

electron@^15.3.0:
  version "15.3.0"
  resolved "https://registry.yarnpkg.com/electron/-/electron-15.3.0.tgz#f9803c5a05b2dac12efc6d4203492c7e204b4819"
  integrity sha512-YLzaKCFmSniNlz9+NUTNs7ssPyDc+bYOCYZ0b/D6DjVkOeIFz4SR8EYKqlOc8TcqlDNu18BbWqz6zbJPyAAURg==
  dependencies:
    "@electron/get" "^1.13.0"
    "@types/node" "^14.6.2"
    extract-zip "^1.0.3"
```

To me, it seems there is no reason why electron 12.0.0 should be in the `yarn.lock`, when obviously `*` can be resolved to `15.3.0` as well.

I tried running `yarn-deduplicate` and to my surprise it generated quite a lot of optimisations.

I pushed these changes into the [`yarn-deduplicate` branch](https://github.com/trezor/trezor-suite/compare/yarn-deduplicate)

Since these are supposed to be reviewed by someone who actually understands the yarn build system, I am not creating a pull request and rather just creating this issue for someone else to pick this up.

### PR DESCRIPTION
**Pull request by Nodonisko**
This will `npx yarn-deduplicate` used packages and reduce size of `node_modules` by 50%.

Important: `suite-desktop` and `suite-web` seems to work, other needs to tested before merge but I don't expect any issues.

Before:
Screenshot 2022-01-17 at 20 42 44

After:
Screenshot 2022-01-17 at 20 44 20

// edit 18.1.2021
- fixed error in `suite-desktop` caused by using old types before deduplication
- fixed version of `ws` in blockchain-link, bumped to exact version `ws@7.4.6`. Tt was used here before according to yarn.lock so this is just cosmetic change, not real version change happened. Highier version will cause some error - maybe they are not following sem ver?

// edit 18.1.2021 vol.2
- just note: `yarn-deduplicate` also has `exclude` option so in case of any problems with any package we can easily exclude that package from deduplication

Closes #4501

### CODE REVIEW

**Comment by mroz22** [comment]
you can check here for some of the problems it has in CI https://github.com/trezor/trezor-suite/pull/4711/files I did not run numbers in that branch but my guess is that deduplication maybe does something similar to what `yarn upgrade` does but without bumping packages versions?

**Comment by Nodonisko** [comment]
@mroz22 Partially yes, but primary goal is to merge deps of your deps where you will never be able to unify versions because you can't change package.json inside node_modules. Also yarn internally deduplicate during `yarn install` but this doesn't work like this tool: https://www.npmjs.com/package/yarn-deduplicate#why-is-this-necessary

This probably won't be totally painless but we definitely should follow this tool (as guide for and what upgrading) because size reduction is really significant. Also this tool could be used in CI to watch for adding duplicated deps and throw error.

I used to much agressive unification strategy where also major version were bumped, and that is not good. I will try it with less agressive strategy.

**Comment by Nodonisko** [comment]
This is good example what it is doing, all version here were safe to merge to one:
Screenshot 2022-01-17 at 22 00 07

**Comment by Nodonisko** [comment]
It looks that tool actually discovered hidden issue caused by duplicated dependencies. Look what error TS is now throwing in `packages/suite-desktop/src-electron/app.ts`:

Screenshot 2022-01-17 at 22 08 20

This `enableRemoteModule` was removed since Electron v14, but according to `package.json` we should use `"electron": "^15.3.0",` so issue was there only TS was not throwing because it probably used types from Electron v12 that was also in deps for some reason.

**Comment by Nodonisko** [comment]
All know errors should be resolved now.

This PR will require some little more intensive testing because this tool should be used incrementally with every added dependency, not in one huge run.

**Review by matejkriz — CHANGES_REQUESTED** [review]
please do not merge before https://github.com/trezor/trezor-suite/pull/4711

**Review by matejkriz — APPROVED** [review]

**Pull request merged**
