### PR TITLE
Disable Anonymize button when there is nothing to coinjoin

### LINKED ISSUE #6818: Disable anonymization when there is nothing to anonymize
Disable the "Anonymize" button when:
- account has 0 balance
- target anonymity is 1
- all UTXOs are anonymous (not sure about this one @hynek-jina, someone might want to run it again for some reason)

### PR DESCRIPTION
**Pull request by komret**
## Description

ddf2dab81821bb18d14a65c27e1934fb0df4b679 disables the button on main page when there is no `availableBalance`. Anonymity is not checked here because it may be changed on the following strategy page. there is no tooltip, but it should be self-explanatory. I was not entirely sure whether I should check `availableBalance` or `balance`, though.

c88151cea9f50ca15861a52edb6f6ea0e4315bcf disables the button starting coinjoin if there are no non-private funds. The tooltip instructs the user to add funds or increase anonymity level if they want to coinjoin.

## Related Issue

Resolve #6818

## Screenshots (if appropriate):
Main page:
image

Strategy:
image

### CODE REVIEW

**Comment by dahaca** [comment]
From Figma 
image

**Comment by komret** [comment]
I will replace the button with text. The text is not very fitting when there is 0 balance though.

**Comment by komret** [comment]
4d2d8289e266fd072774a63803094c14916390ac introduces some changes originating from discussion with @hynek-jina:
- disabled button replaced with text (text has been changed so that it is applicable also when there is 0 total balance)
- button hidden whenever there are 0 non-private funds (previously only when total balance was 0)
- simplified the tooltip message on strategy page
Screenshot 2022-11-08 at 13 17 10
Screenshot 2022-11-08 at 13 17 30

**Review by matejkriz — APPROVED** [review]
👍 nice, I just updated the screenshots in description to reflect later changes

**Pull request merged**
