### PR TITLE
chore: Enable noImplicitReturns

### LINKED ISSUE #3630: Enable `noImplicitReturns` TypeScript option in Suite package
Stemmed from [this thread](https://github.com/trezor/trezor-suite/pull/3590#discussion_r612241102).

Enabling this option could help us catch some bugs and generaly make our code more deterministic.

In the Suite package `noImplicitReturns` is curently violated on some 65 places that would have to be altered.

Marking this as `Good first issue` as it shouhd be mostly mechanical code juggling.

cc @szymonlesisz @keraf

### PR DESCRIPTION
**Pull request by dahaca**
fix #3630

### CODE REVIEW

**Comment by Nodonisko** [comment]
@matejkriz Do we really like this? 

Sorry to say that @dahaca but I am not sure if this is even beneficial for us, I don't see any benefits in readability (which for me is maybe even worse since lot of "useless" return are added). I also don't see any benefits to code reliability or determinism since TS will know very well there what is return value and will check everything for you. I don't like idea of doing things like: `onClick: () => { something(); return; }` everywhere and I never had this enabled in any project and never had issue related to missing `returns`.

My opinion is not strong about that, and if majority of team like this then I have no problem with using this, but in my point of view these returns are really "useless".

**Comment by matejkriz** [comment]
No strong opinion on my side either. It's stemmed from this discussion: https://github.com/trezor/trezor-suite/pull/3590#discussion_r612241102

If a function has declared that it will return a value, then the compiler can ensure that it does with `noImplicitReturns: true`. So it's more strict and could prevent us from  introducing some unwanted logic flaws.

And it really doesn't mean, that you have to do things like `onClick: () => { something(); return; }` everywhere. Only if you have the return type defined or inferred:
```
 onClick: (): boolean | undefined => {
                if (Math.random() > 0.5) {
                    return true;
                }
            }
```          
so only if you return something...

**Comment by Nodonisko** [comment]
@matejkriz Thanks for explanation, I don't have too much experience with this. Although I still don't like it and I still thinks returns are mostly useless... I will leave decision to others.

BTW. I found only one discussion about that for language R, and they seems to do not need either https://community.rstudio.com/t/r-style-guide-explicit-return-or-not/40025/8 😅

**Comment by matejkriz** [comment]
I'm so sorry @dahaca that we didn't realize beforehand, but we agreed with the rest of the team that the potential benefit is too small compared to the headaches from changes of habits in this case. We could still do the strong typing for return type in some special cases but we don't want to turn it on globally.

**Comment by dahaca** [comment]
Sure, @matejkriz, probably should have asked everyone one more time before starting. I agree that it is not worth the ugliness added with useless returns. Although I had some small refactors too in that branch but it's ok.

**Pull request closed without merging**
