### PR TITLE
Add new TS3 CA pubkeys and update timestamp

### PR DESCRIPTION
**Pull request by tsusanka**
Add pubkeys for all known valid CA certificates at the moment and update config timestamp.

### CODE REVIEW

**Review by komret — APPROVED** [review]

**Comment by komret** [comment]
[Conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) are required, i.e. `chore(connect): add new TS3 CA pubkeys and update timestamp`.

**Comment by MiroslavProchazka** [comment]
We need to merge this until freeze (asap) as devices with those keys are probably on sale already.

**Comment by MiroslavProchazka** [comment]
@tsusanka There is a failing test due to the wrong formatting. Should I fix it, or the commit should come from you?

**Comment by tsusanka** [comment]
It doesn't have to, but I fixed it while I was at it. I also rebased on top of develop, there was a conflict due to https://github.com/trezor/trezor-suite/pull/11968.

I didn't bump the timestamp, because it was an older one than in #11968. Is that alright @komret?

**Comment by komret** [comment]
> I didn't bump the timestamp, because it was an older one than in #11968. Is that alright @komret?

Correct.

**Pull request merged**
