### PR TITLE
feat(connect-popup): use trezor icons with display off from suite-data

### PR DESCRIPTION
**Pull request by tomasklim**
## Description

- consulted with @Hermez-cz, if Ondra will not like my icon, he will change it in the future
- unify icons so that we have less work with Trezor Model R

## Screenshots:
Screenshot 2023-08-24 at 10 54 24

### CODE REVIEW

**Comment by tomasklim** [comment]
cc @Hannsek

**Comment by Hannsek** [comment]
So we would use TT images for all connected devices? 🤔
How it is done in Suite?

**Review by komret — APPROVED** [review]
No nitpicks this time :)

**Comment by tomasklim** [comment]
> So we would use TT images for all connected devices? 🤔 How it is done in Suite?

We use T1 for T1, TT for TT, TR for TR and TT without face for unknown device which should never occur, I guess

**Comment by Hannsek** [comment]
And is it correct that we would use the same icon (TT) for all devices in connect?

**Pull request merged**
