### PR TITLE
add language picker to settings

### PR DESCRIPTION
**Pull request by mroz22**

### CODE REVIEW

**Review by slowbackspace — CHANGES_REQUESTED** [review]
Screenshot 2019-12-30 at 09 59 51

Selected language isn't visible as it is white text on white bg.
Also It probably should be placed at the top, or at least above labelling?

**Comment by mroz22** [comment]
> Selected language isn't visible as it is white text on white bg.

It uses component from @trezor/componets, so either we need to change it there, or make abandon it and style own select. I would vote for the latter. Someone decide @ZdenekSL  ? 

> Also It probably should be placed at the top, or at least above labelling?

Design not provided, so I dont know. Probably yes.

**Comment by slowbackspace** [comment]
> > Selected language isn't visible as it is white text on white bg.
> 
> It uses component from @trezor/componets, so either we need to change it there, or make abandon it and style own select. I would vote for the latter. Someone decide @ZdenekSL ?
> 
imo there is a little reason to keep it in trezor/components now as it is just a regular select without heavy custom styling that was applied before. Also the header component where it was used was supposed to be shared in all apps so it made some sense for the language picker to be included in components.

**Comment by mroz22** [comment]
Yes, lets just use Select component. 

I have also played with types a little bit and can not decide if I should create custom utility types somewhere in `suite/types` for language stuff, such ass "LanguageCode" which would be union of language string literals etc, or just reconstruct the required type directly when needed from config which is the way I've chosen ultimately as I dont like very much cyclic imports in types declarations.

**Comment by mroz22** [comment]
And we probably want to have flags in Select, right?

**Comment by mroz22** [comment]
imho good enough, regarding other visuals (flags, etc...) I d wait for designs

image

**Review by slowbackspace — APPROVED** [review]

**Comment by slowbackspace** [comment]
spectacular

**Pull request merged**
