### PR TITLE
loading skeletons tests

### PR DESCRIPTION
**Pull request by mroz22**
@slowbackspace 
let's see if it works

### CODE REVIEW

**Review by keraf — APPROVED** [review]

**Comment by keraf** [comment]
Could you rebase this and update the commit message to follow the conventional commit syntax please. Also for next time, a clearer description would be appreciated, I couldn't really figure out what this change was about right away.

**Review by tomexx — APPROVED** [review]

**Comment by mroz22** [comment]
this just goes to @slowbackspace branch so I guess he will make the final clean up of commit messages before getting his branch ready for merging to develop

**Comment by mroz22** [comment]
Maybe I shoudn't have applied 'ready to review' label when it does not go to the develop branch

**Comment by slowbackspace** [comment]
@mroz22 yeah I was scared for a second why are we going to merge this 😁 
Thank you!

**Pull request merged**
