### PR TITLE
fix: @release-it/bumper dependency version

### PR DESCRIPTION
**Pull request by szymonlesisz**

### CODE REVIEW

**Comment by tsusanka** [comment]
I have intentionally remove `release-it`. Did I remove it incorrectly? Or are we putting it back?

**Comment by szymonlesisz** [comment]
looks like you didn't, it's still present in root `package.json` and used in `ci/release-it.yml` and `ci/releases.yml`
i just changed version number to valid one

**Review by tomexx — APPROVED** [review]
lgtm

**Comment by tsusanka** [comment]
> looks like you didn't, it's still present in root package.json and used in ci/release-it.yml and ci/releases.yml

Looks like I did it but I didn't file a PR :laughing:. https://github.com/trezor/trezor-suite/pull/3779 I suggest to close this in favor of that one.

**Pull request closed without merging**
