### PR TITLE
feat(suite-native): switch play haptics

### LINKED ISSUE #11594: Switch haptics
**Describe the bug**
Switch component doesn't play haptics feedback on change but according to https://developer.apple.com/design/human-interface-guidelines/playing-haptics it's recommended.

**How to reproduce**

1. Find any switch component

**Expected behavior**
Should play haptics feedback.

### PR DESCRIPTION
**Pull request by AdamSchinzel**
## Description

Switch component play light haptics feedback on change.

## Related Issue

Resolve #11594

### CODE REVIEW

**Comment by juriczech** [comment]
I guess it's fine, but was it discussed with anyone? I guess it should be added to all clickable elements?

**Comment by Nodonisko** [comment]
I don't think this is default behavior of switch on any platform, it should be discussed with Kuba or Katka if we want this behavior.

**Comment by vytick** [comment]
It is not default. Apple uses it for its apps though. Definitely better to check with product

**Comment by vytick** [comment]
cc @mnuky to check

**Pull request closed without merging**
