### PR TITLE
Fix/fiats

### PR DESCRIPTION
**Pull request by tomasklim**
## Description

- preventively fixed fiat rates conditions
- reverted fetching fiat rates only for recognised tokens
- reverted fetching of fiat rates when token definitions are fetched

## Related Issue

Resolve

### CODE REVIEW

**Review by AdamSchinzel — CHANGES_REQUESTED** [review]
I would also add the `&& !item.tokenAddress` to Invity sections just to be sure. Savings is just for BTC but:
- `useCoinmarketExchangeForm.ts`, `useCoinmarketSellForm.ts`, `ExchangeQuote.tsx`

can be for EVMs

**Review by AdamSchinzel — APPROVED** [review]
LGTM

**Review by martykan — APPROVED** [review]
I did some testing on it and it seems good

**Pull request closed without merging**
