### PR TITLE
fix: loader simpler design for better performance

### PR DESCRIPTION
**Pull request by tomexx**
fix: loader simpler design for better performance in Chrome + cleanup of available properties

### CODE REVIEW

**Comment by tomexx** [comment]
Not sure why the pipeline has failed - I've requested access to Gitlab pipelines but it won't be ready this week so I can't look into it.

**Comment by keraf** [comment]
Looks like some linting issues. You can run `yarn run lint` at the root of the project to lint all projects or `yarn workspace @trezor/suite-web run lint` if you want to run it in a single project (suite-web for example).

**Comment by slowbackspace** [comment]
I fixed the lint issue as I want this to merge this asap 😅

**Review by keraf — APPROVED** [review]

**Comment by keraf** [comment]
Tests are failing because of the 404 redirect issue which is unrelated to this change. I'll merge this.

**Pull request merged**
