### PR TITLE
fix(coinmarket): unify icon thickness and remove unused ones (#14135)

### LINKED ISSUE #14135: Coinmarket - Fix DCA icons thickness
## Issue

Before merging of https://github.com/trezor/trezor-suite/pull/13772 there were changes in other icons thickness so now they are of different weight.

## Now

Screenshot 2024-09-04 at 18 05 23

## Desired after

Screenshot 2024-09-04 at 18 05 59

### PR DESCRIPTION
**Pull request by salax**
## Description

Before merging of https://github.com/trezor/trezor-suite/pull/13772 there were changes in other icons thickness so now they are of different weight.

I also removed now unused icons added by me in mentioned PR.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/14135

## Before

Screenshot 2024-09-04 at 18 05 23

## After

Screenshot 2024-09-04 at 18 05 59

### CODE REVIEW

**Comment by seibei-iguchi** [comment]
Would it be possible to use the new icon set and not add icons to the deprecated set?

**Comment by salax** [comment]
> Would it be possible to use the new icon set and not add icons to the deprecated set?

@adamhavel I think it should be now using the new icons.
https://github.com/trezor/trezor-suite/blob/262354ffb9ca8ce76a361c04e7d6415c74feba51/packages/suite/src/views/wallet/coinmarket/DCA/index.tsx#L89

**Comment by seibei-iguchi** [comment]
> > Would it be possible to use the new icon set and not add icons to the deprecated set?
> 
> @adamhavel I think it should be now using the new icons.
> 
> https://github.com/trezor/trezor-suite/blob/262354ffb9ca8ce76a361c04e7d6415c74feba51/packages/suite/src/views/wallet/coinmarket/DCA/index.tsx#L89

I don't mean the Icon component but the new set of icons:) See https://satoshilabs.slack.com/archives/G019WLX2P7B/p1725459770638579 For example, arrowDownLight is deprecated

**Comment by salax** [comment]
@adamhavel I see 👍 I changed that icon and the other ones should be ok.

**Comment by seibei-iguchi** [comment]
> @adamhavel I see 👍 I changed that icon and the other ones should be ok.

Great! I'm not an approver but I approve:D

**Review by jvaclavik — APPROVED** [review]
Like this one!

**Review by seibei-iguchi — APPROVED** [review]

**Pull request merged**
