### PR TITLE
Fix account name in buy Info

### PR DESCRIPTION
**Pull request by vladimirvolek**
Part of https://github.com/trezor/trezor-suite/issues/2732

before:
image

after:
image

### CODE REVIEW

**Comment by mroz22** [comment]
You managed to get better exchange rate :tada: :1st_place_medal: :smile:

**Comment by vladimirvolek** [comment]
> You managed to get better exchange rate 🎉 🥇 😄

Here is the reason why.

image

**Comment by mroz22** [comment]
Weird thing is that `<AccountLabeling />` should do exactly what you are trying to achieve here. 
Still I am not questioning validity of this PR as the aformentioned component should show even more information (in some cases) and you may want it to happen here.

**Comment by mroz22** [comment]
I am ok with it. Just are you aware of and ok with that the AccountLabeling component may show even more information?
```
if (device && !accounts.find(a => a.deviceState === device.state)) {
        // account is not associated with selected device, add wallet label
        const accountDevice = accountUtils.findAccountDevice(accounts[0], props.devices);
        if (accountDevice) {
            return (
                <>
                    <WalletLabeling
                        device={accountDevice}
                        useDeviceLabel={!deviceUtils.isSelectedDevice(device, accountDevice)}
                    />{' '}
                    <TabularNums>{accountLabel}</TabularNums>
                </>
            );
        }
    }

```

**Pull request merged**
