### PR TITLE
chore: review missing/broken JSDoc annotations

### PR DESCRIPTION
**Pull request by darwin**
Found these while doing personal review of the code.

### CODE REVIEW

**Comment by tsusanka** [comment]
@mroz22 @szymonlesisz @keraf is there even any benefit of writing the JSDoc at all? I understand it in case the language is not typed but I personally hate comments that do not comment anything. They create an illusion of the code being commented with no added value. For example do you consider the comment here helpful?

```
 * @param {string} value
 * @param {boolean} passphraseOnDevice
 * @param {boolean} hasEmptyPassphraseWallet
**/
export const onPassphraseSubmit = (
    value: string,
    passphraseOnDevice: boolean,
    hasEmptyPassphraseWallet: boolean,
```

**Comment by szymonlesisz** [comment]
no strong preference here, at some point (at the beginning?) we thought that it would be nice to have auto-generated docs straight from the code, but it wasn't enforced rule so it's used in like maybe 10% of the code

**Comment by darwin** [comment]
Isn't there a tool to generate JSDoc from source code and typescript definitions if needed? To me this looks like a mechanical task for machines not for humans.

I've seen some js codebases which were using Google Closure (and no TypeScript) and there JSDoc annotations were needed for Google Closure Compiler ([mostly type info](https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler)).

**Comment by szymonlesisz** [comment]
regardless if its necessary or not i would like to merge it :)
@darwin could you pls fix the conflict in Router.tsx?

**Comment by darwin** [comment]
@szymonlesisz rebased.

**Comment by szymonlesisz** [comment]
thanks!

**Pull request merged**
