### PR TITLE
fix(suite): IO details in transaction details modal

### PR DESCRIPTION
**Pull request by seibei-iguchi**
### After
Screenshot 2024-12-04 at 9 52 19

### CODE REVIEW

**Review by jvaclavik — APPROVED** [review]
LGTM

**Review by tomasklim — APPROVED** [review]
Pearfect

**Comment by seibei-iguchi** [comment]
> Pearfect

Are you ok with amount being on the right side for non-utxo networks? Since the amounts are on the left side for token transfers. I could move them to the right side, too.

**Comment by bosomt** [comment]
**QA OK **

**24.12.1**
image

**develop**

image

**Info:**
 - Suite version: web 25.1.0 (e2860882d84f904cab9a204ec964d5725455fe89)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.7 regular (revision ef02c4de5d492a5c5d562984ec65a302d093dfd0)
 - Transport: BridgeTransport 2.0.33

**Pull request merged**
