### PR TITLE
chore(mobile): upgrade deps to RN 0.75

### PR DESCRIPTION
**Pull request by Nodonisko**
## Description

I will need ugpraded RN because of new CPU profiling tool in 0.75

## Related Issue

Resolve

### CODE REVIEW

**Comment by Nodonisko** [comment]
Chcked all mentioned packages by socket.dev and they seems fine 

@SocketSecurity ignore-all

**Comment by Nodonisko** [comment]
@SocketSecurity ignore-all

**Review by matejkriz — APPROVED** [review]
Except `Invalid hermes-engine.podspec file: undefined method visionos for #<Pod::Specification name="hermes-engine/Pre-built">.` error during `yarn run native:prebuild:clean` it works fine for me. I hope it's only local issue.

**Review by PeKne — APPROVED** [review]
Tested both for Android and iOS without an issue. I was not able to reproduce @matejkriz's error.

**Pull request merged**
