### PR TITLE
chore: update docs

### PR DESCRIPTION
**Pull request by mroz22**
Hello people, 
I would like to kick off the "big docs cleanup". 

Few tasks that come to my mind. feel free to add more: 
- [x] structure of docs. are we going to use `root/docs` folder for everything or `root/packages/*/docs` approach?
- [ ] READMEs deeply nested in `package/*/src` folders. we should eliminate these
- [ ] connect docs. it should be easy to find relevant info for 3rd party devs
- [ ] internal docs. it should be easy to find and mantain various 'internal' information such as how to run things, why are things done the way they are done and so on. 
- [ ] do something with https://docs.trezor.io/trezor-suite/. It is built from `/docs` folder but got outdated long time ago (is not even synced at the moment I think)

I would like to invite pretty much everybody but right from the start lets tag @matejkriz and @tomasklim  since we were discussing this topic. 

And also @sime since I would like to improve connect docs in this PR significantly.

### CODE REVIEW

**Comment by szymonlesisz** [comment]
missing description of connect api params/fields could be found directly in [protobuf definitions](https://github.com/trezor/trezor-firmware/blob/master/common/protob/messages-bitcoin.proto) 

maybe we should only point there to avoid duplication?

**Comment by sime** [comment]
> structure of docs. are we going to use root/docs folder for everything or root/packages/*/docs approach?

My gut feeling is beneath individual packages. Feels out of place in root/docs.

**Comment by komret** [comment]
> * [ ]  structure of docs. are we going to use `root/docs` folder for everything or `root/packages/*/docs` approach?

We discussed this with @matejkriz and it seems to me that moving documentation to `root/docs` is a better approach for the following reasons:

1) Only two packages currently have their own `docs` folder (_suite_ and _connect_), the majority of documentation already being in the _root/docs_.
2) Some info is relevant to more than one package, therefore keeping it in `root/docs` makes it easier to find rather than trying to guess what package it is in.
3) If wee need `root/docs`, as suggested in the previous point, we better keep all documentation in one place to avoid deciding where to look for the info.
4) `root/docs` is (or rather should be) more easily accessible and readable via https://docs.trezor.io/trezor-suite/.



> * [ ]  internal docs. it should be easy to find and mantain various 'internal' information such as how to run things, why are things done the way they are done and so on.

Each package has a README [which should be] briefly describing the package, including some basic instructions on how to use it in development, and eventually linking relevant documentation in `root/docs`.

What do you think?

I am going to update the READMEs and docs but I will certainly need help from more knowledgable developers. So please continue updating connect and other packages you know, @mroz22.

**Comment by mroz22** [comment]
Hey, so far I have only merged all docs I could find into `root/docs` honestly I dont care very much if it is `root/docs` or `packages/*/docs` just lets keep it one way. 
I would merge this PR and then we could do actual changes to docs after that. It will be easier to review.

**Comment by Nodonisko** [comment]
I like most of points but I don't agree with removing READMEs from packages.

README.md in package root makes perfect sense for things that are closely tied to that specific package like install instructions and some similar stuff. For example as we have in packages `suite-native` or `atoms` now. Placing stuff like this anywhere else that README.md would be confusing and unexpected for most of people because having README for package is very common thing in NPM universe.

Another argument for keeping READMEs for package is NPM itself because without it, it will show nothing on NPM pages https://www.npmjs.com/package/trezor-connect or on github when I want to send someone link to package on github, it will again show nothing without README. It actually really nice that I can someone send this kind of link https://github.com/trezor/trezor-suite/tree/develop/packages/connect-web

**Comment by vdovhanych** [comment]
Please take a note from this pr #5456 So the build on docs.trezor.io is happy

**Comment by mroz22** [comment]
> README.md in package root makes perfect sense

@Nodonisko I totaly agree. This is some misundestanding. `packages/*/README.md` is a must. The only thing I would like to remove from packages are these kind of readmes `packages/*/src/components/meow/HELLO.md`

**Comment by Nodonisko** [comment]
@mroz22 Oh sorry, then it totally makes sense to get rid of them.

**Review by vdovhanych — CHANGES_REQUESTED** [review]
we need to fix summary.md for docs build

**Review by vdovhanych — APPROVED** [review]
Looks good

**Pull request merged**
