### PR TITLE
fix(solana): Solana QA Fixes

### PR DESCRIPTION
**Pull request by memoriesadrift**
## Description
Addressing requested fixes. As for "Make PR Green", it should be working fine, re-run checks if necessary.

**Note:** Unit tests are failing, though only the following unit tests we haven't touched:
```
 Summary of all failing tests
        FAIL  src/api/firmware/__tests__/verifyAuthenticityProof.test.ts
         ● firmware/verifyAuthenticityProof › verify success (with prod keys)

           SubtleCrypto not supported
```
Please advise how we should go about fixing these.

### CODE REVIEW

**Comment by mroz22** [comment]
lets please start with 
```
 yarn dedupe
```

**Comment by mroz22** [comment]
this looks related to solana https://github.com/trezor/trezor-suite/actions/runs/6666432904/job/18217220130?pr=9773#step:19:370

**Comment by mroz22** [comment]
looks like that the last 2 commts have some conflict

**Comment by memoriesadrift** [comment]
Fixed merge conflicts

**Review by mroz22 — APPROVED** [review]
its green

**Pull request merged**
