### PR TITLE
feat(analytics): requests outlive the app session

### PR DESCRIPTION
**Pull request by tomasklim**
## Description

- few years ago, I was considering `Navigator.sendBeacon` for sending analytics data. However, the data were send using `POST` which is not possible in case of our analytics solution. 
- `keepalive` should do the same but also for other requests methods
- not available for Firefox

https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon (first note)
https://javascript.info/fetch-api#keepalive
https://caniuse.com/?search=keepalive

## Related Issue

https://github.com/trezor/trezor-suite/issues/3717#issuecomment-841168548
we do not have `session-end` anymore but let's add it

### CODE REVIEW

**Comment by matejkriz** [comment]
Looks promising, how to test it? Have you tried that in Electron? Do you have any links describing how it works in Electron apps?

**Comment by tomasklim** [comment]
Yes it works @matejkriz 
No keepalive web:
Screenshot 2023-06-13 at 11 35 35
No keepalive desktop:
last event
Screenshot 2023-06-13 at 11 33 37

Keep alive implemnted web:
Screenshot 2023-06-13 at 11 31 51
Keep alive implemented desktop: both develop and built app, works reliable
Screenshot 2023-06-13 at 11 31 10

I used simple express server and added 
```
        window.addEventListener('unload', () => {
            // @ts-expect-error
            this.report({ type: 'keepalive implemented electron' });
        });
``` 
to analytics

```
const express = require("express");
const app = express();
const port = 3000;

app.get("/", (req, res) => {
  console.log(req.query);
  res.send("Query params logged to the console.");
});

app.listen(port, () => {
  console.log(`Server running at http://localhost:${port}`);
});
```

**Comment by tomasklim** [comment]
tests fixed

**Review by matejkriz — APPROVED** [review]
nice testing approach with the simple server 👍

**Pull request merged**
