### PR TITLE
Feat: connect getAccountDescriptor method

### PR DESCRIPTION
**Pull request by szymonlesisz**
## Description

Adding new method for https://github.com/trezor/trezor-suite/issues/9658

TODO:
- [x] docs
- [x] e2e tests
- [x] popup view

Screenshot from 2023-10-24 13-18-55

### CODE REVIEW

**Comment by mroz22** [comment]
docs and popup view - we can live without them for now. No need to advertise this method for general audience now.

e2e test is nice to have, as long as it works and solves problem for https://github.com/trezor/trezor-suite/issues/9658 I happy to merge it as it is

**Comment by mroz22** [comment]
looks OK

hereby I nominate @marekrjpolak as a reviewer.

**Comment by marekrjpolak** [comment]
I proudly accept the nomination.

**Review by marekrjpolak — APPROVED** [review]
Looks good and works.

**Pull request merged**
