### PR TITLE
feat(connect): make transportReconnect implicitly true

### PR DESCRIPTION
**Pull request by martykan**
## Description

Make transportReconnect implicitly true, so 3rd parties can reconnect when bridge was not running.

Existing tests affected by this are modified to use `transportReconnect: false`

### CODE REVIEW

**Comment by mroz22** [comment]
woudln't it be easier to add 

`transportReconnect: true` default here? 
https://github.com/trezor/trezor-suite/blob/develop/packages/connect/src/data/connectSettings.ts#L31

**Comment by martykan** [comment]
Yeah, that's simpler, I changed it. I originally chose the approach of changing it in core, so it doesn't need updating on the 3rd party side, but that shouldn't be necessary anyway since iframe will parse them again and it wasn't previously defaulting to false.

**Comment by martykan** [comment]
I just need to figure out what to do about the tests. With transportReconnect this is called on dispose/cleanup:
https://github.com/trezor/trezor-suite/blob/a4e5832d3c9cfae9506bc58f4c5d931b538767c3/packages/connect/src/device/DeviceList.ts#L398
Which results in an unhandled promise rejection (since no one is listening at that point anymore) and Jest considers that a failure.

**Comment by martykan** [comment]
Ok I think it should be in good shape now, the dispose issue was solved by some changes in DeviceList

**Review by mroz22 — APPROVED** [review]
looks ok

**Pull request merged**
