### PR TITLE
fix(suite): type error

### PR DESCRIPTION
**Pull request by tomexx**

### CODE REVIEW

**Comment by tsusanka** [comment]
Could you please also explain to @pingpwned why this happened? I think he introduced it in https://github.com/trezor/trezor-suite/commit/511d265297fbd09771bd0222092b1f7cdf31f1aa .

**Comment by tsusanka** [comment]
Also I have realized the CI did not run on his PR because @pingpwned was working on his fork. @pingpwned I believe you should now have access to push to Suite directly, that way the CI will get triggered. And learning for us never merge without Gitlab running!

**Comment by tomexx** [comment]
My bad, I should have checked it better, sorry. However next time when @pingpwned opens a PR from Suite directly, we'll see type error in the CI. 

@pingpwned you can check type errors locally using `yarn run type-check`.

**Comment by tsusanka** [comment]
I meant why the "small" is correct and the variable is not. But maybe I am asking something obvious? :)

Anyway, it is no biggie, next time the CI will catch it.

**Comment by tsusanka** [comment]
The test passed now, so I am merging. Some e2e tests seem problematic but I do not think it is realted to this one.

**Pull request merged**
