### PR TITLE
fix(invity): Exchange - contents (decimals) of ReceiveCryptoInput and FiatInput clipped

### LINKED ISSUE #3155: Exchange - contents (decimals) of ReceiveCryptoInput and FiatInput clipped
**Describe the bug**
Contents (decimals) of ReceiveCryptoInput and FiatInput are clipped; prominent especially when selecting the fractions buttons.

**Info:**
 - Suite Version: app 20.12.1 be4e3a3, web beta b9113e2
 - Browser: Chromium 87.0.4280.66
 - OS: macOS Big Sur 11.0.1, Nixos 20.09
 - Firmware Version: model T 2.3.4 public

**Steps to reproduce:**
1. Run Suite in the default viewport,
2. Select an ETH or ETC account (~with 18 decimals allowed) and navigate to the Exchange tab,
3. Enter an amount in FiatInput field or select an arbitrary fraction button.

**Expected result:**
Decimals are either displayed all or hidden behind an ellipsis.

**Actual result:**
Decimals are clipped.

**Screenshots:**
image
image

### PR DESCRIPTION
**Pull request by LukasRada**
fixes #3155

### CODE REVIEW

**Review by keraf — APPROVED** [review]

**Comment by bosomt** [comment]
found one problem, ETH and ETC  has too many digits and last digits are clipped, @LukasRada 


image

image


**Info:**
 - Suite version: desktop 21.6.0 (9d8cea584b1f655f0964d80f863b02b1523e2cad)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.6.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model One 1.8.3 regular

**Comment by bosomt** [comment]
Looks like this PR is breaking input fields. When you decrease size of Suite window too much input will clear.
I was able to reproduce it with BTC and ETC so it's happening with all coins
See video in gif.
I was not able to reproduce it in Suite app, and I was not able to reproduce it in web version of production 21.5.1 version


**Info:**
 - Suite version: web 21.6.0 (5cf184412289711766c25ed43c3f6f8fce448968)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:88.0) Gecko/20100101 Firefox/88.0
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.3.4 regular


Peek 2021-05-18 10-20

**Comment by LukasRada** [comment]
@bosomt Already reported in #3721. The issue was there before this PR has been merged.

**Comment by sorooris** [comment]
**QA NOK**

Issue still persists and the linked issue (https://github.com/trezor/trezor-suite/issues/3155) is still open.
 
image

@tsusanka @alex-jerechinsky We need an executive decision about this pull request since it does not fix the linked issue.

**Comment by tsusanka** [comment]
Yes, let's postpone this to #3155. ACK for QA NOK. This is not a blocker for the release.

**Pull request merged**
