### PR TITLE
feat: Showing device status as animated text in device selector 

### PR DESCRIPTION
**Pull request by robertbrada**
fix part of https://github.com/trezor/trezor-suite/issues/2558

For now the animation appears when the user hovers over the device selector. 

**TODO:** show animation when device status changes (I will do that in another PR)

### CODE REVIEW

**Comment by slowbackspace** [comment]
It overlays long labels, which is probably expected but looks weird. Maybe adding a background under the text which will have the same whiteish color as component under and nice rounded borders will help?
image

**Review by slowbackspace — CHANGES_REQUESTED** [review]
see comment above

**Comment by robertbrada** [comment]
I fixed the issue using background gradient. See:

wallet-anim-1
wallet-anim-ě

**Review by slowbackspace — APPROVED** [review]
beautiful!

**Pull request merged**
