### PR TITLE
fix(connect): remove superfluous space from error message

### LINKED ISSUE #13560: UI glitch: connect: superfluous space
image

### PR DESCRIPTION
**Pull request by mroz22**
fix #13560 found while checking on #13555

Probably the most influential PR I ever made. 

image

### CODE REVIEW

**Review by martykan — APPROVED** [review]
I didn't test it, but it should probably work I think

**Comment by mroz22** [comment]
btw @Hannsek at the moment this is what prev 1.4.0 bl devices appear in suite after initial connection (in some cases). maybe they would deserve better handling. I will think about it a bit

**Comment by Hannsek** [comment]
The idea is that there should be something like this:

image


When clicking on the link, the transport would either automatically switch to the old Trezor Bridge or will take to the the debug settings.

**Comment by mroz22** [comment]
ok, please note it somewhere. at the moment, something like this is shown with the new bridge 

image

**Comment by Hannsek** [comment]
by `Trezor Bridge` we mean the old or new?

**Comment by mroz22** [comment]
:man-shrugging:

**Pull request merged**
