### PR TITLE
chore(message-system): msg config cleanup

### PR DESCRIPTION
**Pull request by MiroslavProchazka**
DO NOT MERGE YET

Cleanup of msg config from old messages that are no longer valid

### CODE REVIEW

**Review by komret — APPROVED** [review]

**Comment by komret** [comment]
> DO NOT MERGE YET

Ooops

**Comment by MiroslavProchazka** [comment]
I forget to change the sequence, so I will need to revert it :/ cc @komret

**Comment by komret** [comment]
We can add it in another commit.

**Comment by MiroslavProchazka** [comment]
In [here](https://github.com/trezor/trezor-suite/pull/13212)

**Comment by MiroslavProchazka** [comment]
Oh yeah, you are right, wait a minute

**Comment by MiroslavProchazka** [comment]
New PR here, please do not merge yet - https://github.com/trezor/trezor-suite/pull/13213

**Pull request merged**
