### PR TITLE
chore(connect): add Solana docs and tests

### PR DESCRIPTION
**Pull request by gabrielKerekes**
No production code changes, only Solana docs and tests are added here.

Corresponding [FW PR](https://github.com/trezor/trezor-firmware/pull/3318).

Previous Connect commit which adds actual Solana support - https://github.com/trezor/trezor-suite/commit/f620fad6b7d0ebea039eaf35fc9543d7b1135827. The commit message of that commit says that it adds "draft" support for Solana but I went through the code and haven't found any problems with it.

**I haven't been able to run the tests locally. I tried multiple times and I've wasted a lot of time on this. I've given up on running the tests so please run them and let me know if they can be run and if they pass.** 🙏

### CODE REVIEW

**Comment by mroz22** [comment]
regarding tests locally,

on mac-arm I am able to do
```
./docker/docker-connect-test.sh node -p methods -i solanaGetAddress
```
this requires running docker daemon on your system.

**Comment by mroz22** [comment]
I am happy to merge this ASAP, just please check on type-check issues https://github.com/trezor/trezor-suite/actions/runs/6531626078/job/17734254399?pr=9655#step:15:423

**Comment by gabrielKerekes** [comment]
> ./docker/docker-connect-test.sh node -p methods -i solanaGetAddress

This actually doesn't find any tests on my machine, no idea why. Also if it did find some tests they would probably fail because of wrong emulator version in the docker image?

> just please check on type-check issues

I think the issues stem from the base branch and were not introduced in this PR? If you confirm that's case I would not resolve them here.

**Comment by mroz22** [comment]
> I think the issues stem from the base branch and were not introduced in this PR? If you confirm that's case I would not resolve them here.

Could be, in that case, it means that either feat/solana is broken, or feat/solana is rebased on broken develop. It doesn't really matter here. 

As for tests, you are right, you can't use default firmware emulators, you need to do something like this for tests to pass (until your firmware branch is merged)
https://github.com/trezor/trezor-suite/blob/230236a3e152d2953d4ec8a1fd9a64a68357c3e7/ci/test.yml#L342

it should be possible to pass url also as command line arg
```
./docker/docker-connect-test.sh node -p methods -i solanaGetAddress -u <url to artifact in gitlab CI>
```

> This actually doesn't find any tests on my machine, no idea why. 

oh, thats gonna be __fixutres__/index missing re-export

**Comment by gabrielKerekes** [comment]
> oh, thats gonna be fixutres/index missing re-export

I force pushed an update with the re-exports.

Now the tests actually run thank you. The FW branch has not yet been built by the CI so I can't run them properly - we'll be creating a new branch on FW soon so hopefully we'll be able to run CI there.

**Review by mroz22 — APPROVED** [review]

**Pull request merged**
