### PR TITLE
feat(tests): logging of test details into tenv log

### PR DESCRIPTION
**Pull request by grdddj**
Including logs of all test cases' details into `trezor-user-env`'s `debugging.log`, so we can more easily troubleshoot specific failing tests.

Notes:
- created new specific Cypress task `logNewTestCase`, same as `logTestDetails`, just includes a prefix string (I was not able to call `logTestDetails` from `logNewTestCase`)
  - `logTestDetails` is therefore still not being used, we can send details from the middle of the tests (same info as in `cy.log`)
- my editor (VS Code) is complaining about the `const description = ...` line in all test modules that it `Cannot redeclare block-scoped variable 'description' ` - which is strange, looks as it sees all the files combined (which is maybe happening on the background, but there seems to be no error when running the tests)
- apart from the logging, some small updates to the testing code were made, where it looked appropriate (maybe it deserves its own commit)

### CODE REVIEW

**Comment by tsusanka** [comment]
Can't we really do this somehow automatically? Using the [beforeEach](https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests#Support-file) function and fetching the test name that's inside `describe()` somehow. It is probably a little bit hacky but this [issue](https://github.com/cypress-io/cypress/issues/2972#issuecomment-563335849) describes some ideas.

**Comment by tsusanka** [comment]
Well maybe it is done differently in JS :thinking:. Let's wait what @mroz22 or @tomasklim thinks.

**Comment by grdddj** [comment]
> Can't we really do this somehow automatically? Using the [beforeEach](https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests#Support-file) function and fetching the test name that's inside `describe()` somehow. It is probably a little bit hacky but this [issue](https://github.com/cypress-io/cypress/issues/2972#issuecomment-563335849) describes some ideas.

Thanks a lot for the linked issue! It seems to work fine and theoretically we can **replace this whole commit with just three lines** - at the beginning of the main `beforeEach` function:

https://github.com/trezor/trezor-suite/blob/263691557817774ca6c95907579b7c24ad5821d3/packages/integration-tests/projects/suite-web/support/commands.ts#L33-L40

```js
const suiteName = (Cypress as any).mocha.getRunner().suite.ctx.currentTest.parent.title;
const testName = (Cypress as any).mocha.getRunner().suite.ctx.currentTest.title;
cy.task('logTestDetails', `New test case: ${suiteName} - ${testName}`);
```

(as it is now really only at one place, we also do not need the `logNewTestCase` at all)

I am almost ashamed that I did not Google more to find this, it would save a lot of manual copy-pasting (if we decide to use this, there can be some hidden disadvantages).

**Comment by tsusanka** [comment]
> I am almost ashamed that I did not Google more to find this, it would save a lot of manual copy-pasting (if we decide to use this, there can be some hidden disadvantages).

But do not forget about all the lessons learned! :). Let's wait what the others think, I hope it is not _too_ hacky.

**Comment by mroz22** [comment]
I like this global solution. It could be even made conditional under some env variable which might be set in gitlab.yml. something like 

```
beforeEach(() => {
    if (process.env.CYPRESS_LOG_TEST_NAMES) {
        const suiteName = (Cypress as any).mocha.getRunner().suite.ctx.currentTest.parent.title;
        const testName = (Cypress as any).mocha.getRunner().suite.ctx.currentTest.title;
        cy.task('logTestDetails', `New test case: ${suiteName} - ${testName}`);
    }

    cy.intercept('POST', 'http://127.0.0.1:21325/', req => {
        req.url = req.url.replace('21325', '21326');
    });
    cy.log('stop and start bridge before every test to make sure that there is no pending session');
    cy.task('stopBridge');
    cy.task('stopEmu');
});

```

But also if there is some test file that seems to be flaky and contains multiple tests, I think that we can always break it into multiple test files so that each contains only one test. I believe that it would be even easier to spot problematic test this way.

**Review by mroz22 — CHANGES_REQUESTED** [review]
Lets use this global solution pleaaseeee.

**Comment by tsusanka** [comment]
Thx! I would not worry about the env variable, I think we can enable it by default.. I agree splitting it up into multiple files would be awesome. But we can do that in subsequent PRs @grdddj if you prefer to finish this first.

**Comment by grdddj** [comment]
Good, thanks for confirmation, I will force-push the "three-line" global solution - without the env variable so far. (And saving that big commit locally, just in case)

Regarding the splitting of each test into individual file, what would be the real benefit? If more tests are in the same file, they are influencing each other? It seems that we would have a lot of code duplication this way (all the specific `beforeEach` would need to be in every file etc.). If it would bring some consistency advantages, then surely, I am in (in a different PR :)).

**Comment by tsusanka** [comment]
> Regarding the splitting of each test into individual file, what would be the real benefit? If more tests are in the same file, they are influencing each other?

The main advantage is imho tidiness. You would not have to search through the files to locate a failing test, rather open the specific file right away.

> It seems that we would have a lot of code duplication this way (all the specific beforeEach would need to be in every file etc.). If it would bring some consistency advantages, then surely, I am in (in a different PR :)).

Not sure I understand this. Where is the duplication? Not much would change here, we would just create a new file in tenv when `logTestDetails` is called.

**Review by tsusanka — APPROVED** [review]

**Comment by tsusanka** [comment]
The code LGTM. @mroz22 do you want to re-review?

----

Btw I investigated the log which is part of the artifacts and what I see is:
```
2021-08-10 08:03:22,822 INFO CONTROLLER: Request: {'id': 0, 'type': 'log', 'text': 'New test case: Backup - Backup failed - device disconnected during action'}
2021-08-10 08:03:22,822 INFO CONTROLLER: New test case: Backup - Backup failed - device disconnected during action
2021-08-10 08:03:22,823 INFO CONTROLLER: Response: {'response': 'Text logged', 'id': 0, 'success': True}
2021-08-10 08:03:22,825 INFO CONTROLLER: Client exiting with a failure. Goodbye
2021-08-10 08:03:22,840 INFO CONTROLLER: Welcome: {'type': 'client', 'id': 'TODO', 'firmwares': {'T1': ['1-master', '1.10.2', '1.10.1', '1.10.0', '1.9.4', '1.9.3', '1.9.2', '1.9.1', '1.9.0', '1.8.3', '1.8.2', '1.8.1', '1.8.0', '1.7.3', '1.7.2', '1.7.1', '1.7.0', '1.6.3', '1.6.2'], 'TT': ['2-master', '2.4.1', '2.4.0', '2.3.6', '2.3.5', '2.3.4', '2.3.3', '2.3.2', '2.3.1', '2.3.0', '2.2.0', '2.1.8', '2.1.7', '2.1.6', '2.1.5', '2.1.4', '2.1.3', '2.1.2', '2.1.1', '2.1.0', '2.0.10', '2.0.9', '2.0.8']}, 'bridges': ['2.0.31', '2.0.27', '2.0.26', '2.0.19']}
```

so the text is indeed correctly logged. However, the connection is then exited and restarted again (I guess). That's weird isn't it? Or is it expected?

**Comment by grdddj** [comment]
> > Regarding the splitting of each test into individual file, what would be the real benefit? If more tests are in the same file, they are influencing each other?
> 
> The main advantage is imho tidiness. You would not have to search through the files to locate a failing test, rather open the specific file right away.
> 
> > It seems that we would have a lot of code duplication this way (all the specific beforeEach would need to be in every file etc.). If it would bring some consistency advantages, then surely, I am in (in a different PR :)).
> 
> Not sure I understand this. Where is the duplication? Not much would change here, we would just create a new file in tenv when `logTestDetails` is called.

I am not sure, but seems we are discussing two possible splittings :) One in `Suite` (so that each e2e test file contains only one test) and one in `tenv` (one log file for each test).

Before your comment, I was only considering the first one. By the duplication I meant that currently when one test file in `Suite` contains multiple test cases, they share the file-header, description and `beforeEach` block. When each test case would be single file, these things would be duplicated.

The `tenv` splitting (having one log file for one test scenario) can be done, but could be quite tricky to implement (as currently we log everything into one file without any logic). Not sure if one file containing all tests is not better anyway, as simple ctrl+f search of the test case is enough to locate it - instead of handling and downloading many individual files from artifacts (and yeah, all those files would need to be artifacted somehow). @tsusanka not sure if you meant it this way :)

**Comment by grdddj** [comment]
> so the text is indeed correctly logged. However, the connection is then exited and restarted again (I guess). That's weird isn't it? Or is it expected?

It is expected because it is defined like this in Suite tests - in the way we define Cypress tasks. Example definition below, when performing any command, we are connecting to the controller, triggering the command and immediately disconnecting.

https://github.com/trezor/trezor-suite/blob/dd23ecc920f7bf6fab3e63e7e30bdced32989cdd/packages/integration-tests/projects/suite-web/plugins/index.js#L89-L94

As you are pointing out, it has the disadvantage that it makes the `tenv` logs quite messy and maybe confusing (as each connection logs a welcome message and also the disconnect is logged). Theoretically we could **connect to controller just once before every test case** and then reuse the connection and disconnect only at the end. (there could be some rationale behind this connect-disconnect, maybe @mroz22  will know)

**Comment by tsusanka** [comment]
> The tenv splitting (having one log file for one test scenario) can be done, but could be quite tricky to implement (as currently we log everything into one file without any logic). Not sure if one file containing all tests is not better anyway, as simple ctrl+f search of the test case is enough to locate it - instead of handling and downloading many individual files from artifacts (and yeah, all those files would need to be artifacted somehow). @tsusanka not sure if you meant it this way :)

Oh yeah, that was a misunderstanding, I was indeed talking about `tenv` only. As this needs some more work, let's not worry about it for now and we'll tackle it later in case we conclude it as necessary.

**Comment by tsusanka** [comment]
> It is expected because it is defined like this in Suite tests - in the way we define Cypress tasks. Example definition below, when performing any command, we are connecting to the controller, triggering the command and immediately disconnecting.

I am really curious about this, but that is indeed a question for @mroz22 and I do not want to stall this PR because of that, I'll create an issue.

**Comment by tsusanka** [comment]
So I believe everything is resolved. Merging!

**Pull request merged**
