### PR TITLE
Separate Suite Desktop user data folder by environment

### PR DESCRIPTION
**Pull request by matejkriz**
## Description

We already have separated data per environment on web (storage per domain). The goal is to separate all the user data dir for Suite Desktop too (not only IndexedDB storage, but also electron store, caches, logs). 

It is useful just internally for testing - data from production app are not mixed with data from local/dev builds. It also prevents the loss of production IndexedDB data (remembered wallets, backend settings, coin settings, send form drafts...) during downgrade of the storage from newer testing version.

I did that on two places:
- changing the name property on build (original `@trezor/suite-desktop` for codesing builds and `@trezor/suite-desktop-dev` for other builds)
- changing the user data folder programatically on local dev build (`trezor/suite-desktop-local`)
Because I found no reasonable way how to inject name property to local build (it takes it from the package.json "name")

Together with that I moved electron-builder config out of the package.json to javascript file so it's easier to maintain.

And also changing the appId from `io.trezor.TrezorSuite` (codesign) to `io.trezor.TrezorSuite.dev`(other builds) – that should help us to get all builds signed (dev build with non-production keys) and make autoupdate testing possible on any build. 

App name shown in the title bar also reflects the environment (Trezor Suite/ Trezor Suite Dev / Trezor Suite Local) see the screenshots.
The only downside I see is that we can no longer detect that other instance of Suite is running if it uses different appId. So we are able to start Local version even if there is production already running but we get the error during modules loading (see the screenshot).

## Screenshots:
image
image

image

### CODE REVIEW

**Comment by matejkriz** [comment]
Sentry is still writing to the original directory, don't know why. 
image

**Review by komret — CHANGES_REQUESTED** [review]
Good job!
The error message about another instance running displays correctly when I run production app and then start local build, but when I do it vice versa, the production app shows this:
Screenshot 2023-03-21 at 18 34 25
A then when I refresh:
Screenshot 2023-03-21 at 18 29 38

(Screen captures were not taken together, hence the theme difference)

**Comment by matejkriz** [comment]
> Good job! The error message about another instance running displays correctly when I run production app and then start local build, but when I do it vice versa, the production app shows this:
>  ...


Yes, because I add the propagation of the error [here](https://github.com/trezor/trezor-suite/pull/7297/files#diff-7b842ecc1f207e1622923c454bc11f6dc656acc1d15b090f417eda426b1d00b3R134)  and extend handling of the error [here](https://github.com/trezor/trezor-suite/pull/7297/files#diff-dc5e5cd8bb2f8a20a8c3afea7f759addab9edefa51d086560ba6f442ce3c0540R103)

**Review by komret — APPROVED** [review]
I see, it's expected with the current prod version 🤦

**Comment by bosomt** [comment]
**QA OK**

dev and prod environments have separate directories and settings

**Info:**
 - Suite version: desktop 23.4.1 (cff9e3ab255d4a7feebe7fb81ff3170146ee3537)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.4.1 Chrome/110.0.5481.208 Electron/23.2.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: BridgeTransport 2.0.27

**Pull request merged**
