### PR TITLE
Stable: Solana token list

### PR DESCRIPTION
**Pull request by tomasklim**
## Description

Fixing usage of `develop` and `stable` token list for Solana

### CODE REVIEW

**Review by vdovhanych — COMMENTED** [review]
you also need to add it for gitlab build of desktop apps, both normal and nix shell one. This won't solve production for now. Also i would use IS_CODESIGN for the configuration of the url on prod. 

But i don't care that much so this is also fine, but please add it everywhere where it needs to be used.

**Review by vdovhanych — APPROVED** [review]

**Review by marekrjpolak — APPROVED** [review]
LGTM

**Comment by STew790** [comment]
**QA OK**
image

**Info:**
 - Suite version: desktop 24.5.2 (1ca8b8063fd7028d1fe242db41caa31c0a1f7d5a)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.5.2 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.5.2 (1ca8b8063fd7028d1fe242db41caa31c0a1f7d5a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.5.2 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33

**Pull request merged**
