### PR TITLE
chore: add prebuild as root script

### PR DESCRIPTION
**Pull request by juriczech**
## Related Issue

Resolve

### CODE REVIEW

**Review by matejkriz — APPROVED** [review]

**Comment by juriczech** [comment]
@SocketIgnore npm/resolve-from@5.0.0 npm/ms@2.1.2 npm/get-package-type@0.1.0

**Comment by juriczech** [comment]
@SocketIgnore resolve-from@5.0.0 ms@2.1.2 get-package-type@0.1.0

**Comment by juriczech** [comment]
@SocketIgnore loose-envify@1.4.0

**Comment by juriczech** [comment]
@SocketIgnore resolve-from@5.0.0 ms@2.1.2 get-package-type@0.1.0 loose-envify@1.4.0

**Comment by juriczech** [comment]
@SocketSecurity ignore npm/loose-envify@1.4.0

**Pull request merged**
