### PR TITLE
fix(landing-page): use absolute path to make it work on both /index and /start pages

### LINKED ISSUE #3968: Landing page for new devices
Let's create a new landing page for new devices: **suite.trezor.io/start** (also redirected from trezor.io/start).

The design will be identical to: **suite.trezor.io** however the copy will be changed (via Crowdin).

### PR DESCRIPTION
**Pull request by matejkriz**
fix https://github.com/trezor/trezor-suite/issues/3968

### CODE REVIEW

**Review by tsusanka — APPROVED** [review]
That's almost comically simple :). Let's wait for CI, test when deployed and merge then.

**Review by tsusanka — CHANGES_REQUESTED** [review]
Discuss with @matejkriz that this will not work on our testing slcorp servers. He'll fix it tomorrow.

**Review by tsusanka — APPROVED** [review]

**Review by tsusanka — APPROVED** [review]
I have verified the links seem correct now on `https://suite.corp.sldev.cz/suite-web/fix/3969-landig-page-redirection`. The code should be reviewed by someone from the team though.

**Review by tomasklim — APPROVED** [review]
LGTM

**Comment by tsusanka** [comment]
@matejkriz please squash and force-push and let's merge.

**Pull request merged**
