### PR TITLE
chore(docs): remove deleted file reference from summary

### PR DESCRIPTION
**Pull request by vdovhanych**
Fixes mdbook build on docs.trezor.io. Build tool uses summary for index and it was failing on this file as its not in the repo anymore.

### CODE REVIEW

**Comment by vdovhanych** [comment]
Wait please, there is more that's broken. Will fix it all here.

**Comment by mroz22** [comment]
btw. do we have some way how to detect broken build from pipeline? :thinking:

**Comment by vdovhanych** [comment]
Ok, so the mdbook build now is correct. When updating docs files and folders, it's also important to edit the `SUMMARY.md` file. @mroz22 We cant check the build on the server as per see, but I can add an action that would try to build the docs but not publish it anywhere, and if that fails, the build on the server would also fail.

**Comment by mroz22** [comment]
> I can add an action that would try to build the docs but not publish it anywhere, and if that fails, the build on the server would also fail.

Sounds useful to me! Otherwise we will see broken builds quite often.

**Review by komret — CHANGES_REQUESTED** [review]
Could you please also update _index.md_ with info on how the docs are deployed and a disclaimer that SUMMARY.md must be kept up to date? Also mention the new the action if you can add it.

**Comment by vdovhanych** [comment]
I would maybe close this in favor of https://github.com/trezor/trezor-suite/pull/5439 and fixed it there. Will add the action to that PR and also update how to docs there.

**Review by komret — APPROVED** [review]

**Comment by mroz22** [comment]
cherry-picked this into https://github.com/trezor/trezor-suite/pull/5439

**Pull request closed without merging**
