### PR TITLE
refactor(request-manager): simplification of RequestPool

### PR DESCRIPTION
**Pull request by szymonlesisz**
## Description
Prerequisite for [tor circuits timeouts](https://github.com/trezor/trezor-suite/pull/8661) 
Cherry picked to standalone PR to avoid complex changes in main PR.

1. `RequestPool` unnecessarily stores the data (RequestData) of the request in `requestPool` array. All could be done in the scope of one function.
2.  `RequestPool` doesn't have to be class (see discussion below)
3. removed unused 'ERROR_PROXY_TIMEOUT' and 'ERROR_PROXY_REJECTED' - will be done/handled differently in the main PR
4. fixed `interceptNetSocketConnect` and `interceptNetConnect` details. Occasionally it logs:
```
DEBUG(request-interceptor): net.Socket.connect - undefined
```

 because of forcetyping and ts-ignore

### CODE REVIEW

**Comment by szymonlesisz** [comment]
i was even thinking to change it from class to function like:

```
createHttpPool = () => {
    return (request: http.ClientRequest) => {
        // logic....
        request.on('response', ...);
        request.on('error', ...);
        return request;
    }
}
```
and use it in request-interceptor like:
```
const requestPool = createHttpPool();


https.request = (...args) => {
    if (overload) {
            return requestPool(originalHttpsGet(...overload));
    }
}
```

whats your opinion @karliatto ?

pls checkout fixup below

**Comment by karliatto** [comment]
> i was even thinking to change it from class to function like:
> 
> ```
> createHttpPool = () => {
>     return (request: http.ClientRequest) => {
>         // logic....
>         request.on('response', ...);
>         request.on('error', ...);
>         return request;
>     }
> }
> ```
> 
> and use it in request-interceptor like:
> 
> ```
> const requestPool = createHttpPool();
> 
> 
> https.request = (...args) => {
>     if (overload) {
>             return requestPool(originalHttpsGet(...overload));
>     }
> }
> ```
> 
> whats your opinion @karliatto ?
> 
> pls checkout fixup below

Since you are removing `requestPool` yes it makes sense to simplify with a function since there is not any benefit in having it as a class.

I am just wondering what happens when there is not response, I assume it will timeout and you will get the error. If I remember well you added a custom timeout to the requests from coinjoin, right? So it means that you know how much time you the request will take to timeout. Right?

**Comment by szymonlesisz** [comment]
> I am just wondering what happens when there is not response, I assume it will timeout and you will get the error. 

there is no difference between current (class) implementation and this refactoring when it comes to request event handling except for that the `RequestData` are not stored anywhere

**Review by karliatto — APPROVED** [review]
Nice simplification!

**Pull request merged**
