### PR TITLE
ci(github): build webextension in staging when releasing for proper testing

### PR DESCRIPTION
**Pull request by karliatto**
Build webextension in staging when releasing for proper testing.

### CODE REVIEW

**Review by vdovhanych — COMMENTED** [review]
why do we need artifacts for the prod builds?

**Comment by karliatto** [comment]
> why do we need artifacts for the prod builds?

When building staging QA should be testing webextension with the staging connect src in order to be as close to production as possible.

**Comment by vdovhanych** [comment]
> > why do we need artifacts for the prod builds?
> 
> When building staging QA should be testing webextension with the staging connect src in order to be as close to production as possible.

Yes i understand but this only builds the webextension for artifacts and uploads it there but is not deployed anywhere else

**Comment by karliatto** [comment]
> > > why do we need artifacts for the prod builds?
> > 
> > 
> > When building staging QA should be testing webextension with the staging connect src in order to be as close to production as possible.
> 
> Yes i understand but this only builds the webextension for artifacts and uploads it there but is not deployed anywhere else

Right, it is upload to GitHub so QA can download and test locally.

**Review by vdovhanych — APPROVED** [review]
Ok np then, lets merge.

**Pull request merged**
