### PR TITLE
connect - new stellar messages

### PR DESCRIPTION
**Pull request by mroz22**
there are some new Stellar messages implemented in firware. Do we want to reflect this on connect layer somehow? 
(only 3rd commit is relevant to this PR)
cc @overcat

### CODE REVIEW

**Comment by overcat** [comment]
I can submit a PR in the near future to add support for new operation in connect.

**Comment by mroz22** [comment]
ok, cool. 👍 looking forward to it. you may cherry-pick [3503d4c](https://github.com/trezor/trezor-suite/pull/11184/commits/3503d4c5718e85ec6e313393eb433fa563eaefa3) commit. 
[3b313ef](https://github.com/trezor/trezor-suite/pull/11184/commits/3b313efbcc5b39713a51aa9aeb1d9a854520b286) will already be in develop

**Comment by overcat** [comment]
Hi @mroz22, I encountered a problem while running the test. I would like to ask, if [the log](https://github.com/overcat/trezor-suite/actions/runs/7916070954/job/21609380878#step:7:732) prompts the following information, does it mean that we are using [an outdated firmware](https://github.com/trezor/trezor-firmware/commit/57063dbb408bcd3075c96b44d48bcaeafad36efa) where `StellarClaimClaimableBalancesOp` has not been added yet?
```
test-run-1              |   console.log
test-run-1              |     Device connected:  {
test-run-1              |       major_version: 2,
test-run-1              |       minor_version: 6,
test-run-1              |       patch_version: 3,
test-run-1              |       internal_model: 'T2T1',
test-run-1              |       revision: '57063dbb408bcd3075c96b44d48bcaeafad36efa'
test-run-1              |     }
```

**Comment by mroz22** [comment]
I guess so. Not sure how  you run emulator but I suggest this https://github.com/trezor/trezor-user-env it should already have firmware from master branch. Don't forget to pull lastest image

**Comment by overcat** [comment]
> I guess so. Not sure how you run emulator but I suggest this https://github.com/trezor/trezor-user-env it should already have firmware from master branch. Don't forget to pull lastest image

I am using GitHub Actions from the develop branch. I noticed that the latest test log in the develop branch also displays the above-mentioned logs. Does this mean that we did not use the firmware built from the latest code from the master branch for testing? Is this expected behavior?

See https://github.com/trezor/trezor-suite/actions/runs/7921216376/job/21626184531#step:7:725

**UPDATE:** I can use the latest firmware by removing 2-latest.

**Comment by mroz22** [comment]
yes, you should use something like 2-main I think. ok good, closing this PR in favour of #11210 which is basically the same but with different branch name as I can see now 😬 😄

**Pull request closed without merging**
