### PR TITLE
feat(suite): add link to data analytics docs

### LINKED ISSUE #5129: Link our data analytics document directly from Suite
In https://github.com/trezor/trezor-suite/pull/4516 we have improved our data docs. We would like to link [this page](https://github.com/trezor/trezor-suite/blob/develop/docs/analytics/index.md) from this screen directly:

image

I would simpy change the sentence "Read more in [Terms & Conditions](https://data.trezor.io/legal/wallet-terms.pdf)" to "Read more in our [technical documentation](https://github.com/trezor/trezor-suite/blob/develop/docs/analytics/index.md) and [Terms & Conditions](https://data.trezor.io/legal/wallet-terms.pdf)" or similar.

@b-irving could you come up with the sentence please? Or is my suggestion good enough?

### PR DESCRIPTION
**Pull request by komret**
Add a link to technical documentation on data analytics to the onboarding screen.

Screenshot 2022-05-09 at 14 56 27

### CODE REVIEW

**Review by mroz22 — APPROVED** [review]

**Review by matejkriz — CHANGES_REQUESTED** [review]
We need to think about the static link to github file. Please do not merge now.

**Comment by komret** [comment]
I rebased from develop to change the relative URLs to absolute. The link to analytics docs now leads to docs.trezor.io.

**Review by matejkriz — APPROVED** [review]
closes #5129

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: desktop 22.6.0 (d72ff4c5b9f3cbe2ccb4be47170f88c08e9271d1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.6.0 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.11.1 regular (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: bridge 2.0.31

**Pull request merged**
