### PR TITLE
chore(suite-data): update tor binaries to 0.4.7.13

### PR DESCRIPTION
**Pull request by prusnak**
- this PR also updates the script to include also linux-arm64 binaries
- let's make sure this is merged ASAP so we have the latest and greatest Tor release for CJ testing

### CODE REVIEW

**Comment by karliatto** [comment]
@tomasklim Could you help me running the `packages/suite-data/files/bin/tor/update.sh` script to see it produces the same binaries as the ones in this PR? It requires to be run in a MacOS because of lipo that unpacks universal mac binary into arm64 and x64 binaries.

**Comment by tomasklim** [comment]
> packages/suite-data/files/bin/tor/update.sh

no changes in git

```
~/SatoshiLabs/trezor-suite $ ./packages/suite-data/files/bin/tor/update.sh
Downloading extension CRX files for:
- Mac
- Windows
- Linux x64
- Linux arm64

Unpacking extensions

Expecting Tor release 0.4.7.13-0

Checking hashes of downloaded binaries
sed: 1: "tmp/SHA512SUMS": undefined label 'mp/SHA512SUMS'
```

**Comment by prusnak** [comment]
Hm, it seems the sed expression does not work with sed shipped with macOS. Will push the fix soon.

**Comment by prusnak** [comment]
I just pushed 75de06d0ebe65aac9ec98cbe0aaa70f59e28ca95 which makes sed calls valid on macOS version of sed.

**Review by tomasklim — APPROVED** [review]

**Review by karliatto — APPROVED** [review]
I tested the with linux-x64 and Tor works as expected.

@trezor/qa Could you please test Tor regression in all the platforms?

**Comment by bosomt** [comment]
@karliatto tested on macARM, Linux and Windows.
See https://www.notion.so/satoshilabs/tor-binaries-update-to-0-4-7-13-025ddd0734f84abc9df2e3222b2f93ad?pvs=4
Approving

**Pull request merged**
