### PR TITLE
Raspberry Pi (Linux ARM64) support

### PR DESCRIPTION
**Pull request by prusnak**
My take at Raspberry Pi (Linux ARM64) support - closes https://github.com/trezor/trezor-suite/pull/2960

We are still missing:

- [ ] Tor binary for linux-arm64
- [x] testing on the real hardware

### CODE REVIEW

**Comment by keraf** [comment]
FYI, I have a Pi 4 on my desk with Raspberry Pi OS. Feel free to take it (I'm not using at the moment).

**Comment by prusnak** [comment]
> FYI, I have a Pi 4 on my desk with Raspberry Pi OS.

Thanks, I have my own Pi 4 at home, so I'll test with that. I just didn't get time to do it properly. :-)

In another word, the one in the office is still available.

**Comment by prusnak** [comment]
Good news! I just tested this on a Raspberry Pi 4 and the Suite Desktop works flawlessly! (modulo Tor)

I just had to download and install the udev rules - the provided deb worked easily via `sudo dpkg -i trezor-udev*.deb`

I stumbled upon one small unrelated issue reported as https://github.com/trezor/trezor-suite/issues/2968

**Comment by prusnak** [comment]
Superseded by https://github.com/trezor/trezor-suite/pull/2969

**Pull request closed without merging**
