### PR TITLE
Add vector CoinLogo's

### LINKED ISSUE #301: Add vector CoinLogo's
TinyGrab Screen Shot 23-07-2019, 17 22 02

### PR DESCRIPTION
**Pull request by keip**
closes #301
BREAKING CHANGE: props `width`/`height` replaced with `size`

### CODE REVIEW

**Comment by vladimirvolek** [comment]
Please add this braking change to CHANGELOG.md

**Comment by vladimirvolek** [comment]
Coin icons are not the same size.

before
image


after
image

**Comment by vladimirvolek** [comment]
Tests are failing https://gitlab.corp.sldev.cz/trezor/trezor-suite/-/jobs/48394

**Comment by vladimirvolek** [comment]
Height and width param is still in storybook.

image

**Comment by keip** [comment]
> Coin icons are not the same size.
> 
> before
> image
> 
> after
> image

I see the old logos in your screenshot "after".
You need to build the lib first: yarn workspace @trezor/components build:lib
I changed the size of the logos in storybook from 23 to 32 so they are a little bit bigger, so i just need to update the screenshot tests.

I see them like this:
TinyGrab Screen Shot 24-07-2019, 15 47 22

**Comment by keip** [comment]
> Please add this braking change to CHANGELOG.md

added

**Comment by keip** [comment]
> Height and width param is still in storybook.
> 
> image

fixed

**Pull request merged**
