### PR TITLE
feat(connect-cardano): add support for babbage features

### PR DESCRIPTION
**Pull request by gabrielKerekes**
This PR contains accompanying Connect updates for the already merged Cardano Babbage changes in Trezor Firmware PR https://github.com/trezor/trezor-firmware/pull/2367 or more specifically https://github.com/trezor/trezor-firmware/pull/2354.

All the changes should be backwards compatible so clients not wishing to leverage the new features shouldn't have to update their code.

We were able to run the Connect integration tests at some point but since then we've updated the tests a little and we haven't been able to run the tests again for some reason, so we're not 100% sure if they are correct. I must say that running the tests against custom built firmware is quite complicated and we'd be interested to know, what your flow is when developing Connect against unreleased FW? Or do you not need to do that? Currently we weren't able to run the tests even against the current FW master for some reason (on both Linux and M1 mac).

We're also not sure if the `transport` package should be updated here or you do that somehow differently so please let us know.

### CODE REVIEW

**Comment by mroz22** [comment]
Hello, thank you for your PR, it looks good in general (as usual). 

> We were able to run the Connect integration tests at some point...

Yes, sorry, we had a bunch of problems with our CI and docker images. Should be fixed now.

> I must say that running the tests against custom built firmware is quite complicated and we'd be interested to know, what your flow is when developing Connect against unreleased FW? 

You are right. I am trying to address this issue in https://github.com/trezor/trezor-suite/pull/5790 (still WIP)

> We're also not sure if the transport package should be updated here or you do that somehow differently so please let us know.

I guess it is ok the way you did it. No formal process for doing this in place at the moment. 

___

So please just a little more patience. I guess only thing I will ask you will be to rebase your branch but I will let you know once develop branch is in good shape.

**Comment by mroz22** [comment]
@gabrielKerekes could you please rebase your branch now? connect tests in develop branch seem to be passing now.

**Comment by gabrielKerekes** [comment]
Rebased on top of current develop, although I didn't run the tests locally.

**Review by mroz22 — APPROVED** [review]
Hi, 
it looks good and [tests are passing](https://gitlab.com/satoshilabs/trezor/trezor-suite/-/pipelines/595797675) so nothing prevents merge. 

I would just like to ask you if you would mind creating PR an the ADA wallet you are maintaining and try to implement connect version 9 there? Altough connect 9 is still in beta, we would like to switch it to production version soon and you are going to need these features anyway right? 

we have a tracker here https://github.com/trezor/trezor-suite/issues/5757

**Comment by gabrielKerekes** [comment]
We'll try integrating Connect v9 into [NuFi](https://wallet.nu.fi/). AdaLite doesn't support smart contracts and so it won't directly benefit from these changes. We will probably update AdaLite to v9 sometime later anyways, but we'd like to try NuFi first (although it's not open source).

**Comment by mroz22** [comment]
Cool, will let you know once we release this so that you can try. Thanks.

**Comment by gabrielKerekes** [comment]
👋 @mroz22 I just realised that you might also be interested in the Connect v9 integration in [Cardano HW CLI](https://github.com/vacuumlabs/cardano-hw-cli/pull/127/files#diff-826ea20816b036c9f6e1397682f6167db2281fa321ff17c2b0723614da2a990dR1) which is a CLI tool running in Node.js. The PR is a WIP and it's based on locally built connect and transport packages based on this PR.

I wanted to ask. Previously we used `import * as TrezorTypes from 'trezor-connect'`to import types from connect. Then we were able to do e.g. `TrezorTypes.CardanoInput` to get the `CardanoInput` type. Currently the only way I was able to get to the type was to do `import * as TrezoTxTypes from '@trezor/connect/lib/types/api/cardanoSignTransaction'` and then `TrezoTxTypes.CardanoInput` to get the type. I think the path I imported is not available in the released beta version. And so is there a better way to import the types? 🤔

Also to access protobuf messages e.g. for the `CardanoTxSigningMode` it was possible to do `TrezorTypes.CardanoTxSigningMode.ORDINARY_TRANSACTION`. Now we need to access the enum via the `PROTO` object in `TrezorTypes` (`TrezorTypes` comes from the `import * as TrezorTypes` mentioned above) i.e. `TrezorTypes.PROTO.CardanoTxSigningMode.ORDINARY_TRANSACTION`.

Is there anyway around this? Or could the types perhaps be made more accessible? 🙏 

(I came upon the same issue with the types now while trying to update NuFi)

**Comment by gabrielKerekes** [comment]
@mroz22 @szymonlesisz could you please take a look at the above message regarding the types? Even with beta.5 I wasn't able to figure how to import e.g. `CardanoSignedTxData`, `CardanoSignedTxWitness` or `CardanoAssetGroup` without importing `import * as TrezorTxTypes from '@trezor/connect/lib/types/api/cardanoSignTransaction'` (which also means I should probably include `@trezor/connect` as a dependency in addition to `@trezor/connect-web`).

We use the types when building the `cardanoSignTransaction` request. Replacing [this line](https://github.com/trezor/trezor-suite/blob/develop/packages/connect/src/types/index.ts#L13) with `export * from './api/cardanoSignTransaction';` solves the problem, but I'm not sure it's desirable. Perhaps `export * as Cardano from ...` might be ok? 🤷

**Pull request merged**
