### PR TITLE
Disable solana unsubscriptions

### LINKED ISSUE #12628: Can't close Trezor Suite with Tor On and Solana account active
**Describe the bug**
If Solana account is activated and Tor is on, I can't close Trezor Suite.

Happens both on 24.5.2.and 24.5.3. and only on Arm Mac
Not reproducible on Linux and Windows yet.

**Steps to reproduce:**
1. Activate Solana account
2. Turn on Tor
3. Close the app
4. Observe app is not closing and in Activity Monitor it's not responding

**Info:**
 - Suite version: desktop 24.5.3 (0ff3e0bd75d90719b7b36a60b3eab1c2bd3d3491)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.5.3 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33

**Expected result:**
App closes

**Screenshots:**
Screenshot 2024-05-29 at 08 43 41

**Note(s):**
related to https://github.com/trezor/trezor-suite/issues/12626 ?

### PR DESCRIPTION
**Pull request by enjojoy**
## Description

Disabled solana accounts unsibscriptions on disconnect

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/12628

## Screenshots:

It does throw some errors but the app closes instantly. 
image

### CODE REVIEW

**Comment by enjojoy** [comment]
@marekrjpolak Does this make sense to you as a temporary solution? The app does close instantly now

**Comment by enjojoy** [comment]
Also checked it out with @martykan , it should be ok. Shall we include it into this release? @tomasklim

**Review by marekrjpolak — APPROVED** [review]
Probably not :100: clean, but I believe it shouldn't cause any serious trouble while it fixes some, so :seal::heavy_check_mark:

**Comment by tomasklim** [comment]
Let's wait with merging. Maybe solana sdk v2 will solve this

**Comment by tomasklim** [comment]
Should be solved by v2 lib

**Pull request closed without merging**
