### PR TITLE
chore(suite-build): add webpack NixosInterpreterPlugin and use it in desktop build

### PR DESCRIPTION
**Pull request by szymonlesisz**
## Description

Follow up of https://github.com/trezor/trezor-suite/pull/6878

Create new webpack plugin and use it to conditionally patch `WabiSabiClientLibrary` on NixOS dev build

### CODE REVIEW

**Review by marekrjpolak — APPROVED** [review]
Works for me!

**Review by mroz22 — APPROVED** [review]
works on my machine but needed to start tor and dont know why

**Comment by szymonlesisz** [comment]
rebased, added console.log to compiler job with status info used/unused

**Comment by szymonlesisz** [comment]
> but needed to start tor and dont know why

this change should not affect tor at all

**Pull request merged**
