### PR TITLE
fix(components): respect `isDisabled` prop in keyboard events

### PR DESCRIPTION
**Pull request by szymonlesisz**
## Description

Even if checkbox/radiobutton is disabled you can still select them using keyboard

### CODE REVIEW

**Comment by komret** [comment]
Good catch. I'd suggest the same approach for both components:

```ts
const handleClick: React.EventHandler<React.SyntheticEvent> = e => {
        if (isDisabled) return;
        onClick(e);
    };
const handleKeyboard = (event: React.KeyboardEvent<HTMLElement>) => {
        if (event.code === KEYBOARD_CODE.SPACE) {
            handleClick(event);
        }
    };
```

I also noticed that `Checkbox` has a green border when it is checked but disabled. Can you fix it to this?
```ts
border: 2px solid
        ${({ $color, isChecked, isDisabled, theme }) =>
            isChecked && !isDisabled ? $color || theme.BG_GREEN : theme.STROKE_GREY};

**Comment by szymonlesisz** [comment]
feel free to do a fixup commit :) im currently in different branch

**Comment by szymonlesisz** [comment]
thanks :+1:

**Review by tomasklim — APPROVED** [review]
LGTM

**Comment by matejkriz** [comment]
adding to Suite Issues so QA knows about it

**Comment by bosomt** [comment]
Thank you @matejkriz  :)
Is there way or need to test this ?

**Comment by komret** [comment]
@boso

How to reproduce the `RadioButton` bug:
- start coinjoin
- go to Details (all should be disabled)
- right-click the "Custom" radio
- press SPACE -> it will change the settings despite the disabled state

There is no way to test the `Checkbox` until https://github.com/trezor/trezor-suite/pull/9021 is merged because we have no disabled checkboxes.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 23.8.0 (549c8f7df73e06cd2542440ec88078a2786170cb)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.8.0 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: Trezor T2T1 2.6.1 Universal (revision 4a6420c5dd038c06a6641331995c7b22cf4c699c)
 - Transport: BridgeTransport 2.0.33

**Pull request merged**
