### PR TITLE
fix(suite): long device name PIN modal

### LINKED ISSUE #8606: PIN modal has broken layout with longer device names
**Describe the bug**
If you have longer device name, PIN entry modal is broken

**Info:**
-  Trezor 1 

**How to reproduce**

1. Give your Model 1 trezor longer name
1. Set PIN for the device
1. Connect the device
1. See error

**Expected behavior**
Longer device label should not break the layout. How to resolve? To be defined. I would expect ellipsis...

**Screenshots**
Device_name-PIN_distorted

### PR DESCRIPTION
**Pull request by AdamSchinzel**
Long device name caused that the UI of modal was a bit broken.

## Description

Moved the device name from modal's heading to modal's description.

## Related Issue

Resolve #8606

## Screenshots:

Screenshot 2023-06-24 at 11 32 28 PM

### CODE REVIEW

**Comment by matejkriz** [comment]
@AdamSchinzel thank you for the fix!

@dahaca @Hermez-cz Please check the solution from UI/UX point of view, we didn't discuss this in advance. This fixes the layout issue, but I'm not sure if the device name is too hidden from the user's point of view. On the other hand, this is only relevant for users who have multiple Trezors connected at the same time, so I find this solution acceptable.

**Comment by dahaca** [comment]
@matejkriz I like it. If you think it's not discoverable enough – the device name can be in bold. Even when you have several devices, it should be kinda clear which one asks for the pin anyways? 

@AdamSchinzel when translations change – they should only be updated in `messages.ts` and it should be mentioned in the PR :)

**Comment by AdamSchinzel** [comment]
> @matejkriz I like it. If you think it's not discoverable enough – the device name can be in bold. Even when you have several devices, it should be kinda clear which one asks for the pin anyways?
> 
> @AdamSchinzel when translations change – they should only be updated in `messages.ts` and it should be mentioned in the PR :)

Thanks for the info. So should I revent any changes in `suite-data/files/translations`?

**Comment by matejkriz** [comment]
> 
> Thanks for the info. So should I revent any changes in `suite-data/files/translations`?

No need to revert anything, we will apply it in Crowding and it will be overwritten during the next synchronization. We should enhance documentation of how to work with translations in Suite...

**Comment by tomasklim** [comment]
I agree with @dahaca's suggestion to bold device name. I also recommend adjusting the translations to position the deviceName at the beginning or in the middle of the sentence. This change can prevent the device name from being split across multiple lines.

**Comment by AdamSchinzel** [comment]
Closing this because it's a PR from my fork, progress in #9002

**Pull request closed without merging**
