### PR TITLE
update connect docs

### PR DESCRIPTION
**Pull request by mroz22**
### update connect docs

- [x] we are waiting for #10181 to be released which implements versioning of docs in connect-explorer.

This PR:
- reverts reverted commit 429db150ed4516b3b08154d537a3b3856bbf88c4

### CODE REVIEW

**Review by karliatto — COMMENTED** [review]
Looks good, but shouldn't we do it also for changelog https://github.com/trezor/trezor-suite/blob/connect-docs/packages/connect-explorer/src/components/PageChangelog.tsx#L6 ?

**Comment by mroz22** [comment]
I believe so, thats why I changed it so that it points to the same commit from which explorer was built 
`https://raw.githubusercontent.com/trezor/trezor-suite/${process.env.COMMIT_HASH}/packages/connect/CHANGELOG.md`,

**Review by karliatto — APPROVED** [review]

**Comment by karliatto** [comment]
> I believe so, thats why I changed it so that it points to the same commit from which explorer was built `https://raw.githubusercontent.com/trezor/trezor-suite/${process.env.COMMIT_HASH}/packages/connect/CHANGELOG.md`,

I was confuse because of the different approach to the `index.md` but now I see it. Thanks!

**Comment by mroz22** [comment]
oh, just one more thing @karliatto. we need to split this PR into 2
- connect-explorer update
- now release connect
- docs update

**Review by karliatto — CHANGES_REQUESTED** [review]
There are still some changes required here.

**Review by karliatto — APPROVED** [review]
:+1:

**Pull request merged**
