### PR TITLE
fix(suite): Hide 'no accounts' in collapsed sidebar

### LINKED ISSUE #15713: Hide "no accounts" in collapsed sidebar
image

### PR DESCRIPTION
**Pull request by jvaclavik**
## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/15713

## Screenshots:

before
image

after
image

### CODE REVIEW

**Review by seibei-iguchi — APPROVED** [review]

**Comment by bosomt** [comment]
**QA NOK**

i can still see it on develop after i disable coins to spawn no accounts text

**Info:**
 - Suite version: web 25.1.0 (b6003e816a7807a9edaf29955cbdab370cec3632)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.5 regular (revision a61e783448043760a7c925e017bd08a4673a61c8)
 - Transport: BridgeTransport 2.0.33

https://github.com/user-attachments/assets/9220773d-7ddb-4512-80d2-ca59f36f5b6d

**Comment by bosomt** [comment]
not sure if not ok or not included in current RC @MiroslavProchazka 

image

**Info:**
 - Suite version: desktop 24.12.1 (ec8321d0d17529ca77d8916e70158cecc469f863)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.12.1 Chrome/128.0.6613.186 Electron/32.2.6 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.6 regular (revision 17f2a3256b2631823c2bad1855fab61b27985fd2)
 - Transport: BridgeTransport 2.0.33

**Comment by MiroslavProchazka** [comment]
It should be part of RC as it was merged before freeze.

**Comment by bosomt** [comment]
**QA NOK**

image

**Info:**
 - Suite version: desktop 24.12.2 (40a2ae63a1d4b21835562f4acad5372ee7fa0a67)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.12.2 Chrome/128.0.6613.186 Electron/32.2.6 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 3.0.0-bundled.24.12.2

**Pull request merged**
