### PR TITLE
Fix/eth swap approve txs

### LINKED ISSUE #4537: Ethereum ERC20 approval transactions do not show fees in transaction history
The ERC20 approval transactions necessary for DEX do not show fees in the transaction history:
image
The detail is correct:
image
The issue is reported on transaction https://eth2.trezor.io/tx/0xaf642709f422116a36e7777db5232288f78f3e09ae77593ba265a09056724e6b but can be reproduced on all approvals.

Probably related to https://github.com/trezor/trezor-suite/issues/4526

Suite Version: web 21.11.2

### LINKED ISSUE #4552: DEX swaps are shown incorrectly in transaction history
**Describe the bug**
Swap transaction of ETH to ERC20 token is displayed incorrectly.

**How to reproduce**
1. Swap ETH for ERC20 on Uniswap, 1inch,...
2. Check transaction history

**Current behavior**
I swapped ETH to UFI. Suite shows:

- `Sent UFI` instead of `Receive UFI` 
- Minus sign before UFI instead of plus sign.
- no ETH spent

**Expected behavior**
- How much ETH I spent
- Correct header and signs

**Screenshots**
Screenshot 2021-11-24 at 16 47 40
Screenshot 2021-11-24 at 16 59 55 (1)

**Additional context**
Related to #4526

### LINKED ISSUE #4557: Transaction daily summary is missing fees
**Describe the bug**
The daily summary in tx history is missing fees.
Related to #4537.

**Info:**
 - Suite Version: 21.11.1

**How to reproduce**
1. Check tx history

**Expected behavior**
It should contain fees.

**Screenshots**
Screenshot 2021-11-25 at 9 57 31

### PR DESCRIPTION
**Pull request by tomasklim**
Fix #4537

Approve tx:
Before: (missing fee)
Screenshot 2021-11-24 at 16 45 00

Now:
Screenshot 2021-11-24 at 16 44 49

Fix #4552

Swap: ETH -> ERC20
Before: (missing ETH payment, wrong ERC20 sign, wrong tx type)
Screenshot 2021-11-24 at 16 47 40

Now:
Screenshot 2021-11-24 at 16 47 46 (1)

Failed transaction: 
Before: (fee missing)
Screenshot 2021-11-24 at 16 52 10
After: 
Screenshot 2021-11-24 at 16 52 16

Fix #4557

Daily summary without fees.
Before:
Screenshot 2021-11-25 at 9 57 31
After:
Screenshot 2021-11-25 at 10 01 56

Not tested: Swap of ERC20 to ETH

### CODE REVIEW

**Comment by martinboehm** [comment]
@tomasklim The change fixes the display of fees. However, the daily summary is shown incorrectly as it does not include the fees, both in bitcoin and ethereum type coins:
image

image

**Comment by tomasklim** [comment]
@martinboehm daily summary should be fixed. Check it now please

**Comment by martinboehm** [comment]
@tomasklim LGTM, thank you!

**Review by szymonlesisz — APPROVED** [review]

**Comment by STew790** [comment]
**QA OK**
After discussion with @tomasklim

**Pull request merged**
