### PR TITLE
fix(invity): add new payment messages

### PR DESCRIPTION
**Pull request by zuzjes**

### CODE REVIEW

**Review by mroz22 — APPROVED** [review]
sry for failing tests, if you rebase now it should pass

**Comment by mroz22** [comment]
actually, why aren't these messages implemented anywhere?

**Comment by slowbackspace** [comment]
@mroz22 ohh, it is used but we couldn't find it because these translation IDs are dynamically generated.
https://github.com/trezor/trezor-suite/blob/118049fdf434b3e63ee5319f6a0cbe4f592f6c7e/packages/suite/src/components/wallet/CoinmarketPaymentType/index.tsx#L58

This will need a proper fix, but this PR at least makes it work so I am approving.

**Review by slowbackspace — APPROVED** [review]

**Comment by mroz22** [comment]
Ok, acceptable :]

**Pull request merged**
