### PR TITLE
Feat/update suite desktop libs

### LINKED ISSUE #4309: Update desktop app libs
We use old versions of libs in `packages/suite-desktop`

E.g. `electron 12` instead of `electron 14`,...

### PR DESCRIPTION
**Pull request by tomasklim**
Lifesaver PR which forced me to try auto-updater and helped me to find stop-release bug.

Closes #4309

1. chore(suite-desktop): update non-electron/build libs (0c3e4b7)
    - libs without breaking changes but `openpgp` where param name changed in patch version
    - some unused libs were deleted
2. chore(suite-desktop): update electron-store lib and type its usage (d5b2701)
    - `any` type changed to `unknown`
3. chore(suite-desktop): update electron and its related libs (cbde469)
    - `new-window` webContents event got deprecated and it was replaced in favor of `setWindowOpenHandler`
    - opening of external links from app has to be tested on all operating systems 🤚🏻
4. chore(suite): bump required node version (f761df6)
    - `electron-builder` requires node 14 and we build our apps in node 14 environment anyway
    - if some developer uses `node 12`, he should update to 14
5. chore(suite-desktop): update electron-builder and handle -x64 extension (6bad772)
    - before update we wanted an app in `Trezor-Suite-${version}-mac-${arch}.${ext}` format. However, there was a bug, so we got only `Trezor-Suite-${version}-mac.${ext}`. Now, after update, the architecture is there. So our app name for Intel mac and for Windows is now `Trezor-Suite-21.10.0-mac-x64.dmg` resp. `Trezor-Suite-21.10.0-win-x64.dmg`
    - I tried to avoid the change but without success. With @matejkriz we decided that it is not good idea to stay on older version of lib or hack it because it could be a problem later.
    - We need to test, that auto-updater works with different names and that it is possible to sign mac app. 🤚🏻
6. chore(suite-desktop): update esbuild (8e45137)
    - `esbuild` is something like `webpack` but faster. They changed transpilation of imports, exports,... and dynamic `import` stopped working
7. chore(suite-desktop): move runtime libs from devDependencies (12a1465)

Summary for QA: 
Everything related to a desktop app has to be tested on all OS. In a web app, everything should remain the same. Most important is auto-update and opening of external links.

### CODE REVIEW

**Comment by tomasklim** [comment]
Auto Update - from and to:
Windows OK
MacOS Intel + M1 OK
Linux OK

**Comment by bosomt** [comment]
**QA OK**

macOS M1 **QA OK** 
Linux Kubuntu 21.03 **QA OK**
Windows 10 **QA OK**

**Comment by wendys-cats** [comment]
**QA OK** 

Windows 10 **OK**
MacOS Big Sur (intel) **OK**

**Review by matejkriz — APPROVED** [review]
Looks good, everything discussed in person. Just the dev mode has to be fixed but it's not part of this PR...

**Pull request merged**
