### PR TITLE
moar fixes

### PR DESCRIPTION
**Pull request by mroz22**
we are going to need messages sync to get rid of this overly long text 
image

### CODE REVIEW

**Review by vladimirvolek — CHANGES_REQUESTED** [review]
develop 
image


this branch

image

**Comment by vladimirvolek** [comment]
The line separator should not start and end at the end of the box.

develop
image


this branch
image

**Comment by vladimirvolek** [comment]
The title is not centered

image

image

**Comment by vladimirvolek** [comment]
Maybe merge the development branch first to see the changes?

**Comment by mroz22** [comment]
Still I think it is better then it was before: 

current develop 
image

image

this branch:

image

image

**Review by vladimirvolek — APPROVED** [review]

**Pull request merged**
