### PR TITLE
Feat/erc20

### PR DESCRIPTION
**Pull request by szymonlesisz**
What should work:
- sending tokens
- set max (+ feature: preserve set max while switching tokens)
- decimals validation
- your token balance (above amount)
- fee levels (gasLimit for tokens is greater from regular eth)
- toast notification and activity (token amount + token symbol)
- warning about not enough ETH to cover ERC20 tx fee

Bugs:
you tell me

### CODE REVIEW

**Comment by bosomt** [comment]
max button is behaving strangely 
max to trop ok, 
to erc20 ok
but back to trop says no funds 
i will observe behavior with non test account or different accounts /accounts with more trop than erc20/

https://www.youtube.com/watch?v=8PCDR3WQsYw&feature=youtu.be
edit: it works fine in different account: https://www.youtube.com/watch?v=6Dqe75nfFp8&feature=youtu.be
but there is moe trop than erc20 in this account

**Comment by szymonlesisz** [comment]
> max button is behaving strangely
> max to trop ok,
> to erc20 ok
> but back to trop says no funds

should be fixed by #https://github.com/trezor/trezor-suite/pull/1845/commits/67b7f0effa9a32a33803680e22a83b867e280e6e

**Comment by bosomt** [comment]
tested by QA and it works fine.
I will forward final results to correct persons today

**Review by vladimirvolek — APPROVED** [review]

**Comment by bosomt** [comment]
tested OK

**Pull request merged**
