### PR TITLE
Revert "chore: update styled components, minor version"

### PR DESCRIPTION
**Pull request by slowbackspace**
This reverts commit 3063d23581d972fe6a11bca11c3318b92bf6b6db.

### CODE REVIEW

**Comment by prusnak** [comment]
Is the issue hard to fix instead of reverting the update?

**Comment by slowbackspace** [comment]
Idk :) I would like to verify if  it is indeed caused by the styled-components upgrade. If so I would still prefer to revert it as we don't know what else is broken because of it and it will for sure cause confusion while reporting bugs around dark mode.

Is there any particular reason why you would prefer to have broken things in develop? :)

**Comment by mroz22** [comment]
Yeah, let's rollback and investigate later. That's actually why I try to update one dependency in one commit, because this can just happen.

**Comment by slowbackspace** [comment]
@mroz22 it really did help, https://suite.corp.sldev.cz/suite-web/fix/landing-headings/
pls let's merge this!

**Pull request merged**
