### PR TITLE
Fix/desktop app quit

### LINKED ISSUE #5055: Suite doesn't relaunch on "Reset app" on Linux
**Describe the bug**
Suite doesn't relaunch when I try to "Reset app" in settings on Linux Ubuntu. (On NixOS it works correctly)

**Steps to reproduce:**
1. Start Suite
2. Go to settings
3. Click on "Reset app"
4. App will quit but won't relaunch

**Info:**
 - Suite version: 22.2.3 (4dc44f620de7f15cdd66970cf22126695435c969)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model 1 1.10.5 regular

**Expected result:**
App will relaunch.

**Actual result:**
App just quits and won't relaunch.

### LINKED ISSUE #5092: Bridge and Tor servers are not properly terminated when you Restart app via Reset app button
**Describe the bug**
Bridge and Tor servers are not properly terminated when you Restart app via Reset app button

**Steps to reproduce:**
1. Start Suite app
2. Reset app settings via `Reset app`
3. Quit second instance of Suite that will be launched.
4. Check that Bridge and Tor servers are running

**Info:**
 - Suite version: desktop 22.3.1 (6b7e7fa25de1c50814fe3bfcd889cf147c93ef24)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.3.1 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: 

**Screenshots:**
```

testing@testings-MacBook-Air MacOS % ps aux | grep rezor                                                      
testing           1042   0.0  0.0 408497296   1376 s002  R+    4:33PM   0:00.00 grep rezor
testing@testings-MacBook-Air MacOS % ./Trezor\ Suite
testing@testings-MacBook-Air MacOS % ps aux | grep rezor
testing           1078   0.0  0.2 409247808  17232 s002  S     4:34PM   0:00.11 /Applications/Trezor Suite.app/Contents/Resources/bin/bridge/trezord
testing           1067   0.0  0.0 408510848   2992   ??  S     4:34PM   0:00.01 /Applications/Trezor Suite.app/Contents/Frameworks/Electron Framework.framework/Helpers/chrome_crashpad_handler --no-rate-limit --monitor-self-annotation=ptype=crashpad-handler --database=/Users/testing/Library/Application Support/@trezor/suite-desktop/Crashpad --url=https://f.a.k/e --annotation=_productName=Trezor Suite --annotation=_version=22.3.1 --annotation=prod=Electron --annotation=ver=15.3.0 --handshake-fd=32
testing@testings-MacBook-Air MacOS % ./Trezor\ Suite    
testing@testings-MacBook-Air MacOS % ps aux | grep rezor
testing           1078   0.0  0.2 409247808  14800 s002  S     4:34PM   0:00.30 /Applications/Trezor Suite.app/Contents/Resources/bin/bridge/trezord
testing           1067   0.0  0.0 408510848   2976   ??  S     4:34PM   0:00.01 /Applications/Trezor Suite.app/Contents/Frameworks/Electron Framework.framework/Helpers/chrome_crashpad_handler --no-rate-limit --monitor-self-annotation=ptype=crashpad-handler --database=/Users/testing/Library/Application Support/@trezor/suite-desktop/Crashpad --url=https://f.a.k/e --annotation=_productName=Trezor Suite --annotation=_version=22.3.1 --annotation=prod=Electron --annotation=ver=15.3.0 --handshake-fd=32
testing           1201   0.0  0.3 409365568  27152 s002  S     4:35PM   0:00.36 /Applications/Trezor Suite.app/Contents/Resources/bin/tor/tor -f torrc
testing           1195   0.0  0.0 408519040   2992   ??  S     4:35PM   0:00.00 /Applications/Trezor Suite.app/Contents/Frameworks/Electron Framework.framework/Helpers/chrome_crashpad_handler --no-rate-limit --monitor-self-annotation=ptype=crashpad-handler --database=/Users/testing/Library/Application Support/@trezor/suite-desktop/Crashpad --url=https://f.a.k/e --annotation=_productName=Trezor Suite --annotation=_version=22.3.1 --annotation=prod=Electron --annotation=ver=15.3.0 --handshake-fd=32
testing@testings-MacBook-Air MacOS % ./Trezor\ Suite    
```

### LINKED ISSUE #5139: ReferenceError: PKG is not defined
https://github.com/trezor/trezor-suite/blob/develop/packages/suite-desktop/src-electron/modules/hang-detect.ts/#L38

Sentry Issue: [TREZOR-SUITE-4YJ](https://sentry.io/organizations/satoshilabs/issues/3110389161/?referrer=github_integration)

```
ReferenceError: PKG is not defined
  File "app:///dist/modules/hang-detect.js", line 1, in Timeout.n [as _onTimeout]
    '{snip} "hang-detect","Quitting app"),c.quit();break;case 2:{let M=PKG.NAME.replace("/",a.default.sep),p=a.default.join(c.getPath("appData"),M,"Cach {snip}
```

### PR DESCRIPTION
**Pull request by tomasklim**
Closes #5139, #5092, #5055

- tor and bridge not killed on autoupdate/restart #5092
- app restart on linux #5055
- app hanging #5139

Has to be tested before merging!

### CODE REVIEW

**Comment by tomasklim** [comment]
~~Adding In progress as Bridge is not killed on autoupdate~~

**Comment by tomasklim** [comment]
Bridge was not killed after autoupdate

Before:
```
2022-03-22T09:03:14.370Z - INFO(app): Quitting
2022-03-22T09:03:14.370Z - INFO(http-receiver): Stopping server (app quit)
2022-03-22T09:03:14.371Z - INFO(tor): Stopping (app quit)
2022-03-22T09:03:14.371Z - WARN(process-tor): Couldn't stop process (already stopped)
2022-03-22T09:03:14.371Z - ERROR(exception): Object has been destroyed
2022-03-22T09:03:14.371Z - INFO(http-receiver): Server stopped
```

Now:
```
2022-03-22T09:01:42.574Z - INFO(app): Quitting
2022-03-22T09:01:42.574Z - INFO(http-receiver): Stopping server (app quit)
2022-03-22T09:01:42.574Z - INFO(tor): Stopping (app quit)
2022-03-22T09:01:42.575Z - WARN(process-tor): Couldn't stop process (already stopped)
2022-03-22T09:01:42.576Z - INFO(bridge): Stopping (app quit)
2022-03-22T09:01:42.576Z - WARN(process-trezord): Couldn't stop process (already stopped)
2022-03-22T09:01:42.576Z - INFO(http-receiver): Server stopped
2022-03-22T09:01:42.580Z - ERROR(exception): Object has been destroyed
```

Test codesign branch @trezor/qa 
https://gitlab.com/satoshilabs/trezor/trezor-suite/-/jobs/2232971240

**Comment by bosomt** [comment]
@tomasklim onit, i will check ` Trezor-Suite-22.3.0-mac-arm64.dmg`

**Comment by bosomt** [comment]
**QA OK**

**macOS m1 OK**
**Windows 10 OK**
**KUbuntu Linux**

tor and trezord are correctly terminated after app is ended or restarted during app storage reset

**Info:**
 - Suite version: desktop 22.3.0 (8ecb68b468d6c640e91c3e96b28131773cb98fac)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.3.0 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.3 regular

**Review by matejkriz — APPROVED** [review]
🎖️

**Comment by matejkriz** [comment]
rebased just to unstack Github checks...

**Pull request merged**
