### PR TITLE
feat(message-system): turn off FW hash check

### PR DESCRIPTION
**Pull request by Lemonexe**
## Description

Turn off FW hash check globally by message system
Tracked in Notion [here](https://www.notion.so/satoshilabs/Disable-Hash-Check-feature-146dc526060680aba6b3dd863ed2dc9c?pvs=4)

[FYI feature flag definition](https://github.com/trezor/trezor-suite/blob/6a811f1d1fa43428ebd67c8df90ab5f122ddef4d/suite-common/message-system/src/messageSystemTypes.ts#L26)

### CODE REVIEW

**Review by MiroslavProchazka — APPROVED** [review]
LGTM

**Review by matejkriz — DISMISSED** [review]
this breaks mobile app, do not merge please

**Comment by Lemonexe** [comment]
@matejkriz fixed, I believe. But we'll only know by redeploying develop

**Review by matejkriz — APPROVED** [review]
Approving for mobile part - mobile should not be affected any more. Haven't test desktop if it works as expected

**Review by komret — APPROVED** [review]

**Pull request merged**
