### PR TITLE
feat(connect): ~~add versionChannel init option~~ connectSrc test

### PR DESCRIPTION
**Pull request by mroz22**
Terms: 

- **pinned** version channel: connect.trezor.io/<9.minor.patch>
- **edge** version channel: connect.trezor.io/9

Behavior:

- [ ] settings.connectSrc is defined -> should be always used
- [ ] settings.connectSrc is not defined && settings.versionChannel is not defined: should use `pinned` versionChannel which resolve to current version of connect. So **'pinned'** is default ? 
- [ ] settings.connectSrc is not defined && settings.versionChannel is set to `edge`. use always the latest released version

### CODE REVIEW

**Comment by sime** [comment]
I'm inclined for `edge` to be the default. Since it is current behaviour, and allows us to roll out changes easier.

Pinning IMHO should be opt-in.

**Comment by mroz22** [comment]
After discussing this with @szymonlesisz we ended up with the conclusion that adding a new option `versionChannel` might be redundant. 

Implementator might achieve the same simply by doing: 

```
TrezorConnect.init({
    connectSrc: 'https://connect.trezor.io/9.0.0/',
    ....
});
```
this is thanks to the fact that with v9 we have started to release every version under its own url. 

So,  I am updating this PR and leaving only the newly added test here which I believe is valuable.

**Comment by sime** [comment]
Can confirm that 9.0.0 and 9.0.2 sites work, but 9.0.1 fails: https://connect.trezor.io/9.0.1/#/

**Comment by mroz22** [comment]
yes, you are right. 9.0.1 was released only into npm and not trezor.io. we had some troubles with CI back then so I released 9.0.2 quickly after since there were already some new changes.

**Comment by mroz22** [comment]
so, now this branch is updated in that way that it contains only tests for setting connectSrc. Passed with green here https://gitlab.com/satoshilabs/trezor/trezor-suite/-/jobs/3115786242

**Review by karliatto — APPROVED** [review]
Looks good!  :+1:

**Pull request merged**
