### PR TITLE
feat(coin-icons): change network separator

### PR DESCRIPTION
**Pull request by FreeWall**
Changing network separator to be compatible with invity coin ids
Enable cron schedule

From `[platform]_[contract_address]` to `[platform]--[contract_address]`
## Related Issue

#13630

### CODE REVIEW

**Comment by tomasklim** [comment]
What's the reason for it?

**Comment by FreeWall** [comment]
To make in compatible with invity-api coin ids, which is `[platform]--[contract_address]`
`_` or `-` is sometimes used in platform identifier, so we wanted to have unique url-safe separator

**Review by vdovhanych — COMMENTED** [review]
So its adding yet another duplicate file to the storage but with a different name?

**Comment by FreeWall** [comment]
It's a replacement, so we can remove the old ones before merging this (they shouldn't be used anywhere yet)

**Comment by tomasklim** [comment]
> To make in compatible with invity-api coin ids, which is `[platform]--[contract_address]` `_` or `-` is sometimes used in platform identifier, so we wanted to have unique url-safe separator

okay makes sense

**Review by tomasklim — APPROVED** [review]

**Comment by vdovhanych** [comment]
> It's a replacement, so we can remove the old ones before merging this (they shouldn't be used anywhere yet)

Well i would like to remove them, is it a specific folder i can delete or there is some prefix i can delete?

**Comment by FreeWall** [comment]
> > It's a replacement, so we can remove the old ones before merging this (they shouldn't be used anywhere yet)
> 
> Well i would like to remove them, is it a specific folder i can delete or there is some prefix i can delete?

Yes please, you can remove everything in coins folder (`/suite/icons/coins/*`), sorry for not being specific before

**Review by vdovhanych — APPROVED** [review]

**Comment by vdovhanych** [comment]
> > > It's a replacement, so we can remove the old ones before merging this (they shouldn't be used anywhere yet)
> > 
> > 
> > Well i would like to remove them, is it a specific folder i can delete or there is some prefix i can delete?
> 
> Yes please, you can remove everything in coins folder (`/suite/icons/coins/*`), sorry for not being specific before

Ok, removing everything from there..

**Review by vdovhanych — APPROVED** [review]

**Pull request merged**
