### PR TITLE
chore(suite-desktop): downgrade electron

### PR DESCRIPTION
**Pull request by Lemonexe**
## Description

Downgrade electron from 33 to 32.

It shall be kept at 32 until we are ready to cut off macOS Catalina.

:information_source: [electron 32 support](https://github.com/electron/electron/tree/v32.2.8?tab=readme-ov-file#platform-support)
:information_source: [current electron support](https://github.com/electron/electron/blob/main/README.md#platform-support)
:information_source: [systems supported by Suite](https://trezor.io/learn/a/os-requirements-for-trezor)

### CODE REVIEW

**Review by komret — APPROVED** [review]

**Comment by komret** [comment]
Let's not merge this yet, final decision TBD.

**Comment by Lemonexe** [comment]
As discussed on standup, I'll merge this, following implementation of OS analytics in #15789

**Comment by bosomt** [comment]
**QA OK**

```
browserName=electron&browserVersion=32.2.6
```

**Info:**
 - Suite version: desktop 25.1.0 (5557f53cb2cf58399a923ca708f05ac193970385)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/25.1.0 Chrome/128.0.6613.186 Electron/32.2.6 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.6 regular (revision 2625facf1fe9b71db120439853ceca0a61bb8396)
 - Transport: BridgeTransport 2.0.33

**Comment by bosomt** [comment]
**QA OK**

`electron&browserVersion=32.2.6`

**Info:**
 - Suite version: desktop 24.12.1 (0d4070d9dcac69cfad8e208ed8acc09f89a5c985)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.12.1 Chrome/128.0.6613.186 Electron/32.2.6 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.6 regular (revision 17f2a3256b2631823c2bad1855fab61b27985fd2)
 - Transport: BridgeTransport 2.0.33

**Pull request merged**
