### PR TITLE
@trezor/utxo-lib 2.0.0

### PR DESCRIPTION
**Pull request by szymonlesisz**
## Description

I didn't touch the core logic (yet). Breaking changes applies only to parameters and response from `composeTx` module used in `@trezor/connect` and `@trezor/suite`.
Main goal was to unify interfaces and make them generic (what you put in is what you get out)

Commits are atomic and as small as possible for easier review. Enjoy :)

### ⚠️  BREAKING CHANGES in `@trezor/utxo-lib/composeTx` module

renamed `composeTx` request parameters and response.

-   request `utxo.tsize` is removed
-   request `utxo.vsize` is removed
-   request `utxo.addressPath` is removed
-   request `utxo.height` > `utxo.confirmations`
-   request `utxo.value` > `utxo.amount`
-   request `utxo.index` > `utxo.vout`
-   request `utxo.transactionHash` > `utxo.txid`
-   request `output.type = 'complete'` > `output.type = 'payment'`
-   request `output.type = 'noaddress'` > `output.type = 'payment-noaddress'`
-   request `changeAddress: string` > `changeAddress: { address: string }`
-   request `height` is removed
-   request `basePath` is removed (not used)
-   request `changeId` is removed (not used)

-   response nested `transaction` object is removed. Final result contains fields `inputs`, `outputs` and `outputsPermutation`
-   response `nonfinal` result contains `inputs`
-   response `transaction.input.index` > `input.vout`
-   response `transaction.input.hash` > `input.txid`
-   response `transaction.outputs.sorted.value` > `output.amount`
-   response `transaction.outputs.sorted.opReturnData: Buffer` > `output.dataHex: string`
-   response `output.type` added (only for final output types: `payment`, `opreturn` and `send-max` which becomes `payment` after amount calculation)
-   response `type = 'error'` is strongly typed

-   request `utxo` is generic and should be equal to `transaction.input` (ComposeInput)
-   request `output` is generic and should be equal to `transaction.output` (ComposeOutput + ComposeChangeAddress)
-   request `changeAddress` is generic and should be equal to `transaction.output.type = 'change'`

### ⚠️ (possible) BREAKING CHANGES  in `@trezor/connect`

We may assume that no one (3rd party popup or nodejs users) are not using  `composeTransaction` method as we do in `@trezor/suite` (which means only to create transaction params used later by `signTransaction`) so i guess we don't need to create breaking change version.

- `composeTransaction` (precompose variant) params and response changes are the same as in `@trezor/utxo-lib`
- `composeTransaction` types unification

## Related Issue
Related https://github.com/trezor/trezor-suite/issues/4528

### CODE REVIEW

**Review by mroz22 — APPROVED** [review]
✅  Changes make sense to me. 

💡 I am sure I might have missed something during the review so please lets have also @marekrjpolak have a look.

👍 Thumbs up for how commits are organized

**Review by marekrjpolak — APPROVED** [review]
```diff
+861
-1,409
```
Nice!

**Comment by szymonlesisz** [comment]
thanks for review :+1: 

i think i will add two more breaking changes so we dont have to do them in the future:
1. i will move `final` response transaction data from nested `transaction` object to top level,
   this change will separate `transaction.outputs.sorted` and `transactions.outputs.permutation`  and makes it more readable
1. `not-final` result from composeTx will contains `inputs` to be able to show them in sendform coin control

**Comment by szymonlesisz** [comment]
@mroz22 + @marekrjpolak 

I've changed few things since you did the review:
- the final response fom `composeTx` is no longer wrapped in `transaction` object [75d3dd3](https://github.com/trezor/trezor-suite/pull/9143/commits/75d3dd388073b536356701c351356b4bc4401e8d)
- nonfinal response from `composeTx` returns inputs (useful for "coin control" view in suite) [ace97a2](https://github.com/trezor/trezor-suite/pull/9143/commits/ace97a26776f32af3ccadca4a850a27c7543c69e)
- cleanup in types/interfaces used and exported by connect [923314f](https://github.com/trezor/trezor-suite/pull/9143/commits/923314f033e804b09206e07ca1ded5fc8fbc20f9) + adjusting tests fixtures
- cleanup in types/interfeces used by suite [392e08c](https://github.com/trezor/trezor-suite/pull/9143/commits/392e08c519bfbe7d2d162ec80e2bb466585f6ff9) + adjusting tests fixtures

**Review by mroz22 — APPROVED** [review]
checked follow up commits, seem reasonable.

**Comment by mroz22** [comment]
still no conflicts 🙏 my plan is to merge this after connect 9.1.2 has been in production for a day or two and we will have data about this api usage
its already in progress https://github.com/trezor/trezor-suite/pull/9290

**Pull request merged**
