### PR TITLE
feat(analytics): use suite versioning for analytics

### LINKED ISSUE #5856: Analytics: use Suite versioning
Right now, we are using custom analytics versioning.

The problem is that if we do not change analytics in a specific Suite version, the analytics version is not bumped. However, analytics data can change or get broken, because there can be a change which can influence analytics. This can result into different behavior of the same version of analytics.

### PR DESCRIPTION
**Pull request by tomasklim**
## Related Issue

close #5856

## Screenshots (if appropriate):
Screenshot 2022-09-07 at 16 16 04

### CODE REVIEW

**Comment by matejkriz** [comment]
please update also this description: https://github.com/trezor/trezor-suite/tree/feat/analytics-versioning/packages/suite-analytics#versioning

**Comment by tomasklim** [comment]
> please update also this description: https://github.com/trezor/trezor-suite/tree/feat/analytics-versioning/packages/suite-analytics#versioning

Oh I was looking for it, but could not find it. I will do

**Comment by tomasklim** [comment]
> please update also this description: https://github.com/trezor/trezor-suite/tree/feat/analytics-versioning/packages/suite-analytics#versioning

@matejkriz updated

**Comment by tomasklim** [comment]
@matejkriz updated

**Review by matejkriz — APPROVED** [review]
please change the link also in docs https://github.com/trezor/trezor-suite/blob/feat/analytics-versioning/docs/analytics/index.md?plain=1#L45

**Pull request merged**
