### PR TITLE
e2e(@group:suite): update snapshots

### PR DESCRIPTION
**Pull request by tomexx**

### CODE REVIEW

**Comment by mroz22** [comment]
Hello!
Why is this needed? In ideal world, snapshot update should come together with some code changes that actually change appereance or something.

**Comment by tomexx** [comment]
> Hello!
> Why is this needed? In ideal world, snapshot update should come together with some code changes that actually change appereance or something.

There was some failed job in the pipeline, some snapshots had a few px difference when I checked the diff. So I tried to run the pipeline again with updated snapshots. But there might be some other weird cause of this because the problem disappeared after second run.
image

**Comment by mroz22** [comment]
I would suggest that you simply remove this snapshot. 

https://github.com/trezor/trezor-suite/blob/8dc2e3b911bd39e36532dd3bbdcb87019a42a409/packages/integration-tests/projects/suite-web/tests/suite/static-pages.test.ts#L12

There is nothing so special about it that would justify slowing you down with occasional errors. @wendys-cats will once write complex test case for bridge modal I'd say :wink:

**Comment by mroz22** [comment]
Look at this. Maybe it helps and it also tests something :D https://github.com/trezor/trezor-suite/pull/3491

**Comment by tsusanka** [comment]
So should we close this on behalf of #3491?

**Comment by tomexx** [comment]
yes, let's get rid of this

**Pull request closed without merging**
