### PR TITLE
feat(coinmarket): hide unrecognized tokens in trade section

### LINKED ISSUE #11341: Hide unrecognized tokens in sell and exchange
In Trade section we still show tokens are unrecognized by coingecko.
Users might have several scamy tokens with same name on the account and no way to know which are scamy ones.

Example contracts:
```
0x32819d807Af179EB93f510191607Dba58d27152f
0x6d995217db76437ea053770dDaB27aA90a298bCa
0xC377cF8Ea22eBc196D9C376B1cc952B633bfBC81
0xB9b207eF957fB679CaAE55C0E3ae9cB404503cd9
0x2B90d84FE76c33f3Dc1ADAf645D6f6202B4b853A
```

image

**Expected behavior**
Since we’re unable to trade those tokens anyway, we need to hide them from exchange and sell forms.

### PR DESCRIPTION
**Pull request by FreeWall**
## Description

Hide unrecognized tokens in sell and exchange section

## Related Issue

Resolve #11341

### CODE REVIEW

**Review by tomasklim — CHANGES_REQUESTED** [review]
Please use logic added in #10034

**Comment by AdamSchinzel** [comment]
Hmm I did some refactor on these places in https://github.com/trezor/trezor-suite/pull/11347 and actually think that it's a better way to build options based on fiat rates not token definitions because from what I saw all tokens with fiat rates have definitions but not all tokens with definitions have fiat rates (e. g. Golem token on all seed wallet).

**Comment by FreeWall** [comment]
> Hmm I did some refactor on these places in #11347 and actually think that it's a better way to build options based on fiat rates not token definitions because from I saw all tokens with fiat rates have definitions but not all tokens with definitions have fiat rates (e. g. Golem token on all seed wallet).

I think we are fine with excluding tokens without fiat rates, that was the goal.
@marek-andrsk can you confirm pls?

**Comment by AdamSchinzel** [comment]
Yes but token definitions don't necessarily mean they have fiat rates so there will be tokens without rates...

**Comment by FreeWall** [comment]
I see, so this PR can be closed in favor of #11347 I guess because you made this change what I originally needed :-), https://github.com/trezor/trezor-suite/pull/11342/commits/038751d89d7785506a0ef307add3aec2cc603f35 vs https://github.com/trezor/trezor-suite/pull/11347/commits/b7c5722b8800f722a84ed95dcf14d6dfff77f06e#diff-6ced21cec624e4d780f272bfd647f19a76a405819c6678f4db0d167c69bb7eabR83

**Review by AdamSchinzel — APPROVED** [review]
LGTM

**Review by tomasklim — APPROVED** [review]

**Pull request merged**
