### PR TITLE
fix(translations): corrections and minor nitpicks

### PR DESCRIPTION
**Pull request by 1000101**
Some minor improvements of the flaws I've noticed during onboarding. Hope it makes sense!

### CODE REVIEW

**Comment by slowbackspace** [comment]
@1000101 thanks for your wonderful contribution ❤️. However these changes need to be done in https://github.com/trezor/trezor-suite/blob/develop/packages/suite/src/support/messages.ts

en.json is just auto generated from Crowdin using definitions from messages.ts as a fallback.

Check https://docs.trezor.io/trezor-suite/misc/localization.html#message-definitions for more information 😁

**Comment by szymonlesisz** [comment]
well fuck :)

**Comment by szymonlesisz** [comment]
well, sorry :) i was so excited by @1000101 contribution that i've merge it :)

**Comment by slowbackspace** [comment]
@szymonlesisz 😁 , not a huge problem. It will simply be replaced with next crowdin sync. I'll make necessary changes to message definitions.

**Pull request merged**
