### PR TITLE
fix(connect): disallow interaction-less fw update when switching fw type

### LINKED ISSUE #13106: Error: Different firmware vendor when switching Universal 2.7.0 to BTC only 2.7.2
**Describe the bug**
Error: Different firmware vendor when switching Universal 2.7.0 to BTC only 2.7.2
I was not able to replicate it via 2.7.0 btc > 2.7.2 universal or Uni 2.7.2 > BTC 2.7.2

**Steps to reproduce:**
1. Install 2.7.0 universal
2. Setup device
3. Change to 2.7.2 btc only

**Info:**
 - Suite version: desktop 24.6.2 (b319fb1a1e4e2fb85e398589dec064c26450bab0)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.6.2 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**

https://github.com/trezor/trezor-suite/assets/31506317/94da8437-3526-4f9a-bed6-882f9cd922a3

### PR DESCRIPTION
**Pull request by mroz22**
it looks like it is not possible to have all of these at once:
 - change firmware type 
 - update firmware to a higher version
 - do it interaction-lessly

 should fix #13106. 

cc @komret 
i might have broken something else, please check on it 🙏  @marekrjpolak

### CODE REVIEW

**Comment by marekrjpolak** [comment]
Logic seems good, I've just
- https://github.com/trezor/trezor-suite/pull/13149/commits/afbe326c3529c46bb7b42eab343d46a36b546e6e - fixed a bug of not passing `btcOnly` param to second `getBinaryHelper` call, and
- https://github.com/trezor/trezor-suite/pull/13149/commits/3014523bd7fcb6aca6d883dbb81cee0316d4b466 - simplified conditions for `btcOnly` and `isUpdatingToEqualFirmwareType`

**Review by marekrjpolak — APPROVED** [review]
Tested.

**Comment by mroz22** [comment]
vielen dank!

**Comment by bosomt** [comment]
**QA OK**

image

**Info:**
 - Suite version: desktop 24.7.1 (88dbe0410ac5b6245f392ce13e8c30f0f8f549f2)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.7.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.8.0 bitcoin-only (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 3.0.0

**Pull request merged**
