### PR TITLE
Fix: Desktop Updater

### LINKED ISSUE #2550: App download - MacOS zip contents, unable to install app
**Info:**
 - OS: any
 - Browser: N/A
 - Suite Version: .zip from staging 426ce98f
 - Firmware Version: N/A
 
**Describe the bug**
Contents of the .zip file of the MacOS version does not allow installation of the app.

**Steps to reproduce:**
1. Navigate to the landing page
2. Select the MacOS version of the app and download the .zip file
3. Unpack the .zip file

**Expected result:**
A .dmg or .pkg file is inside the .zip that allows an easy installation.

**Actual result:**
A folder with a .exe file is unpack from the .zip with no .dmg or .pkg file present.

**Screenshots:**
N/A

### PR DESCRIPTION
**Pull request by keraf**
This PR contains
- Added back missing version button and commit hash tooltip on the settings page #2525 
- Added new version button that sends the user to the release page of the latest release.
- Disabled update checking on dev builds.
- Removed `tar.gz` target for Linux builds and `zip` for Windows builds. Added `dmg` to Mac builds. Fixes #2550 
- Updating landing page and CI to reflect target updates.
- Added runtime flag to disable CSP `--disable-csp`. 
- Disabled differential downloads (caused issues with download progress and cancellation).
- Fixed issue with download cancellation not resetting view (back to download available page).

### CODE REVIEW

**Comment by tsusanka** [comment]
@keraf Typescript lint is failing, can you check it out please?

**Comment by tsusanka** [comment]
> Added runtime flag to disable CSP --disable-csp.

What are the security consequences of this? I am thinking in the terms of a malware which can restart Suite with the flag on.

**Comment by keraf** [comment]
@tsusanka Content Security Policy helps mainly to prevent XSS. Disabling the CSP is necessary for using Dev Tools in production builds though. I think we could display a alert message if the application is run with this flag. Is that acceptable?

**Comment by tsusanka** [comment]
Ok that sounds reasonable. Why do we need Dev Tools in production btw? For QA?

Btw I would suggest to move it into a separate PR (both the flag and the alert message) so we do not delay this one (I would really like to merge this one because of the fix builds for QA).

**Comment by tsusanka** [comment]
I tried to review as best as I could, but obviously I am not the right person to do that. As discussed we are merging now and @szymonlesisz will have a look "post mortem" on Monday. We really really need to pass this one to QA.

**Pull request merged**
