### PR TITLE
fix(wallet-utils): remove eth 0 value error

### LINKED ISSUE #8959: Error: Amount has to be greater than 0
Sentry Issue: [TREZOR-SUITE-TJP](https://satoshilabs.sentry.io/issues/4327071539/?referrer=github_integration)

```
Error: Amount has to be greater than 0
  at Kp (/js/main.d4ac2cf5.js:1:388804)
  at None (/js/main.d4ac2cf5.js:1:399906)
  at None (/js/vendors.be2d9e0b.js:2:2324730)
  at dispatch (/js/vendors.be2d9e0b.js:2:2328062)
  at None (/js/main.d4ac2cf5.js:1:399595)
...
(5 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by tomasklim**
## Description

- zero is valid when having data

## Related Issue

closes #8959

### CODE REVIEW

**Review by komret — APPROVED** [review]
It works, it is now possible to send a transaction with data and 0 ETH, but the receiving transaction should provide some more info (at least show the 0 amount):

Screenshot 2023-08-04 at 15 41 29

**Comment by komret** [comment]
**QA:** It should be possible to send a 0 ETH transaction as long as it has Data (added via the _Add Data_ option). This does not fix related bugs described in https://github.com/trezor/trezor-suite/issues/9063.

**Comment by bosomt** [comment]
**QA NOK**

im still not able to send 0 ETH tx

image

image


**Info:**
 - Suite version: desktop 23.9.0 (b5c24aa43350998ed132edf093927558d6dde36b)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.9.0 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: Trezor T2T1 2.6.1 regular (revision b151a3db6b04d2bee0bb68470e57b822443bf83d)
 - Transport: BridgeTransport 2.0.33

**Comment by komret** [comment]
@bosomt, This is because of point 3 in https://github.com/trezor/trezor-suite/issues/9063. Amount validation is not triggered at the right time. This PR only enables sending a 0-value transaction if the amount field is the last one edited. So, it is still broken, but at least some small progress has been made...

**Pull request merged**
