### PR TITLE
web: Add PWA support

### PR DESCRIPTION
**Pull request by prusnak**
* see https://web.dev/progressive-web-apps/ for more info
* among other things this enables "Add to Home Screen" feature and webapp can act as a regular app
* not sure how to handle paths in `manifest.json` - I hardcoded `/wallet` - but this is not ideal, because then the dev build does not work

That's essentially the same thing we already have on the current [Wallet](https://wallet.trezor.io/manifest.json)

### CODE REVIEW

**Comment by mroz22** [comment]
PWA is definitely a nice thing, but is there some built-in mechanism for cache invalidation? Something like this will be probably needed in order to avoid user running multiple outdated versions unknowingly https://medium.com/progressive-web-apps/pwa-create-a-new-update-available-notification-using-service-workers-18be9168d717

**Comment by keraf** [comment]
I think this needs some work to meet all the requirements of a PWA and improve the experience. I would suggest looking at Workbox and integrate it into our build process so we can generate the precache manifest and build the service worker.

**Comment by keraf** [comment]
This is still work in progress for now. Removed the "READY TO REVIEW" label.

Testing the whole PWA setup with Lighthouse doesn't work on localhost with a self signed certificate (exception flags are broken...). Hopefully it will work on sldev.

**Comment by keraf** [comment]
This is now ready :slightly_smiling_face: It requires trezor/connect#682 to work properly.

@prusnak How can I squash my fixups? I've committed a lot of them to test small changes on deployed dev environments.

**Comment by prusnak** [comment]
> How can I squash my fixups?

```
git rebase -i develop --autosquash
git push --force-with-lease
```

`--autosquash` takes all commits with the `fixup!` prefix and squashes them into the commit they belong to

**Comment by szymonlesisz** [comment]
- First load (precacheing) occasionally takes really long time and it ends up with suite timeout error "Loading takes too long"
 maybe this timeout should be started after service-worker load process end?
- when you switch service worker to a offline mode you are not able to make `trezord` calls (blocked by worker? or browser it self? idk)
Screenshot 2020-10-01 at 10 57 48

**Comment by keraf** [comment]
I'll address the pre-caching issue. Probably by ignoring the service worker registration in the loading timeout.

For the requests not working on `trezord`, I guess this is a behaviour of the browser when enabling offline mode in the dev tools. In the real world, localhost would be available if the device is not connected to a network.

**Comment by keraf** [comment]
Closing this one in favour of #3446 (PWA addressed there)

**Pull request closed without merging**
