### PR TITLE
feat(suite-guide): update suite guide version

### LINKED ISSUE #3: replace links to old wiki.trezor.io by new help center links https://trezor.io/learn
Article name | Category | Type | Current URL | Change to | Checked
-- | -- | -- | -- | -- | --
Passphrase | Security | Guide to KB | https://blog.trezor.io/is-your-passphrase-strong-enough-d687f44c63af | https://trezor.io/learn/a/passphrases-and-hidden-wallets | No
Shamir Backup | Security | Guide to KB | https://wiki.trezor.io/Shamir_Backup | https://trezor.io/learn/a/what-is-shamir-backup | No
Single Backup | Security | Guide to Shop | https://wiki.trezor.io/Recovery_seed | https://trezor.io/learn/a/how-to-use-a-recovery-seed | No
Single Backup | Security | Guide to KB | https://wiki.trezor.io/Recovery_seed | https://trezor.io/learn/a/how-to-use-a-recovery-seed | No
Supported Coins | Supported Crypto | Guide to Trezor Web | https://trezor.io/coins/ | https://trezor.io/coins/ | No
Supported Coins | Supported Crypto | Guide to Shop | https://shop.trezor.io/btc-only/ | https://trezor.io/learn/a/bitcoin-only-firmware-on-trezor | No
Accounts | Suite Basics | Guide to KB | https://wiki.trezor.io/Taproot | https://trezor.io/learn/a/what-is-taproot | No
Accounts | Suite Basics | Guide to KB | https://wiki.trezor.io/User_manual:Updating_the_Trezor_device_firmware | https://trezor.io/learn/a/update-trezor-device-firmware | No
Suite Guide | Suite Basics | Guide to Trezor Web | https://trezor.io/coins/ | https://trezor.io/coins/ | No
Suite Guide | Suite Basics | Guide to KB | https://wiki.trezor.io/ | https://trezor.io/support/ | No
Locktime | Suite Basics | Guide to KB | https://wiki.trezor.io/Transaction | https://trezor.io/learn/a/addresses-transaction-history | No
Locktime | Suite Basics | Guide to KB | https://wiki.trezor.io/Trezor | https://trezor.io/learn/a/locktime-in-trezor-suite-app | No
Send Overview | Suite Basics | Guide to KB | https://wiki.trezor.io/Taproot | https://trezor.io/learn/a/what-is-taproot | No
Contact Support | Support & Feedback | Guide to KB | https://trezor.io/support/ | https://trezor.io/support/ | No

[Suite Guide links bce97844542e4f6a9c0c7dd5c918044b (2).csv](https://github.com/trezor/trezor-suite-guide/files/9852663/Suite.Guide.links.bce97844542e4f6a9c0c7dd5c918044b.2.csv)

### PR DESCRIPTION
**Pull request by jerechinsky**
## Description
- Replacing all old wiki.trezor.io links with trezor.io by @b-irving 
- Article "Dust & Dust Limit" added to Suite Guide by @b-irving 
- Typos fixed in "Self-Hosted full node" article by @b-irving 
- Trade section review and update by J. Dohnal

https://github.com/trezor/trezor-suite-guide/commit/3762d38f4dc4f28ce6e9f051559517649202858e

fixes trezor/trezor-suite-guide#3

### CODE REVIEW

**Comment by matejkriz** [comment]
@alex-jerechinsky 
image in Save Bitcoin section in Trade article is broken
image
https://github.com/trezor/trezor-suite-guide/commit/74217c1e90818f150fd612a98e508a00e1767172#diff-52061e99bafda8a857ffbfabccd9893249fb615fe1d3e9963f26cb08e1cbd662R96

**Comment by b-irving** [comment]
@matejkriz @alex-jerechinsky I have updated the image

**Comment by jerechinsky** [comment]
I've updated the commit ID from Ben's fix. @matejkriz 

https://github.com/trezor/trezor-suite-guide/commit/a1594d259de4f4687e19ae7f8c38a85c9e0f8b4a

**Comment by matejkriz** [comment]
Dust & Dust Limit has two `:bulb:`s instead of 💡 🤔 

Please try to insert the emojis directly and not their codes.
  
image

**Review by matejkriz — APPROVED** [review]
squashed to 1 commit

**Pull request merged**
