### PR TITLE
feat: add tip warning the developers that they may have bridge disabled in the debug settings

### PR DESCRIPTION
**Pull request by peter-sanderson**
- Tip shows only if you have debug mode on + disabled both bridge and legacy bridge

image

### CODE REVIEW

**Review by mroz22 — CHANGES_REQUESTED** [review]
please test web.

and this.. 
```
&& !bridgeSettings?.legacy
```
is it needed? I am not sure I get why

**Review by mroz22 — COMMENTED** [review]
this is gonna have conflicts with #15615 which contains some important fixes and I want to merge it first. So this should wait. 

otherwise it looks ok. 

btw don't we want to have some top level signaliation of debug mode active? something like a red square in the top right corner, exactly the same emulator does it?

**Comment by peter-sanderson** [comment]
> btw don't we want to have some top level signaliation of debug mode active? something like a red square in the top right corner, exactly the same emulator does it?

Interesting idea we have the icon in the dashboard of the suite. But nothing on the welcome screen/fullscreeen layouts

**Review by mroz22 — APPROVED** [review]
imho ok. cc @Hermez-cz in case you guys want to solve some global debug mode signalization.

**Comment by bosomt** [comment]
**QA OK**

after i enabled debug and disabled bridge
as soon i disabled debug mode its gone :)

image


**Info:**
 - Suite version: desktop 25.1.0 (0b116799334cb4a05fcb59cc480deb7c4b9a63e9)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/25.1.0 Chrome/128.0.6613.186 Electron/32.2.6 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.7 regular (revision e196413bb745443610211c325623ba7cee7309e9)
 - Transport: BridgeTransport 2.0.33

**Pull request merged**
