### PR TITLE
feat(suite): polish app for mobile devices

### LINKED ISSUE #4417: Polish Suite for Android
As the React Native is not yet being tackled let's give Android a few days to improve the web experience as much as possible. In another words let's do as many "low hanging fruits" in a few days as possible.

Let's bother Product as much as needed in this issues.

### PR DESCRIPTION
**Pull request by tomasklim**
close #4417

Sorry, only 1 commit 😵‍💫

It would be nice if @STew790 check it on Android phone.

Mostly only media queries for mobile were added. Also, there is a change in index.html where I added metadata viewport for mobiles. There are also changed components in debug settings. Tested for 400px device with model 1 and T.

### CODE REVIEW

**Comment by matejkriz** [comment]
if it's just one commit, at least it's a small one 😜

**Review by marekrjpolak — APPROVED** [review]
Valid and definitely better than before (tested only in desktop browser).

**Comment by STew790** [comment]
I left a comment about my findings in the issue here https://github.com/trezor/trezor-suite/issues/4417#issuecomment-981779581

**Comment by tomasklim** [comment]
@marekrjpolak could you please check fixup?

**Review by marekrjpolak — APPROVED** [review]
Fixup OK

**Pull request merged**
