### PR TITLE
feat: add metadata labels in exports

### LINKED ISSUE #3185: Include labels in the TX export
At the moment, labels are not included in the export. Let's include them in a separate column.

### PR DESCRIPTION
**Pull request by mroz22**
will resolve #3185 but it really needs some product decisions how the resulting files should look like

### CODE REVIEW

**Comment by jerechinsky** [comment]
Instead of separating multiple addresses and OP_RETURN in one transaction by the pipe symbol like Suite is doing it right now: 

Screenshot 2021-07-28 at 17 43 17

I suggest that we separate the addresses and OP_RETURN by putting them on a new line and then put the label after a hyphen, like so: 

Screenshot 2021-07-28 at 17 30 24

@matejzak what do you think?

**Comment by mroz22** [comment]
Hmm I actually don't think that creating some newlines inside cell in a csv is a good approach (pdf is fine). So, so far I have done it as @alex-jerechinsky suggested but without these newlines. You can check this branch on dev server

**Review by matejkriz — APPROVED** [review]

**Comment by bosomt** [comment]
@mroz22 can you please check this  export ? looks like some labels ale breaking file formatting, probably just label size, maybe we can consider to limit label size during export ?

[export-btc-1627987246393.csv](https://github.com/trezor/trezor-suite/files/6923521/export-btc-1627987246393.csv)

[export-btc-1627987388820.pdf](https://github.com/trezor/trezor-suite/files/6923518/export-btc-1627987388820.pdf)

**Comment by mroz22** [comment]
csv is format intending to provided machine readable data in the first place. So label sizes really dont matter. I accept only stuff that break lines / columns, etc.

**Pull request merged**
