### PR TITLE
Load CoinLogo's from svg files

### LINKED ISSUE #329: Load CoinLogo's from svg files

### LINKED ISSUE #339: fix Header logo
Load it from TrezorLogo component

### LINKED ISSUE #343: Fix cypress snapshot tests for svg files
after changing all images to svg our cypress snapshot tesst is failing:
TinyGrab Screen Shot 01-08-2019, 13 56 04

### LINKED ISSUE #362: components: missing icon
image

I dont see `ARROW_RIGHT` :crying_cat_face: could you add @keip ?

### PR DESCRIPTION
**Pull request by keip**
closes #329 
closes #343 
closes #339
closes #362

### CODE REVIEW

**Comment by slowbackspace** [comment]
just making sure... please test the Trezor Suite (with rebuilding libs) if everything works as it should before merging this PR

**Comment by slowbackspace** [comment]
size of the icons in suite needs a little tweaking:
this branch:
Screenshot 2019-08-19 at 11 16 37

develop:
Screenshot 2019-08-19 at 11 16 42

**Review by slowbackspace — CHANGES_REQUESTED** [review]
see comments

**Comment by slowbackspace** [comment]
tests are failing Screenshot 2019-08-19 at 12 53 42

**Comment by keip** [comment]
> size of the icons in suite needs a little tweaking:
> this branch:
> Screenshot 2019-08-19 at 11 16 37
> 
> develop:
> Screenshot 2019-08-19 at 11 16 42

fixed

**Comment by keip** [comment]
> tests are failing Screenshot 2019-08-19 at 12 53 42

fixed

**Pull request merged**
