### PR TITLE
fix: unaligned check-boxes in backup modal

### LINKED ISSUE #2713: Unaligned checkbox items in Backup modal
See

unaligned

### LINKED ISSUE #2720: Inconsistent close buton in some modals
Let's remove all "cancel"/"close" buttons in modals and replace them with default close btn in the upper right corner.

Be aware that probably not all steps have close button, so it won't be enough to set `cancelable` prop for the whole modal flow (eg in case of backup check/dry run there are steps where we don't want to allow user to cancel the modal).

image

### PR DESCRIPTION
**Pull request by robertbrada**
fix https://github.com/trezor/trezor-suite/issues/2713
fix https://github.com/trezor/trezor-suite/issues/2720

I fixed the distorted layout and removed redundant "close modal" buttons in **Backup** modal and **Check Seed** modal. New layout looks like this:

backup-fix

### CODE REVIEW

**Comment by robertbrada** [comment]
I found more visual problems related to backup modals, I will fix that
 in this PR as well

**Comment by slowbackspace** [comment]
e2e tests are failing
` AssertionError: Timed out retrying: Expected to find element: `[data-test="@backup/close-button"]`, but never found`
Looks like tests for backup are still trying to click removed close button. Basically you need to find all clicks on `@backup/close-button` and replace them by click on modal's close btn (`data-test="@modal/close-button"`).
Eg. few of these are in [`passThroughBackup` function](https://github.com/trezor/trezor-suite/blob/ffe96ca0ccf23872991c33e85b0728d062552f77/packages/integration-tests/projects/suite-web/support/utils/shortcuts.ts#L34)

Send me a message on slack if you'll need help with this :)

**Comment by slowbackspace** [comment]
Just so we don't forget what's going on here... We are not really sure if we really should delete all standalone close buttons in backup flow since it is also used as part of the onboarding modal, one solution would be to set cancel button on the onboarding modal itself, but that may have UX consequences... To be discussed with @matejzak

**Comment by robertbrada** [comment]
The issue with unaligned checkboxes was already fixed in a separate PR.

**Pull request closed without merging**
