### PR TITLE
fix(connect): emit changed event with state change in keepSession

### LINKED ISSUE #15226: Suite needs passphrase input for every action after reconnecting to view only wallet
**Describe the bug**
When I reconnect my device to Suite and I have my wallet in view-only mode, Suite wants passphrase input for "every" action there is and not only once per session.

**Steps to reproduce:**
1. Connect device with passphrase
2. Enable view only for the wallet
3. Disconnect device
4. Reconnect device
5. Go to any account and select receive address
6. Suite asks for passphrase
7. Now go to any other receive address to show it
8. Suite asks for passphrase again

**Info:**
 - Suite version: web 24.11.0 (b7afbd05152736013d619dfd9dc9f10143fbd216)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.33

**Expected result:**
Suite wants passphrase input only once per session.

**Actual result:**
Suite wants passphrase input for "every" action there is and not only once per session.

### PR DESCRIPTION
**Pull request by martykan**
## Description

We update `sessionId` in saved device state in Suite from receiving a `DEVICE.CHANGED` event.
However this event wasn't being sent for calls with `keepSession: true`, such as during account discovery, this meant that if the passphrase was entered during those calls, it wasn't saved.

## Related Issue

Resolve #15226

### CODE REVIEW

**Comment by mroz22** [comment]
btw what about `skipFinalReload`? Does it affect this case too?

**Comment by martykan** [comment]
Cardano doesn't work so I assume there is an issue with `skipFinalReload`

**Comment by martykan** [comment]
Nevermind, it's a different issue with Cardano, due to the device state being current on subsequent calls

**Review by mroz22 — APPROVED** [review]
looks legit

**Pull request merged**
