### PR TITLE
Fix send form output labelling

### LINKED ISSUE #13862: Label of outgoing address cannot be saved
I am using Trezor Suite on MacOS sonoma 14.6.1. The Trezor Suite version is 24.7.3. Please check the bug. When I tried to give a label to the outgoing address when sending out coins, the label cannot be saved and there is no place to find the list of addresses. I enable the label function and save locally in Trezor Suite. Please fix the bug or give a solution.

**Describe the bug**

**Info:**

-   Remembered Wallet: yes/no
-   Suite Version: app/web, commit
-   Browser: name, version
-   Browser Installation Method: snap, flatpak, app store, windows store, downloaded installer, etc.
-   OS: name, version
-   Bridge: version
-   Firmware Version: model, version/commit

**How to reproduce**

1. Click on '....'
1. Scroll down to '....'
1. See error

**Expected behavior**

**Screenshots**

**Additional context**

### LINKED ISSUE #15953: Lables added to addresses in Send form are not added to the transaction history after sending
**Describe the bug**
When I add a label to a transaction, it is not shown in the tx history:
What I entered:
image
vs what is in tx history (don't mind the nonsense, its the name of the labeled account):
image

This all also applies for importing transactions with labels from CSV.

**Info:**
 - Suite version: desktop 24.12.1 (37b23d87f1678af93935deb93c9251a232bb2763)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.12.1 Chrome/128.0.6613.186 Electron/32.2.6 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.33

**Expected result:**
When I add label to transaction that I wanna broadcast, it also appears in the transaction history.

### PR DESCRIPTION
**Pull request by komret**
## Description

Cause: Dispatching `addAccountMetadata` after  `discardTransaction`. At that point, `precomposedForm` was `undefined` so there is no metadata to be saved.

Origin: The order was changed in c4e2fc549aef94d71c45d9b2627685fcd9c6391e, but it didn't break the feature because `precomposedForm` was replaced with persistent `draft` in the same PR. I did not notice this when going back from `draft` to `precomposedForm` in 8e681ea01f68c39e01ed9fe6e6f4d403e766e945.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/15953
Resolve https://github.com/trezor/trezor-suite/issues/13862 (This is weird though, the bug was introduced in 24.11, but the issue is older.)

### CODE REVIEW

**Comment by komret** [comment]
@PeKne, please check the mobile part.

@HajekOndrej, this would be worth an e2e test, but I want to merge this quickly, so let's do it separately. Can QA do it or should I try?

**Review by PeKne — APPROVED** [review]
Code looks good and its working as expected on mobile. I just tested it.

**Review by Lemonexe — APPROVED** [review]
LGTM, the bug makes sense as the `pushSendFormTransactionThunk` canceled the form before `applySendFormMetadataLabelsThunk` is called in suite desktop.

Tested suite-web with regtest and works fine :heavy_check_mark:

**Comment by Lemonexe** [comment]
:warning: non trivial conflicts - the thunk in `suite-native` was apparently unused and deleted in d035575255667c6f4ed0737cf040021d17795fdf

So idk if & how it should work in native, but approve for suite web/desktop still stands.

**Review by marekrjpolak — APPROVED** [review]
LGTM as well

**Comment by PeKne** [comment]
@Lemonexe the thunk is not needed anymore. So all the changes applied to it in this PR can be removed. Nonetheless the native app works as expected even without use of the removed thunk.

cc @komret

**Comment by komret** [comment]
Yes, I resolved the conflict by removing the thunk.

**Pull request merged**
