### PR TITLE
feat(message-system, coinjoin): Coinjoin temporary disabled due high mining fees

### PR DESCRIPTION
**Pull request by hynek-jina**
- Coinjoin temporary disabled due high mining fees
- Banner changed to: ```Coinjoin is temporarily unavailable due to technical issues```

### CODE REVIEW

**Review by tomasklim — APPROVED** [review]
LgtM

**Comment by matejkriz** [comment]
@hynek-jina only a nitpick, on any older version of Suite the banner will say “update suite to coinjoin” and only after the upgrade on latest version user will see “coinjoin disabled”

**Comment by hynek-jina** [comment]
You are right (again 🙂).. I assume there will be new version soon... so I will have a look on that. But we are ready to go live with this one for now.

**Pull request merged**
