### PR TITLE
Fix/native/splashscreen

### LINKED ISSUE #15523: Fix app icon and splashscreen after Expo update
Followup for https://github.com/trezor/trezor-suite/pull/15383, not in production.

App icon and splash screen is supposed to stay the same as it is on production, but the logo is somewhat smaller in app icon and splash screen is missing.

ICON

splashscreen ORIGINAL

splashscreen AFTER UPDATE

### PR DESCRIPTION
**Pull request by matejkriz**
## Description

Wrong app icon fixed by expo update.

Splashscreen fixed by recreating the image using [figma template](https://www.figma.com/community/file/1155362909441341285) referenced [here](https://docs.expo.dev/develop/user-interface/splash-screen-and-app-icon/#create-a-splash-screen) (but not using splash screen tamplate, but adaptive icon template 🙉 ). The docs about the changes is not very clear and expo is still working on making the documentation better.

Read more here https://expo.dev/changelog/2024/11-12-sdk-52#big-improvements-to-expo-splash-screen

I also switched from the now deprecated splash property to config plugin.

## Note for testing 

This can't be properly tested on debug builds or preview builds using development client, better to test it on "release" build or develop build.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/15523

## Screenshots:
ios

https://github.com/user-attachments/assets/20b7bbf5-c135-44b9-bbc4-243c53132016

android

https://github.com/user-attachments/assets/fbba7099-bca8-42fb-857b-b8065a4975d0

### CODE REVIEW

**Review by PeKne — APPROVED** [review]
Looks good 👍

**Comment by matejkriz** [comment]
Waiting for https://github.com/trezor/trezor-suite/pull/15557 to be merged because it also touches runtimeVersion so it has to be rebased.

**Review by Nodonisko — APPROVED** [review]
Briefly tested and it looks it may have solved that annoying double splash screen issue (first app icon as splash and then normal splash) not it's only one splash which is nice. Tested only in debug mode, hope it doesn't behave differently in prod mode and dev client.

**Comment by PeKne** [comment]
@matejkriz https://github.com/trezor/trezor-suite/pull/15557 was just merged ✅.

**Pull request merged**
