### PR TITLE
chore: clean unused messages

### PR DESCRIPTION
**Pull request by mroz22**
please check this @LukasRada these are invity messages and I remember some of them were "dynamic".

### CODE REVIEW

**Comment by LukasRada** [comment]
Yes, these messages are dynamic and should not be removed.

**Comment by mroz22** [comment]
thanks. so it should be done like this then 3e8460f76d170d31371b68d7de8b18896db3c5cb

**Comment by LukasRada** [comment]
I'm sorry, I didn't have the knowledge about `dynamic: true`. Now I know for the next time. Thank you.

**Comment by mroz22** [comment]
No big deal. This solution is far from ideal but it allows us to have a way how to detect unused messages.

**Review by jerechinsky — APPROVED** [review]

**Pull request merged**
