### PR TITLE
fix(suite): cleanup account names and descriptions

### LINKED ISSUE #4534: Naming accounts
Taproot PR https://github.com/trezor/trezor-suite/pull/4486 will require some followup. Moved from [notion](https://www.notion.so/satoshilabs/Taproot-product-copy-db17b96784a74ad4bc1cc2d47d9f1bc1).

Naming accounts

Add account dialog and Account details page should be reworked regarding account names.
there are 4 pieces of information we might want to present here:

- "human readable account type"
- bip standard which is implemented
- input script type being used
- address format encoding

account types:

- Taproot | `BIP86` | `P2TR` | `Bech32m`
- Segwit | `BIP84` | `P2WPKH` | `Bech32`⇒ this one is default for the time being
- Compat/Legacy Segwit | `BIP49` | `P2WPKH-nested-in-P2SH` | `Base58`
- Legacy | `BIP44` | `P2PKH` | `Base58`

### PR DESCRIPTION
**Pull request by prusnak**
Implements https://github.com/trezor/trezor-suite/issues/4534

Before:

After:

suite-taproot-account

### CODE REVIEW

**Comment by prusnak** [comment]
The test `metadata/account-metadata.test.ts` fails on `AssertionError: expected [ Array(25) ] to have a length of 27 but got 25`, but it seems to me this is failing on `develop` as well. Can you please @mroz22 have a look?

**Comment by mroz22** [comment]
Sure. it should pass now. I will rebase this and resolve conflicts if you don't mind.

**Comment by prusnak** [comment]
I went ahead with the rebase by myself.

**Comment by prusnak** [comment]
CI is green now, but please review all changes whether they make sense.

**Review by mroz22 — APPROVED** [review]
lookd good imho. files in `translations` folder will get overwritten once we sync them with crowdin but it does not matter. Just heads up to @alex-jerechinsky that he is going to see bunch of changes in crowding once this is merged and synced.

**Comment by prusnak** [comment]
> in crowding once this is merged and synced.

Can we also sync the other direction (from github to crowdin)? I think it would be beneficial to do that once this PR is merged, so we don't lose any already existing translations.

**Comment by mroz22** [comment]
>  Can we also sync the other direction (from github to crowdin)? I think it would be beneficial to do that once this PR is merged, so we don't lose any already existing translations.

We don't  have any tooling to do this at the moment. :thinking: 

Right now it works like this:
1. changes are done to `messages.ts` 
2. changes are uploaded to Crowdin
3. in Crowdin, all translations whose source strings have changes are set to "not approved"
4. translators or alex does necessary fixes, approves them
5. translations are downloaded back to the project and commited. 

I will discuss this case tomorrow with @alex-jerechinsky maybe we will find a way.

**Comment by prusnak** [comment]
It does not have to be automated. It is good to know there is a way, albeit manual one (there are not a lot of affected strings and languages in this PR).

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 21.12.0 (312a355e355722a2bb67e43133434b4e2abebbfc)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:94.0) Gecko/20100101 Firefox/94.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.10.4 regular

**Pull request merged**
