### PR TITLE
Message system config for FW header change and fixed welcome layout

### PR DESCRIPTION
**Pull request by matejkriz**
## Description

Updating the T2B1 FW from 2.6.2 to 2.6.3 will wipe any previously stored seed.

<details>
  <summary>3 new messages:</summary>
  
1. **Suite ≤ 23.10 w/ and w/o TS3 2.6.2 FW ~ pre November 15** 
yellow, dismissable
- When the next Trezor device update rolls out, make sure you've got your recovery seed ready. You’ll need it to regain access to your coins.
- CS: Až se objeví další aktualizace zařízení Trezor, nezapomeňte si připravit sadu pro obnovení. Budete ho potřebovat k obnovení přístupu k mincím.
- ES: Cuando salga la próxima actualización del dispositivo Trezor, asegúrate de tener preparada tu semilla de recuperación. La necesitarás para recuperar el acceso a tus monedas.
- JA: 次のTrezorデバイスのアップデートがリリースされたら、リカバリーシードを準備しておいてください。コインへのアクセスを回復するために必要です。
- IT: Quando uscirà il prossimo aggiornamento del dispositivo Trezor, assicuratevi di avere pronto il seme di ripristino. Ne avrete bisogno per riavere accesso alle vostre monete.
- HU: Amikor a következő Trezor készülékfrissítés megjelenik, győződjön meg róla, hogy készen áll a helyreállítási mag. Szükséged lesz rá, hogy újra hozzáférj az érméidhez.
- RU: Когда выйдет следующее обновление устройства Trezor, убедитесь, что у вас наготове семя восстановления. Она понадобится для восстановления доступа к монетам.

2. **Suite ≤ 23.10 w/ and w/o TS3 2.6.2 FW ~ after November 15**
red, non-dismissable
- Essential update of Trezor Suite is required for your new Trezor Safe 3.
- CS: Pro nový Trezor Safe 3 je nutná základní aktualizace sady Trezor Suite.
- ES: Se requiere una actualización esencial de Trezor Suite para su nuevo Trezor Safe 3.
- JA: 新しいTrezor Safe 3を使用するには、Trezor Suiteの必須アップデートが必要です。
- IT: Per il nuovo Trezor Safe 3 è necessario un aggiornamento essenziale di Trezor Suite.
- HU: A Trezor Suite alapvető frissítése szükséges az új Trezor Safe 3 készülékhez.
- RU: Для нового Trezor Safe 3 требуется обновление Trezor Suite.

3. **Suite ≥ 23.11 w/ TS3 2.6.2 FW**
red, non-dismissable
-  An update is available for your Trezor device. Make sure you’ve got your recovery seed ready as you’ll need it to regain access to your coins.
- CS: Pro zařízení Trezor je k dispozici aktualizace. Ujistěte se, že máte připravený recovery seed, protože jej budete potřebovat k obnovení přístupu k mincím.
- ES: Hay una actualización disponible para tu dispositivo Trezor. Asegúrate de tener preparada tu semilla de recuperación, ya que la necesitarás para recuperar el acceso a tus monedas.
- JA: お使いのTrezorデバイスにアップデートが提供されています。コインへのアクセスを回復するにはリカバリーのシードが必要です。
- IT: È disponibile un aggiornamento per il vostro dispositivo Trezor. Assicuratevi di avere pronto il seme di ripristino, che vi servirà per riavere accesso alle monete.
- HU: Frissítés érhető el a Trezor készülékéhez. Győződjön meg róla, hogy készenlétben tartja a helyreállítási magot, mivel szüksége lesz rá, hogy újra hozzáférjen az érméihez.
- RU: Для устройства Trezor доступно обновление. Убедитесь, что у вас наготове семена восстановления, поскольку они понадобятся для восстановления доступа к монетам.
</details>

 \+ Fix vertical alignment on welcome screen to work with banner.
 I found out during testing, that security check and other welcome screen components can't scroll to the very bottom on smaller screen heights when there is banner shown on top. I removed top 20vh top-margin completely because it had to have lot of workarounds and align everything on center instead.

## Related Issue

Notion description
https://www.notion.so/satoshilabs/Copy-TS3-FW-wiping-update-d1937c3b0f39476286f043065727bdf0?pvs=4

message system requests overview:
https://www.notion.so/satoshilabs/Secure-message-system-5ade512cbd38481f9d5f65f03dbfd9a8?pvs=4

## Screenshots:
1. Suite ≤ 23.10 w/ and w/o TS3 2.6.2 FW ~ pre November 15:
image
image

2. Suite ≤ 23.10 w/ and w/o TS3 2.6.2 FW ~ after November 15:
image

3. Suite ≥ 23.11 w/ TS3 2.6.2 FW:
image

### CODE REVIEW

**Comment by matejkriz** [comment]
@komret please review https://github.com/trezor/trezor-suite/pull/9746/commits/dcfc1f9bfd493ac7604884692abe3b21c1d5827a in the first place.

@tomasklim please check the changes in `config.v1.json`. I used `duration` condition for a first time to have there both variants prepared. If we didn't release Suite exactly on time, we could do another message-system release before the 15th of November.

**Comment by komret** [comment]
Ad 2: So users will only see the blue banner for FW update after Suite is updated to 23.11?

**Comment by matejkriz** [comment]
> Ad 2: So users will only see the blue banner for FW update after Suite is updated to 23.11?

No blue banner for TS3. Happy path is no FW on the device and so regular onboarding. Unhappy path is FW 2.6.2 and red banner that you will need recovery seed during upgrade. And device itself warn you about that too during the FW update.

**Comment by matejkriz** [comment]
During regular FW update there is this screen in Suite:
image
In case of T2B1 2.6.2 -> 2.6.3 it will be for sure, but user is also warned about that on device screen an has to confirm FW header change.

**Review by komret — APPROVED** [review]
The layout issue could have been solved by moving `overflow:y: auto` from `Content` to `Body` in `WelcomeLayout`, but this is much cleaner 👍 .

As for the message system, in an edge case where user has FW, but the device is not yet initialized, they can click on the CTA button during onboarding and it takes them to settings. Otherwise it is not possible to get there from onboarding. So, if they create a wallet and click the CTA button before they create backup, they skip backup and PIN (but can still set them up later so I guess it's fine).

The fixup is linked to a wrong commit, but nevermind.

**Comment by matejkriz** [comment]
> The layout issue could have been solved by moving `overflow:y: auto` from `Content` to `Body` in `WelcomeLayout`, but this is much cleaner 👍 .

I think I've tried that but it didn't solve all the issue in all states, but not sure now. If you like the current solution, I'm not going to investigate any further.

> 
> As for the message system, in an edge case where user has FW, but the device is not yet initialized, they can click on the CTA button during onboarding and it takes them to settings. Otherwise it is not possible to get there from onboarding. So, if they create a wallet and click the CTA button before they create backup, they skip backup and PIN (but can still set them up later so I guess it's fine).

Sounds too much too marginal to me. If the device is not initialized and user update FW in settings, how they can create the wallet? I think that only in onboarding?

> 
> The fixup is linked to a wrong commit, but nevermind.

Thanks for noticing, will fix.

**Comment by komret** [comment]
> Sounds too much too marginal to me. If the device is not initialized and user update FW in settings, how they can create the wallet? I think that only in onboarding?

Yes, let's disregard it.

**Comment by matejkriz** [comment]
@trezor/qa message-system config released on develop, please test it out.

1. and 2. can be tested on https://suite.corp.sldev.cz/suite-web/release/23.10/web/ (for 2. you need to change your local computer date to after 15th November)

3. can be tested on develop

**Comment by bosomt** [comment]
**QA OK**

**release branch**

- no banner for TT connected

- when model Safe 3 connected: 

_26.11.2023:_
Screenshot 2023-11-26 at 12 53 51


_26.10.2023:_
Screenshot 2023-10-26 at 12 53 08


**Info:**
 - Suite version: web 23.10.1 (6c8d061f7305947b0270a2560e4cc65d1f7ded27)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/118.0
 - OS: MacIntel
 - Screen: 1824x1140
 - Device: Trezor T2B1 2.6.2 bitcoin-only (revision 6e5967af25de87bebd331d697e6ef940e64286ef)
 - Transport: BridgeTransport 2.0.33

**develop**

- no banner for TT connected

- when model Safe 3 connected: 

image


**Info:**
 - Suite version: web 23.11.0 (ef8c862c77f728f26a28b41bf0ec6b28508bd826)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/118.0
 - OS: MacIntel
 - Screen: 1824x1140
 - Device: Trezor T2B1 2.6.2 bitcoin-only (revision 6e5967af25de87bebd331d697e6ef940e64286ef)
 - Transport: BridgeTransport 2.0.33

**Pull request merged**
