### PR TITLE
chore(components): make Switch checked state to be handled by its parent

### LINKED ISSUE #2149: PIN protection and passphrase says enabled even when you cancel enable dialogue
**Info:**
 - OS: nixos
 - Browser: , Chromium 83.0.4103.116
 - Wallet Version: app/web, commit 582ebd2f9c1b733058df3e6adf70f842c7ef394d
 - Firmware Version: 1.9.1 , revision 0xc6b2580cd245ee924507f45e9675f857a3d78768,
 
**Describe the bug**

When you enable PIN protection via suite but you cancel it in device dialogue, suite says enabled.
Same behavior in web and app suite
EDIT: same behavior with passphrase enable/disable switch

**Steps to reproduce:**
1. enable PIN protection
2. press cancel on device
3. see that suite says PIN protection is enabled

**Expected result:**
PIN protection is still grey
**Actual result:**
PIN protection switch is green

**Screenshots:**
https://www.youtube.com/watch?v=INrG8T1ktKY&feature=youtu.be

### PR DESCRIPTION
**Pull request by tomasklim**
closes #2149 

It consists of:

- [x] fix of passphrase and pin switch [d198120](https://github.com/trezor/trezor-suite/pull/3890/commits/d198120) **OLD**

The switch component handled its checked state on its own and when the user cancelled enabling of pin/passphrase, it got into the wrong state. That happened because the parent's component state was not changed.

The switch component's checked state is now handled by its parent to display the correct state. It is now unified with RadioButton, Checkbox and Select components, which are also handled by their parents.

- [x] refactor of storybook form elements [31eed6a2](https://github.com/trezor/trezor-suite/pull/3890/commits/31eed6a2) **NEW**

Refactor of stories of form elements was required to solve a problem with controlled components. When user changed state of the component by clicking on it, the state was not reflected in knobs and vice versa. Another issue was, that if a user changed e.g. state of Switch and then disabled it, the state was changed to default, so a user could not see how the switch in `switched` state looks like in disabled state.

- [x] install new storybook libraries which allow solving controlled components problems  [9035f737](https://github.com/trezor/trezor-suite/pull/3890/commits/9035f737) **NEW**

`@storybook/addon-knobs` is deprecated and it is not possible to easily fix a problem with controlled components. By replacing it with `@storybook/addon-controls` it is possible to solve this issue. Both libraries will now be available in the project until everything is migrated. #3907

- [x] solve problems with controlled form components [4393a68a](https://github.com/trezor/trezor-suite/pull/3890/commits/4393a68a) **NEW**

Migration of form element stories to `@storybook/addon-controls`

### CODE REVIEW

**Review by goodhoko — APPROVED** [review]
LGTM

**Review by szymonlesisz — APPROVED** [review]

**Comment by tomasklim** [comment]
Ready to be reviewed again.

@szymonlesisz @goodhoko commit [d198120](https://github.com/trezor/trezor-suite/pull/3890/commits/d19812029d5564e213c814297ac29e0d7c4030e9) remains the same. Other commits addresses problems with Storybook.

**Review by goodhoko — APPROVED** [review]
Quickly went through the three new commits and found nothing suspicious. Still LGTM.

Also, the description of this PR is really nice 👍

**Review by szymonlesisz — APPROVED** [review]
bjutiful :)

**Pull request merged**
