### PR TITLE
@solana/web3.js v2 update

### LINKED ISSUE #12628: Can't close Trezor Suite with Tor On and Solana account active
**Describe the bug**
If Solana account is activated and Tor is on, I can't close Trezor Suite.

Happens both on 24.5.2.and 24.5.3. and only on Arm Mac
Not reproducible on Linux and Windows yet.

**Steps to reproduce:**
1. Activate Solana account
2. Turn on Tor
3. Close the app
4. Observe app is not closing and in Activity Monitor it's not responding

**Info:**
 - Suite version: desktop 24.5.3 (0ff3e0bd75d90719b7b36a60b3eab1c2bd3d3491)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.5.3 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33

**Expected result:**
App closes

**Screenshots:**
Screenshot 2024-05-29 at 08 43 41

**Note(s):**
related to https://github.com/trezor/trezor-suite/issues/12626 ?

### PR DESCRIPTION
**Pull request by tomasklim**
## Description

- solana sdk updated to v2 in #15535
- this PR contains and fixes code done in 🔝 

Resolve #12628

## Screenshots:

Screenshot 2024-11-29 at 9 04 41
Screenshot 2024-11-29 at 9 05 32

### CODE REVIEW

**Comment by enjojoy** [comment]
I tested desktop app + tor issue, it's not present 👍🏻

**Comment by tomasklim** [comment]
@SocketSecurity ignore npm/@solana/rpc-transport-http@2.0.0
@SocketSecurity ignore npm/@solana-program/compute-budget@0.6.1

**Comment by enjojoy** [comment]
> I tested desktop app + tor issue, it's not present 👍🏻

Tested again, it closed with no problems @tomasklim

**Review by martykan — APPROVED** [review]
🚀

**Review by vytick — APPROVED** [review]
Thanks for the help @steveluscher 🙏

**Comment by bosomt** [comment]
**QA OK**

Info:

Suite version: desktop 24.12.0 (https://github.com/trezor/trezor-suite/commit/ba5174eb1c7fc19b376c089ec56e843bbbf8d437)
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.12.0 Chrome/130.0.6723.91 Electron/33.1.0 Safari/537.36
OS: MacIntel
Screen: 1512x982
Device: Trezor T3T1 2.8.6 regular (revision 688bddc887b8bb660640cc6e40a99036f2e87f1f)
Transport: BridgeTransport 2.0.33

**Pull request merged**
