### PR TITLE
fix(win): start signing DLL binaries to satisfy AppLocker policy

### PR DESCRIPTION
**Pull request by matejkriz**
https://www.electron.build/configuration/win#WindowsConfiguration-signDlls

### CODE REVIEW

**Review by vdovhanych — APPROVED** [review]

**Comment by matejkriz** [comment]
for QA: please test windows app and autoupdate on win carefully

**Comment by prusnak** [comment]
Just a note: we have to be careful and check whether this change will not increase the probability of failed signing.
This https://github.com/electron-userland/electron-builder/issues/3101#issuecomment-404212384 indicates the change might trigger a rate-limiting on a signing server and there is no fallback mechanism (wait on failure and try again) implemented yet. The good thing is that such failure is hopefully immediately visible in the CI.

**Comment by vdovhanych** [comment]
We should do a test signing then, I will do it later today with latest develop.

**Comment by omer-phanatic** [comment]
Hi,
 I was directed to this conversation after opening a ticket with your support team.
 I can provide you with the unsigned DLL paths found in our logs. Hope it helps further progress on this issue.
 ( I have replaced the username with a wildcard. )

 %OSDRIVE%\USERS\*APPDATA\LOCAL\PROGRAMS\TREZOR SUITE\LIBGLESV2.DLL

 %OSDRIVE%\USERS\*\APPDATA\LOCAL\PROGRAMS\TREZOR SUITE\LIBEGL.DLL

 %OSDRIVE%\USERS\*\APPDATA\LOCAL\PROGRAMS\TREZOR SUITE\FFMPEG.DLL

**Comment by vdovhanych** [comment]
@matejkriz All dlls should be signed in the latest staging build.

**Comment by bosomt** [comment]
**QA OK**

checked all .dll files in Trezor Suite directory and they are all signed 🎉 
@omer-phanatic please wait next release in upcoming days

**Comment by omer-phanatic** [comment]
Thanks a lot, guys! 
looking forward to the next release:)

**Comment by matejkriz** [comment]
reopenning: https://github.com/trezor/trezor-suite/issues/4900

those two files looks still unsigned:
`swiftshader/libEGL.dll`
`swiftshader/libGLESv2.dll`

**Pull request merged**
