### PR TITLE
fix(suite): show stop on hover when there is no deadline yet in CJ status wheel

### PR DESCRIPTION
**Pull request by dahaca**
## Description

* allow to cancel CJ when there is no deadline yet

### CODE REVIEW

**Comment by szymonlesisz** [comment]
i think PR name and commit message is misleading
what you did here is that you changed component displayed in the button from loader (`StyledLoader` circles) to stop icon, when button is hovered right?

**Comment by szymonlesisz** [comment]
btw, while i was testing it i noticed that conditions in `ProgressWheel` (parent component) `handleWheelClick` are not working properly

I have intentionally disabled/commented out the code which is responsible for opening critical-phase modal (page was not blocked while in critical phase) yet i was able to stop session in critical phase (and i've break the round)

I guess this needs to be fixed as prerequisite for [Remove blocking modal for signing phase of coinjoin](https://github.com/trezor/trezor-suite/issues/8374)


EDIT: I will try to solve it in separate PR

EDIT 2:[ fixed here](https://github.com/trezor/trezor-suite/pull/9021/commits/3e4ea4992ece27ddad6a22a78476846695e4c1ee) but i need some UI/texts for the case when session is auto stopped

**Comment by dahaca** [comment]
@szymonlesisz you are right, the title is slightly misleading, since it's just a cosmetic change to better reflect what is possible, based on [this](https://satoshilabs.slack.com/archives/CLAR68GBV/p1690181947689519) slack thread.

**Review by szymonlesisz — APPROVED** [review]
you didnt convicend me regarding the commit message :) but i tested it and it works

**Comment by dahaca** [comment]
@szymonlesisz I can change the commit message!

**Comment by szymonlesisz** [comment]
it's up to you :+1:  i already approve it

**Pull request merged**
