### PR TITLE
fix(suite-native): account balance includes XRP reserve

### LINKED ISSUE #13900: XRP balance mismatch
Amount on Dashboard and Account detail shown including 10 XRP reserve, My assets, Receive and Select account shown without.

It has to be unified - the amount should always include those locked 10 XRP.

### PR DESCRIPTION
**Pull request by PeKne**
XRP reserve is always included in the account balance.

## Related Issue

Resolve #13900

## Screenshots:

https://github.com/user-attachments/assets/ef40ea28-55ae-440b-b22a-0ca8bb0ba643

### CODE REVIEW

**Comment by Nodonisko** [comment]
Woudn't this break something else? I think there was some concers that `balance` does or doesn't include non confirmed transactions etc. (IDK it's a mess :D)

**Comment by PeKne** [comment]
@Nodonisko it should not. Desktop is using `balance` everywhere as well.

**Comment by PeKne** [comment]
I'm missing some go back button in the cancelled firmware update state. If the user cancels the flow on device, only way to leave it is by restarting the app.

https://github.com/user-attachments/assets/0c5b16cd-87ce-4b88-a728-066cfda6a8dd

**Comment by Nodonisko** [comment]
@PeKne I think you wanted to add this comment to FW upgrade PR :D Anyway this is bug, it should return automatically when flow is cancelled on device.

**Review by Nodonisko — APPROVED** [review]

**Pull request merged**
