### PR TITLE
fix(blockchain-link-utils): fee display in Solana self token txs

### LINKED ISSUE #10920: Tx sent to myself shows that I got fee back in tx modal detail
**Describe the bug**
Tx sent to myself shows that I got fee back in tx modal detail

**Info:**

-   Suite Version: 24.2.0

**How to reproduce**

1. Sent token tx to yourself

**Expected behavior**
I says the truth!

**Screenshots**
Screenshot 2024-01-30 at 14 54 20
Screenshot 2024-01-30 at 14 54 26
Screenshot 2024-01-30 at 14 54 49

### PR DESCRIPTION
**Pull request by memoriesadrift**
The native effects and transaction ammount is calculated to account for multi asset transfers. If the transfer amount to self is equal to the fee (i.e. only the fee was paid, no SOL was transfered) we set it to 0.

I suggest further investigation into why the modal displays a different value than the tx history item, since the tx history item correctly displayed -fee whereas the modal displays +fee. 
Since I perceive that the fee display as a sent value is a bug anyway I didn't address this.

## Related Issue

Resolves #10920

## Screenshots:
image
image

### CODE REVIEW

**Comment by Nodonisko** [comment]
cc @vytick

**Comment by vytick** [comment]
Might the `.abs()` be the reason why the fee is shown > 0?

https://github.com/trezor/trezor-suite/blob/a86214f104109df3a52bad85b0b3c75d74809d0a/packages/blockchain-link-utils/src/solana.ts#L412

**Comment by PeterBenc** [comment]
Update


Tx history with Token and Sol self tx
image
Token tx details
image
image
Sol tx details
image
image

**Review by tomasklim — APPROVED** [review]

**Comment by tomasklim** [comment]
Closing in favor of https://github.com/trezor/trezor-suite/pull/14808

**Pull request closed without merging**
