### PR TITLE
fix(suite-desktop): unpack node binaries to fix mac signing

### PR DESCRIPTION
**Pull request by matejkriz**
## Description

Native dependencies can't be signed for mac when they are bundled in asar archive format.

## Related Issue

Resolve [](https://satoshilabs.slack.com/archives/C031LD98L9K/p1688539417507729)

## Screenshots:

fixing this error:

image (10)

### CODE REVIEW

**Review by marekrjpolak — APPROVED** [review]
I acknowledge its existence.

**Comment by matejkriz** [comment]
It fix the mac signing, but breaks win build 🙉 https://gitlab.com/satoshilabs/trezor/trezor-suite/-/jobs/4605482050

Issue in electron-builder https://github.com/electron-userland/electron-builder/issues/7652

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 23.7.1 (4a4127f0beab65e4dfadb2a68385761abee44396)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.7.1 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.6.1 Universal (revision c3f6e8f19fd647c73b414322e287ba23cf8a0c7c)
 - Transport: BridgeTransport 2.0.33

**Comment by STew790** [comment]
**QA OK**
OK for all other platforms as well (Windows, Mac Intel, Linux). Approving

**Pull request merged**
