### PR TITLE
Fix/coin control layout

### LINKED ISSUE #16026: Send - Coin control - inputs values not properly aligned
**Describe the bug**
Send - Coin control - inputs values not properly aligned 

**Steps to reproduce:**
1. Load BTC like accounts with multiple inputs
2. Enter send dialogue and open coin control section
3. Observe coin value

**Info:**
 - Suite version: desktop 24.12.2 (63a31ccba4fd23c07d1e6cfd1944e1432e327c04)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.12.2 Chrome/128.0.6613.186 Electron/32.2.6 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.3 regular (revision 7f373ae71eca855dd41b4a0fdcc7cadaa13a8281)
 - Transport: BridgeTransport 3.0.0-bundled.24.12.2

**Screenshots:**
image

### PR DESCRIPTION
**Pull request by komret**
## Description

- Fixes broken selector (checkbox should be in hovered state when the section is hovered)
- Fixes horizontal alignment

A `className` prop should always be attached to the topmost element, otherwise layout-related styles are ignored. This bug originates from https://github.com/trezor/trezor-suite/pull/15457/commits/c27f9895fefcb137228d70476441d1099ab18aec. Discussion [here](https://satoshilabs.slack.com/archives/C07NNMUBJFN/p1734519767134879).

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/16026

## Screenshots:
before:

https://github.com/user-attachments/assets/541609fd-21e3-4cf2-a2d7-763bc1e1b745

after:

https://github.com/user-attachments/assets/0d7b18be-9c68-4238-b0b3-93c48cccf9e6

### CODE REVIEW

**Review by seibei-iguchi — APPROVED** [review]

**Review by enjojoy — APPROVED** [review]
LGTM but looks like linting is failing

**Comment by komret** [comment]
Fixed linting error in 5a813bcb0efff8ee0ae35620119fe012d09d0f84.

**Pull request merged**
