### PR TITLE
fix: modify defaultMessage in messages.ts

### PR DESCRIPTION
**Pull request by fujicoin**
I modified message.ts after extracting the difference between the latest en.json and message.ts in English.

[diff_newmaster2master2.txt](https://github.com/trezor/trezor-suite/files/7893947/diff_newmaster2master2.txt)

I created a new master.json from the modified message.ts using the attachment tool and confirmed that it exactly matches the one in #4768. This modification PR is perfect.

[messages.ts2master.json.zip](https://github.com/trezor/trezor-suite/files/7893932/messages.ts2master.json.zip)

This fix eliminates the need for en.json. Delete en.json.
The existence of en.json is annoying to the supporters who help with the translation at crowdin.com.
I think it's a good idea to always add or modify the original text in messages.ts, then convert it to master.json and upload it to crowdin.com.

### CODE REVIEW

**Comment by prusnak** [comment]
Why do some of the strings include an extra `\n` while others do not?

**Comment by tomasklim** [comment]
> Why do some of the strings include an extra `\n` while others do not?

Probably someone hit `Enter` instead of `Save` button. Those `\n` are not reflected and can be deleted @alex-jerechinsky 
Screenshot 2022-01-19 at 10 12 47

**Comment by fujicoin** [comment]
Removed unnecessary `\n` at the end of the line.
Attach the master.json created by messages2master.json.py from this file.
Upload this file to #4768  as well. 

[master.json.zip](https://github.com/trezor/trezor-suite/files/7900396/master.json.zip)

If you don't upload this master.json to crowdin.com, the correct translation file will not be downloaded.
Note: The current crowdin English source file contains incorrect keys and is missing new or correct keys.
---------------------------------------------------------------------------------------------------------

**Comment by fujicoin** [comment]
This fix was captured in the next commits and will be closed.

https://github.com/trezor/trezor-suite/commit/3b465f43e0756c34cafaf11ab75a88e51c4193c9
https://github.com/trezor/trezor-suite/commit/435992e8f39c86a379b8719df515f0b03019d601

**Comment by fujicoin** [comment]
This fix was captured in the next commits and will be closed.

https://github.com/trezor/trezor-suite/commit/435992e8f39c86a379b8719df515f0b03019d601

**Comment by jerechinsky** [comment]
I have removed all the unnecessary `\n` from `master.json` in Crowdin. The changes have since been reflected to `messages.ts` by @mroz22's backport in 3b465f4 and 435992e. Thank you, @fujicoin.

**Pull request closed without merging**
