### PR TITLE
connect-explorer frontpage revamp kickoff

### PR DESCRIPTION
**Pull request by mroz22**
connect-explorer was initially just some internal dev tool. later, we decided to put it on connect.trezor.io/9 frontpage because we thought it might be valuable for 3rd party devs too. but it doesn't look well and content wise it could present more useful information. 

lets collect whatever low-hanging fruit we may see here @Hannsek 

WIP screenshot
image

For latest results check https://suite.corp.sldev.cz/connect/feat/connect-explorer-frontpage-revamp/#/

Also note that all of the results (changes to md files) will not take effect until this is merged to develop. Maybe we could reference permalinks based on branches where this was built? Might this also solve versioning problem?

### CODE REVIEW

**Comment by mroz22** [comment]
I guess that the best way to go for now would be rendering this md file for index
https://github.com/trezor/trezor-suite/blob/develop/docs/packages/connect/index.md

**Comment by Hannsek** [comment]
image
What is the ES6 under "Events" tab?

**Comment by Hannsek** [comment]
Otherwise lgtm.

**Comment by mroz22** [comment]
> image What is the ES6 under "Events" tab?

https://www.w3schools.com/js/js_es6.asp

**Comment by Hannsek** [comment]
Thanks, it just looks like text out of nowhere.

**Review by Hannsek — APPROVED** [review]

**Pull request merged**
