### PR TITLE
feat: enable and use p2wpkh aka bech32 as default for litecoin aka ltc. closes #3399

### LINKED ISSUE #3399: Litecoin - support for Bech32 address (native segwit)
**Is your feature request related to a problem? Please describe.**
Bech32 (native segwit) is supported for bitcoin in trezor-suite (thanks for this) but litecoin is sadly not yet supported, so it's not possible to use accounts starting with ltc prefix without using third party software.

**Describe the solution you'd like**
Support for Bech32 for litecoin in trezor-suite

**Describe alternatives you've considered**
Third party sw (electrum-ltc), but I really like trezor suite much more

### PR DESCRIPTION
**Pull request by mcudev**
This addresses #3399

In summary, this enables P2WPKH aka bech32, and makes it the default account type, for Litecoin / LTC.

A good mnemonic for testing this, with an empty passphrase, is: `all all all all all all all all all all all all`
That mnemonic has transactions for legacy and segwit accounts already.

Some of the changes just remove bitcoin/BTC verbiage as P2WPKH/bech32 is not unique to BTC.
I also fixed the tooltip about converting LTC address formats so that it only displays for BIP49 p2shsegwit aka segwit accounts (not legacy or bech32 account types).

In the local dev web app and local desktop app, I verified:
- that the cryptocurrency drop down in the new account dialog only shows Litecoin once
- the "Find my Litecoin accounts" button in the new account dialog (it enables the coin and searches for existing accounts)
- that the account type drop down in the new account dialog shows 3 options for Litecoin now
- that the Bech32 banner message for BTC and LTC shows as desired (using the slightly more generically message)
- that the account details all show the correct account type
- that the correct address formats are displayed for the account type
- that the addresses generated from the different account types match the output from `trezorctl`

### CODE REVIEW

**Review by keraf — APPROVED** [review]
Thanks for the contribution, looks good to me! I'll wait for @szymonlesisz's review before merging as he has better insight than me in this part of the project.

**Comment by mcudev** [comment]
thanks! i'm just working on a few additional changes that i'll push up in just a bit related to bech32 validation.

**Comment by mcudev** [comment]
i just force pushed a new single commit with a few more small updates.

i changed `isBech32AddressUppercase` to handle litecoin and litecoin testnet, updated the text in `packages/suite/src/support/messages.ts`, and added a test fixture to `packages/suite/src/utils/wallet/__fixtures__/accountUtils.ts`.

i wasn't sure exactly how to run the test fixture, but i figured that the CI would probably run it after i pushed it.

**Comment by szymonlesisz** [comment]
Hi @mcudev, great job, thanks!
i've cherry picked your commit, fixed eslint error in `FreshAddress` component and add a DB migration for stored accounts.

now it waits for QA testing results

closing in favor of https://github.com/trezor/trezor-suite/pull/3586

**Comment by mcudev** [comment]
@szymonlesisz nice! thanks for the migration code too! i'm testing that right now. that makes sense from a user perspective.i'll update the other PR when i'm done.

**Pull request closed without merging**
