### PR TITLE
fix(suite): Fixed deprecated KeyboardEvent.keyCode

### PR DESCRIPTION
**Pull request by TaseerAhmad**
I have fixed the deprecated keyCode. 
**Issue:** [Issue #3839](https://github.com/trezor/trezor-suite/issues/3839)

I found 7 occurrences instead of 8 as mentioned in the issue.

**Search method:** `https://github.com/trezor/trezor-suite/search?q=SEARCH_TERM`

**Deprecated:** `e.keyCode`
**Fix:** `e.key`

`event.which` which gives an event code is also deprecated. To fix it, simply replace it with the value of `event.code`. Example: 

**Deprecated:** `if (event.keyCode === 32)`

**Fix:** `if (event.key === 'Space')`

### CODE REVIEW

**Comment by tsusanka** [comment]
Thanks for your contribution! Please squash this into one commit.

**Comment by TaseerAhmad** [comment]
> Thanks for your contribution! Please squash this into one commit.

Thank you, I will squash them ASAP.

**Comment by TaseerAhmad** [comment]
> Thanks for your contribution! Please squash this into one commit.

I am having this error: `error: failed to push some refs to remote`. I am all out of ideas to fix it, how can I rectify it. Please let me know.

**Comment by tsusanka** [comment]
After the squash you need to force push `git push origin HEAD --force`.

**Comment by tomasklim** [comment]
@TaseerAhmad 
Hello, thank you for your contribution. Unfortunately, it looks like that by squashing, you somehow deleted all the files in the project.  

Please check your PR again 😊

**Comment by TaseerAhmad** [comment]
> @TaseerAhmad
> Hello, thank you for your contribution. Unfortunately, it looks like that by squashing, you somehow deleted all the files in the project.
> 
> Please check your PR again blush

Sorry about it, I will do it all again. Was having a hard time solving the errors.

**Pull request closed without merging**
