### PR TITLE
Feat/coinjoin testing logs

### PR DESCRIPTION
**Pull request by matejkriz**
## Description

This enables to change logger config while app is already running, and use this possibility for CoinJoin so we don't need the user to run it from terminal with the --log-write parameter.

Logging to file started when user activate the **Debug menu** and it returns the original logger config when you deactivate Debug menu. If you run the app with `--log-write` param, nothing changed.

The default log folder is changed to /logs subfolder of Suite data directory and default file name has now human readable datetime (e.g. `trezor-suite-log-2023-01-03T09-09-05.txt`).

There is a new button in CoinJoin Account tab (see the screenshot below) to open logs folder in the desktop's default manner so user can easily locate the file to be sent to support. Every new app run add new file (with timestamp in name) so user can send all logs or select the one from problematic run.

Scroll anchor is prepared for that button, so we can navigate there from the context message.

Context message is not added yet, it needs https://github.com/trezor/trezor-suite/pull/7189 to be merged.

Would be nice to put there some better explanation instead of just "Open folder with log files.". Or the explanation could come with a request for the logs...

336f94077451b3ee7e541f952fd04cff27eb28ef removes CoinJoin logs because they are no more useful for debugging (Connect calls and network communication is needed, so desktop logs is the place where to find everything) and it wasn't meant for production - user will [see CoinJoin state messages elsewhere](https://github.com/trezor/trezor-suite/issues/6923). 

## Related Issue

Resolve the collection of the logs: https://github.com/trezor/trezor-suite/issues/7125 
Context banner will be added later, it's blocked by https://github.com/trezor/trezor-suite/pull/7189 .

## Screenshots:
image

### CODE REVIEW

**Comment by matejkriz** [comment]
It also adds the link to data folder to debug menu where before there was only a path displayed:
image

**Review by szymonlesisz — COMMENTED** [review]
regarding removing logs from UI, consider reverting [this commit](https://github.com/trezor/trezor-suite/commit/3bd0414a7befd37b8bd0afcfd12c843836839358) completely since data in reducer are not used anymore and all important logs are in the file now

**Comment by matejkriz** [comment]
> regarding removing logs from UI, consider reverting [this commit](https://github.com/trezor/trezor-suite/commit/3bd0414a7befd37b8bd0afcfd12c843836839358) completely since data in reducer are not used anymore and all important logs are in the file now

👍 done

**Comment by szymonlesisz** [comment]
lol :)
https://github.com/trezor/trezor-suite/pull/7280

**Review by szymonlesisz — APPROVED** [review]
working like a charm

**Pull request merged**
