### PR TITLE
fix(suite): Fix backup modal

### PR DESCRIPTION
**Pull request by jvaclavik**
## Description

not great not terrible 🫣

## Related Issue

Resolve 

## Screenshots:
image

### CODE REVIEW

**Comment by MiroslavProchazka** [comment]
Resolves [#12317](https://github.com/trezor/trezor-suite/issues/12317)

**Review by komret — APPROVED** [review]
It's fine, but I have some suggestions regarding `Flex`.

1. I don't think it should be exported as it is equivalent to `Columns` and there should ideally only be one way to do stuff.
2. The names are a bit confusing and it takes me some time to wrap my head around it every time. I'd rename `Columns` -> `Row`, `Rows` -> `Column`.

**Comment by jvaclavik** [comment]
> It's fine, but I have some suggestions regarding `Flex`.
> 
> 1. I don't think it should be exported as it is equivalent to `Columns` and there should ideally only be one way to do stuff.
> 2. The names are a bit confusing and it takes me some time to wrap my head around it every time. I'd rename `Columns` -> `Row`, `Rows` -> `Column`.

1. We can export just Row and Column and theoretically not export Flex, this could fix this issue. But sometimes you don't care about the direction (like here - centering the content). WDYT?
2. Agree, it's probably more clear if we change it this way in singular. Will fix it in different PR

**Comment by komret** [comment]
I think you care about direction so that you know whether you should `justify-content` or `align-items` to center it so I would not export `Flex`.

**Comment by bosomt** [comment]
Looks like this now

image


**Info:**
 - Suite version: web 24.5.0 (115c7183cf7da0011fc6f8e594f279c28656fac0)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:125.0) Gecko/20100101 Firefox/125.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33

**Pull request merged**
