### PR TITLE
Feat: send form + utxos registered in coinjoin

### LINKED ISSUE #6895: Propagate UTXOs registered for coinjoin into reducer
UTXOs registered for an upcoming coinjoin round need to be saved into reducer so that a corresponding icon can be shown in coin control. 

The `UtxoSelection` component is already expecting it:
```ts
const isRegisteredForCoinjoin = coinjoinAccount?.session?.registeredUtxos.includes(
        getUtxoOutpoint(utxo),
    );
```

### PR DESCRIPTION
**Pull request by szymonlesisz**
## Description

1.  ~adding registered utxos to `excludedUtxos`~
-  `excludedUtxos` calculation moved to standalone hook `useExcludedUtxos` and used in send form (replacement for https://github.com/trezor/trezor-suite/commit/52a5cc27e62e35927a88b8e1c3eb6da6cefc2604)
- `getExcludedUtxos` utility returns new reason, utxos which are currently registered in coinjoin
- tests of `useExcludedUtxos` to make sure that values are updated (or not) expectedly
> Explanation: before that getExcludedUtxos was called in 3 different places, sometimes unnecessarily. Now it is called only if certain parts of props were changed. 
~> Additional benefit: this hook can be used in `useRbfForm` as well, to be done in https://github.com/trezor/trezor-suite/issues/7184~

~2.WIP implementation of coinjoinUtxos in CoinControl. cc @komret~
~- [ ] manual selection (checkbox) for regisered utxo should be disabled~
~- [ ] decision, separate group or only marked as it is prepared? send form actions requires to have registered utxo in excludedUtxos, but in UI it might have jumping side effect when utxo is moved from one group to another (low-anonymity > registered)~

~3. assigning values to CoinjoinSession~

4. implement forgotten TODO (commented in useCompose hook) which is also a partial preparation for updating `react-hook-form` [PR](https://github.com/trezor/trezor-suite/pull/7018)
> sendForm(*)Actions should use specific set of data: ComposeActionContext (im opened for discussion regarding the name) instead of `UseSendFormState` (invity and rbf forms doesnt use it - therefore `excludedUtxos` is undefined there)

## Related Issue

Resolve #6895

### CODE REVIEW

**Comment by komret** [comment]
No. 2 implemented in #7398. Let's merge this PR before mine so that I can test with real data.

**Comment by szymonlesisz** [comment]
@komret we don't need to merge this, you can just cherrypick your commits here and continue in this branch (this is the reason why i assigned you)

i've rebased and resolved conflicts, do you want me to remove WIP commit from here or you will do it for your self?

**Comment by komret** [comment]
@szymonlesisz Ok, I'll move it here and rebase.

**Comment by komret** [comment]
The logic has changed during implementation of this issue - UTXOs registered in coinjoin are no longer excluded from sending because send form is disabled altogether.
f4878acee74bc679d985e1f406a97a64184e967f implements the new logic as a fix-up to @szymonlesisz's commit.
0aa3f29e6e72f4747a2b9d96c67db81aa811aa25 is a relic of the previous implementation, but I think styles for a disabled checkbox could be handy in future.

@szymon please check the fix-up does not mess up anything. Also,`registeredUtxos` in the reducer are not used anymore, not sure whether we should keep a675e0cb89337f10686ba21336bd627b4abe9b9a.

**Comment by szymonlesisz** [comment]
approving :+1:

**Review by komret — APPROVED** [review]

**Comment by komret** [comment]
Registered UTXOs will not be part of `excludedUtxos` as coinjoin will always pause when in send/rbf form, thus there is no more need for storing `registeredUtxos` in the reducer and they have been removed. This PR should not affect any logic currently in place, it is mostly just refactoring.

**Pull request merged**
