### PR TITLE
fix(connect-common): do not publish firmware binaries

### PR DESCRIPTION
**Pull request by matejkriz**

### CODE REVIEW

**Comment by matejkriz** [comment]
> Files included with the "package.json#files" field cannot be excluded through .npmignore or .gitignore.

https://docs.npmjs.com/cli/v7/configuring-npm/package-json#files

**Comment by matejkriz** [comment]
image

**Comment by szymonlesisz** [comment]
squash it pls

**Comment by matejkriz** [comment]
> squash it pls

@szymonlesisz squashed and version bumped

**Review by szymonlesisz — APPROVED** [review]

**Pull request merged**
