### PR TITLE
fix(connect): support unknown (custom) internal_models

### PR DESCRIPTION
**Pull request by szymonlesisz**
## Description

Connecting unknown (custom or new) model fails on multiple places:
- firmwareRelease check
- deviceInfo (device name)
- getUnavailableCapabilities check
- AbstractMethod/checkFirmwareRange check
- paramsValidator/getFirmwareRange check

### CODE REVIEW

**Review by mroz22 — APPROVED** [review]
looks legit, did not test

**Review by mroz22 — APPROVED** [review]

**Comment by szymonlesisz** [comment]
converting back to draft, i need to test it more

**Pull request merged**
