### PR TITLE
fix(suite): max fee copy

### LINKED ISSUE #3330: [copy] Ethereum sign/review fee message
Fees in Ethereum are not final, technically you can pay less for a tx to mine.
Proper message should be the same as on the device:

Screenshot from 2021-02-02 19-10-36
Screenshot from 2021-02-02 19-01-30

### PR DESCRIPTION
**Pull request by AdamSchinzel**
Updating copy since fees on Ethereum are not final

## Description

Ethereum type network have now in confirm modal Maximum fee instead of Fee.

## Related Issue

Resolve #3330

### CODE REVIEW

**Review by dahaca — COMMENTED** [review]
How about changing it in the send form as well?
image

**Comment by AdamSchinzel** [comment]
> How about changing it in the send form as well? image

Yeah makes sense 👍 a2315da6a1ad069b30c4284e42791ffc3532cd4d

**Review by dahaca — APPROVED** [review]

**Comment by bosomt** [comment]
How about changing it here too ? :) 

image

**Comment by AdamSchinzel** [comment]
Where exactly do you mean? Including fee to Including max fee?

**Comment by bosomt** [comment]
@AdamSchinzel yes

**Comment by bosomt** [comment]
and same for bumping fee, there is no max fee in bumping fee dialogue

image

**Comment by AdamSchinzel** [comment]
Now that I'm looking on the first screen, isn't the copy misleading? Total amount is 1.03 and Including fee is 0.03... I would rename including fee just to Maximum fee (without including bcs total amount is already including the fee).

And for replace tx, there is no fee right now, just current and new so in my opinion not making much sense with current copy.

cc. @sime

**Comment by sime** [comment]
Thinking out load, for normal TXs, isn't the fee always maximum? (I actually dunno, just asking)

But 'maximum fee' is in line with Ethereum Staking efforts.

Also cc: @Hannsek

**Comment by AdamSchinzel** [comment]
Yes. It's always maximum

**Comment by Hannsek** [comment]
On trezor, it looks like this: 
image

**Comment by AdamSchinzel** [comment]
So it would be better to have it the same no?

Total amount -> Amount
Including fee -> Maximum fee

**Comment by Hannsek** [comment]
Ahh, wait, there is a bug in the eth flow on Trezor. Will post here the update.

**Comment by Hannsek** [comment]
Yes

**Comment by AdamSchinzel** [comment]
Will create a separate PR for this one

**Comment by Hannsek** [comment]
But only for ETH.

**Comment by AdamSchinzel** [comment]
Maximum fee will be only for ETH but Amount for everything no?

**Comment by Hannsek** [comment]
No, other flows have _Total amount_ and _Including fee_
image

**Pull request merged**
