### PR TITLE
fix connect metadata provider

### LINKED ISSUE #3130: Labeling Dropbox and Google Drive never connects in app
**Describe the bug**
Labeling storage to  Dropbox and Google Drive is never established in application.
Browser connection is successful and it asks you to to close browser window
But app waits forever. When you close modal nothing changes and labeling is still disabled.

Works fine in Firefox browser

**Info:**
- Suite Version: app, commit 78c9fd3
- OS: Windows 10 + Mac OS
- Firmware Version: 1.9.3 model One

**Steps to reproduce:**
1. Start Suite and enable labeling
2. Connect to Dropbox or/and Goodle Drive
3. Observe 

**Expected result:**
Connection to external storage is established.

**Actual result:**
Connection to external storage is never established

**Screenshots:**
image

### PR DESCRIPTION
**Pull request by mroz22**
fix #3130

this fix has been also part of #3049 but there is still vivid discussion on whether to create a type alias or not so I am creating a separete PR without any controversialities.

### CODE REVIEW

**Review by tsusanka — APPROVED** [review]
Confirming this works :rocket:!

But @mroz22 do I understand it correctly that this gives the user 5s to make it? That is plenty for people that are already logged in into Dropbox/Google but entering email and password under 5s might be harsh. Is there any downside to increasing it?

**Comment by mroz22** [comment]
It gives user 5 second to accept response from provider after the window is closed. If no response comes within  this interval we assume that user closed window manually. Sounds awkward but there is probably no better way how to do it as I don't have access to the window opened on another domain. 5 seconds should be enough, I tested this even with throttling using "Slow 3G".

**Review by tsusanka — CHANGES_REQUESTED** [review]
Discussing in person.

**Comment by mroz22** [comment]
OK, one more change. The same hack that is used to detect popup close that works on web can't be used in electron. So as a hotfix, electron goes back to the old behavior and can't detect that popup was closed manually at the moment.

**Review by tsusanka — APPROVED** [review]
Tested and works.

**Review by keraf — APPROVED** [review]

**Pull request merged**
