### PR TITLE
fix(suite-desktop): set absolute path for dev resources

### LINKED ISSUE #2876: Desktop app: Tor connection issues
**Describe the bug**
discovery with enabled TOR always ends up with an error (works like a charm with disabled TOR)

**Info:**
 - Suite Version: desktop app, 1188894
 - OS: Windows 10
 - Firmware Version: any 

**Screenshots:**
tor-discovery-error

tor-ws-connection

### PR DESCRIPTION
**Pull request by keraf**
Fixes #2876

### CODE REVIEW

**Comment by szymonlesisz** [comment]
are you sure? this issue was present on regular build, not dev

**Comment by keraf** [comment]
The issue only appeared in dev builds for me. Is it working if you run the app as an admin? Are you running it installed or extracted?

**Comment by szymonlesisz** [comment]
imho it has nothing to do with resource path, resources are loaded normally and they are working if tor is disabled.
if tor is enabled it throws websocket connection errors not "invalid resources".

1. start app without tor, do first discovery
2. enable tor
3. add hidden wallet and do second discovery (discovery fails, caused by ws connection errors)
4. disable tor and hit "retry" (discovery success)

**Comment by szymonlesisz** [comment]
but lets give it a try. it i'll try prod. build later

**Pull request merged**
