### PR TITLE
feat(chore) Mobile issue template

### PR DESCRIPTION
**Pull request by MiroslavProchazka**
Adding new template for Mobile issues

### CODE REVIEW

**Review by mroz22 — APPROVED** [review]
meow

**Comment by MiroslavProchazka** [comment]
I don't see the last GH merging commit while rebasing in VS code, so I cannot reword/squash it. What should I do next?

**Comment by vdovhanych** [comment]
> I don't see the last GH merging commit while rebasing in VS code, so I cannot reword/squash it. What should I do next?

You need to first pull the changes so do git pull on your branch locally it will get this commit and then you can rebase it.

**Pull request merged**
