### PR TITLE
@trezor/utxo-lib grooming before breaking changes

### PR DESCRIPTION
**Pull request by szymonlesisz**
## Description

Grooming before introducing [breaking changes](https://github.com/trezor/trezor-suite/pull/8201) for `@trezor/utxo-lib` 2.0.0

- Moving types to `types` directory - same as in other  packages
- first runtime change applies to only internally used `CoinSelectSuccess` and `CoinSelectFailure` - unify interface with the other packages: { success: true | false, payload: {...} }
- second runtime change applies to renamed coinselect and compose `utils` files and imports from them

### CODE REVIEW

**Review by mroz22 — APPROVED** [review]
looks nice and neat

**Comment by szymonlesisz** [comment]
last minute fixup :/ i forgot to rename test files

**Pull request merged**
