### PR TITLE
chore: update recharts lib

### PR DESCRIPTION
**Pull request by mroz22**
instead of #4286 

added `@suite-components/TransactionsGraph` mock to few unit tests. This is more a workaround than  a proper solution solving this error while running unit tests:

```
  Details:

    /trezor-suite/node_modules/d3-shape/src/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export {default as arc} from "./arc.js";
                                                                                             ^^^^^^

    SyntaxError: Unexpected token 'export'

```

this probably could be solved also by tweaking jest configuration too. lets discuss. can this be done easily? do we need to introduce babel to solve this?

### CODE REVIEW

**Comment by matejkriz** [comment]
I don't understand why `d3-shape/src` is used instead of `d3-shape/dist`, but simply exclude `d3-shape` from `transformIgnorePatterns` in jest.config.js could probably help...

**Comment by matejkriz** [comment]
@mroz22 check this, please: https://github.com/trezor/trezor-suite/pull/4289/commits/57b1b0202d023618fbd2ca44e9cd9cb34aad0318 tests are passing! It was about adding transformation for multiple packages and do not ignore them for the transformation...

**Comment by mroz22** [comment]
nice! can confirm it works on my machine

**Comment by mroz22** [comment]
ok, rebased

**Review by matejkriz — APPROVED** [review]

**Pull request merged**
