### PR TITLE
Replace prepare-release action with a bash script

### PR DESCRIPTION
**Pull request by komret**
## Description

The GitHub action added in https://github.com/trezor/trezor-suite/pull/8164 does not work because `TREZOR_BOT_TOKEN` does not have the permission to push to a protected release branch. We concluded that giving it this permission would not be secure. This script does the same as the action (creates all the necessary branches, changes `suiteVersion`, and creates a pull request), but it is run locally so that the permissions are based on the user executing it. Tested in a forked repo.

### CODE REVIEW

**Review by vdovhanych — CHANGES_REQUESTED** [review]
Please look at the `Shell validation check` and fix the issues from that check.

**Comment by komret** [comment]
Fixed, @vdovhanych.

**Review by vdovhanych — APPROVED** [review]
All good.

**Pull request merged**
