### PR TITLE
chore(coinjoin): rename affiliationFlag > affiliationId

### PR DESCRIPTION
**Pull request by szymonlesisz**
## Description

Following [changes on coordinator](https://github.com/zkSNACKs/WalletWasabi/pull/10091#issuecomment-1434808871)

rename:
-  `affiliationFlag` > `affiliationId`
- `coinjoinRequests` > `affiliateData`

### CODE REVIEW

**Review by mroz22 — APPROVED** [review]
looks straightforward

**Comment by szymonlesisz** [comment]
pls dont merge it yet, let's test it on our coordinator first

**Comment by andrewkozlik** [comment]
I think we will also need to rename `coinjoin_requests` to `affiliate_data` (not sure).

**Comment by lontivero** [comment]
> I think we will also need to rename coinjoin_requests to affiliate_data (not sure).

Yes. That rename is required too.

**Comment by szymonlesisz** [comment]
tested locally on commit https://github.com/trezor/WalletWasabi/commit/117956370e8dc82da346a9571f8578a966a2552a

**Pull request merged**
