### PR TITLE
fix(e2e): fix dev port

### PR DESCRIPTION
**Pull request by tomasklim**
Fix of unchanged port in #3768 in e2e test configuration.

### CODE REVIEW

**Review by tsusanka — COMMENTED** [review]
Ahh that's why e2e tests did not work locally to me yesterday! Tested ACK!

Btw @matejkriz provided a [nice list](https://github.com/trezor/trezor-suite/pull/3768#issuecomment-843884950) and I think some modifications are missing? Such as the one in message-system docs.

**Comment by tsusanka** [comment]
I have also added `8000` to our [internal wiki](https://www.notion.so/satoshilabs/Ports-30cca2ab5dde470aa3cc71f6688da851).

**Comment by tomasklim** [comment]
@tsusanka See other PRs #3825 and #3826

**Comment by tsusanka** [comment]
Ah splendid!

**Review by tsusanka — APPROVED** [review]

**Pull request merged**
