### PR TITLE
feat(suite): enable Zcash v5 transactions

### LINKED ISSUE #5344: Support Zcash NU5
Zcash will soon [1] deploy the NU5 upgrade to mainnet. Currently NU5 is running on Zcash testnet. Suite only supports v4 transactions. As a result of the upgrade Suite users will not be able to spend UTXOs created in v5 transactions. However, they will still be able to spend UTXOs created in v4 transactions and earlier-version transactions.

In order to spend a UTXO created in a v5 transaction, Suite needs to spend it in a v5 transaction, which can be done as follows:
- The `version` field in `SignTx` needs to be set to 5.
- The `branchId` needs to be set to 0xc2d6d0b4, see https://zips.z.cash/zip-0252.
- The `versionGroupId` needs to be set to 0x26a7270a, I think (no source available).
- When signing v5 transactions the client does not need to provide the previous transaction(s).

The accounts and addresses remain the same as for version 4. The serialized transaction structure is different, but that is taken care of by Trezor firmware. Suite should not need to make any updates in this regard, just broadcast the transaction that Trezor spits out.

There are two implementation options for signing Zcash transactions:
1. Once this is implemented Suite will only create v5 transactions.
2. Suite will create a v5 transaction only if at least one transaction input comes from a v5 transaction. Otherwise it will create a v4 transaction.

The advantage of Option 1 is that no prev_tx streaming is needed. The advantage of Option 2 is that we only create v5 UTXOs if it's necessary to spend our selected UTXOs. This way if the wallet used by the recipient of the payment does not support v5 transactions yet, they might still be able to receive the payment, i.e. see that the payment was received and be able to spend it.

We can implement Option 2 for a transition period and switch to Option 1 later.

On Trezor NU5 support will be available starting with the upcoming releases of T1 firmware v1.11.1 and TT firmware v2.5.1. If Suite intends to sign a v5 transaction, it will need to ensure that the user has this firmware version or a later version.

This issue might be related to https://github.com/trezor/trezor-suite/issues/3749 (maybe `branchId` and `versionGroupId` can be retrieved from blockbook?). But implementing it is certainly not a prerequisite for this issue.

[1] Zcash schedule: https://z.cash/support/schedule/
[2] Firmware issue: https://github.com/trezor/trezor-firmware/issues/2031
[3] TT firmware PR: https://github.com/trezor/trezor-firmware/pull/2166
[4] T1 firmware PR: https://github.com/trezor/trezor-firmware/pull/2244

### PR DESCRIPTION
**Pull request by prusnak**
(Naively) fixes https://github.com/trezor/trezor-suite/issues/5344 - Option 1 = v5 only

If the support table at the bottom of https://z.cash/upgrade/nu5/ should be trusted, there should not be an issue to support v5 only straight away.

### CODE REVIEW

**Comment by prusnak** [comment]
No testing has been performed yet. Also the PR does not provide test vectors, yet.

**Comment by szymonlesisz** [comment]
maybe it's a good time to implement this https://github.com/trezor/trezor-suite/issues/3749?

**Comment by prusnak** [comment]
> maybe it's a good time to implement this #3749?

Is all necessary info already served by the Blockbook? I don't think so. Moreover, I do believe the logic/decision which transaction format to use should belong to Trezor Suite not to Blockbook, especially if we need more complex decision such as suggested as Option 2 of https://github.com/trezor/trezor-suite/issues/5344

**Comment by szymonlesisz** [comment]
> Is all necessary info already served by the Blockbook? I don't think so.

i was convinced that it does since that is issue is already 1 year old :) but looks like [it doesnt ](https://zec1.trezor.io/api/v2/get-info)

> I do believe the logic/decision which transaction format to use should belong to Trezor Suite not to Blockbook

[in previous forks we were relying on blockHeight](https://github.com/trezor/trezor-suite/pull/2072/files) from blockbook  to determine which branchId/versionGroupId should be used and afaik that was the intention in mentioned issue, to get  them from the backend instead of hardcoding in suite (and in connect as well, to provide v5 support for 3rd parties)

I was thinking that this is the same case again, i didnt follow zcash v5 development only noticed your changes which reminded me about that issue

**Comment by szymonlesisz** [comment]
I've just did a quick look on the issue and here is what needs to be done:
- update trezor-common [coins definition](https://github.com/trezor/trezor-firmware/blob/master/common/defs/bitcoin/zcash.json#L40-L45=) and add v5 there (those data are used by connect and passed to utxo-lib) 
- make sure that `@trezor/utxo-lib` transaction [parsing is working](https://github.com/trezor/trezor-suite/blob/develop/packages/utxo-lib/src/transaction/zcash.ts#L306=) properly, if v5 tx contains some additional data it probably will not work out of the box
- i'm suggesting to add logic from option 2 only to  `@trezor/connect` (looking up at inputs to make the decision about tx version) [somewere here](https://github.com/trezor/trezor-suite/blob/develop/packages/connect/src/api/signTransaction.ts#L95=) and [here](https://github.com/trezor/trezor-suite/blob/develop/packages/connect/src/api/composeTransaction.ts#L358-L364=)
- remove enhancement constants from suite completely and leave it to `@trezor/connect`

**Comment by prusnak** [comment]
> * update trezor-common [coins definition](https://github.com/trezor/trezor-firmware/blob/master/common/defs/bitcoin/zcash.json#L40-L45=) and add v5 there (those data are used by connect and passed to utxo-lib)

Added in https://github.com/trezor/trezor-firmware/commit/ea35f46f5f5cd79b54a709d48b534126545e3db0

**Comment by prusnak** [comment]
Pushed 9be27ad9618dc21a9f022fbd00cc3c5703d42840 which also changes the constants in connect.

@szymonlesisz are you saying we can now drop `ZEC_SIGN_ENHANCEMENT` from the Send Dialog completely because connect always adds the constants correctly?

**Comment by szymonlesisz** [comment]
@prusnak 
> are you saying we can now drop ZEC_SIGN_ENHANCEMENT from the Send Dialog completely because connect always adds the constants correctly?

currently connect adds those only in one method, [composeTransaction](https://github.com/trezor/trezor-suite/blob/develop/packages/connect/src/api/composeTransaction.ts#L358-L364=) in `signTransaction` you (suite) still have to provide it.

my suggestion was to move this also into `signTransaction` method  to have it in one place for easier maintenance (in cases when you are signing zcash/zcash-like and you are not providing them defaults will be added automatically).

This logic could be even extended by Option 2 of https://github.com/trezor/trezor-suite/issues/5344

**Comment by szymonlesisz** [comment]
closing in favor of https://github.com/trezor/trezor-suite/pull/5554

**Pull request closed without merging**
