### PR TITLE
feat: build desktop and web app on github acitons

### PR DESCRIPTION
**Pull request by vdovhanych**

### CODE REVIEW

**Review by komret — APPROVED** [review]

**Comment by komret** [comment]
There is a formatting issue, see validation check.

**Comment by komret** [comment]
@vdovhanych There are some checks failing and I noticed a typo in filename `suite-prouction-ci.yml`

**Comment by vdovhanych** [comment]
Yes this doesnt work at all atm i need to revisit how to do it :)

**Comment by vdovhanych** [comment]
Closing this as it was solved in a different PR

**Pull request closed without merging**
