### PR TITLE
feat(repo): TS 5.5

### PR DESCRIPTION
**Pull request by Nodonisko**
## Related Issue

Resolve

### CODE REVIEW

**Review by mroz22 — COMMENTED** [review]
uf, these are type-box related. maybe @martykan could take a look. also I just noted that there is yet another version of type-box so maybe updating might help (blind shot here)

**Comment by martykan** [comment]
Yeah unfortunately this is the part where I was doing some black magic to infer a type for "keyof enum". 
I will try to see if it's fixable

**Comment by martykan** [comment]
I think we're good to go, should I rebase?

**Comment by Nodonisko** [comment]
@martykan Thanks for fixing it!

Yes, rebase please.

**Review by martykan — APPROVED** [review]

**Pull request merged**
