### PR TITLE
feat(ci): add CodeQL analysis

### PR DESCRIPTION
**Pull request by tsusanka**
As discussed with @matejkriz we want to try this out.
- We need to fix the errors before merging (obviously).
- @vdovhanych feel free to take over the PR and do whatever if needed.

### CODE REVIEW

**Comment by mroz22** [comment]
Cool. I think some of those "bugs" are reported for tests and can be ignored.

**Comment by vdovhanych** [comment]
I like it, fixed only some formatting so the lint is happy, and I also changed the file name so we're consistent in the naming scheme for the `worklows` folder. And I would like to change the name of the workflow to `CodeQL check` can I do it and then rebase the fixup commit?

**Comment by mroz22** [comment]
image
 
there is actually option "used in test". I will go through and mark those I believe should be marked "used in tests" if you dont mind.

**Comment by tsusanka** [comment]
Yes, yes, please take over (both of you) and do what you need :)

**Review by vdovhanych — APPROVED** [review]

**Comment by vdovhanych** [comment]
@mroz22 have you checked everything that is used for tests, can I merge this?

**Comment by mroz22** [comment]
Maybe we could silence all existing "errors" as these parts of code can be considered "battle tested"? And focus only on what will be reported in future. Otherwise it would need some refactoring.

**Review by matejkriz — APPROVED** [review]
Dismissed all the current issues as not that much important, but the tool looks very promising  ❤️

**Pull request merged**
