### PR TITLE
Quick action debug eap exp tooltip & Tor

### PR DESCRIPTION
**Pull request by peter-sanderson**
Part of https://github.com/trezor/trezor-suite/issues/13990

image
image
image

### CODE REVIEW

**Comment by jvaclavik** [comment]
Screenshot 2024-09-08 at 08 47 22

 I think gaps are not matching with [Figma](https://www.figma.com/design/d8Ekwm865R3YR6PtH4gdyc/Auto-update?node-id=4083-20734&node-type=SECTION&t=dSNpiDx19ys6jvpV-0)

**Review by jvaclavik — APPROVED** [review]
Looks good except padding (see above)

**Comment by peter-sanderson** [comment]
@jvaclavik thanks, nice catch

I fixed all but the width. Despite in Figma the Update & EAP tooltips has same width I decided to leave it as "auto" with. The reason is that Tor is small (auto) width in figma so I suppose the EAP Tooltip width is just an error (copy-pasted tooltip from Upate)

image

**Comment by jvaclavik** [comment]
> I fixed all but the width. Despite in Figma the Update & EAP tooltips has same width I decided to leave it as "auto" with. The reason is that Tor is small (auto) width in figma so I suppose the EAP Tooltip width is just an error (copy-pasted tooltip from Upate)

Makes sense 👍

**Comment by peter-sanderson** [comment]
image
image
image

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.10.0 (0c147a1d37dc615e286a114d90bc8b637bbb929f)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.10.0 Chrome/124.0.6367.243 Electron/30.3.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 2.0.33

**Pull request merged**
