### PR TITLE
Solana spl-token-2022

### LINKED ISSUE #13538: Solana Token2022
**Token2022 overview**

**Suite:**

- tokens are not visible (e.g. `$CWIF`)
- transactions including Token2022 are `Unknown transaction`

**Third-party wallet:**
- Nufi and Backpack ok
- tokens are visible
- device is able to sign transactions with Token2022. It just says `Transaction contains unknown instructions`

**Device:**
- resolve `Transaction contains unknown instructions`

### PR DESCRIPTION
**Pull request by tomasklim**
original #15769

QA manual:

1. Open desktop solana app
2. Use backpack to buy some `Token2022` type token on Jupiter (try something else then `pyusd`)
Screenshot 2024-12-11 at 13 39 55
3. Check the account on Suite if it now shows the token you bought
4. Try to send it (suite)
5. Try to swap it (suite)
6. Restart and check token is still there

_____

1. Test it also in web app
2. ...

Resolve [#13538](https://github.com/trezor/trezor-suite/issues/13538)

### CODE REVIEW

**Comment by tomasklim** [comment]
@SocketSecurity ignore npm/@solana-program/token-2022@0.3.1

**Review by martykan — APPROVED** [review]
Works in my tests, LGTM

**Comment by STew790** [comment]
**QA OK**
I can see tx history of token and I am able to send it.
image
image
image


**Info**
25.1.2 ac8cd6e

**Pull request merged**
