### PR TITLE
fix: smaller image in "Your wallet is almost ready" step to prevent s…

### LINKED ISSUE #2588: Redundant scroll bar in onboarding
I am using desktop version in fullscreen and my viewport size is 1920 × 948 based on whatismyviewport.com.

image

Revision: b8ea32c7bce1702e0c990324921df77c5669152a
OS: NixOS
Browser: Firefox 81

### PR DESCRIPTION
**Pull request by slowbackspace**
…crollbars showing

as a quick workaround should be good enough
fix https://github.com/trezor/trezor-suite/issues/2588

### CODE REVIEW

**Review by szymonlesisz — APPROVED** [review]

**Comment by tsusanka** [comment]
@slowbackspace I can still see scrollbar on https://suite.corp.sldev.cz/suite-web/fix/onboarding-wallet-ready-overflow/web/ even though the `height` seems to be applied.

image

----

Seems to fail on Firefox only. Works fine in Chromium 85.

**Comment by slowbackspace** [comment]
I found few other similar issues (due to longer texts), I'll fix them in this branch.

**Comment by tsusanka** [comment]
I confirm Firefox is fixed by 9509a31 :tada:.

**Comment by slowbackspace** [comment]
Okay, fixed few scrollbars in backup and wipe modals. cc @mroz22 if you wanna take a look

**Review by mroz22 — APPROVED** [review]

**Pull request merged**
