### PR TITLE
Dependencies update 03/2023

### PR DESCRIPTION
**Pull request by tomasklim**
## Description
- `typescript` and `react-native` things are left for mobile team 😒
- cypress image updated
- `bs58check` moved to separate PR #7981

## Related Issue

[Notion](https://www.notion.so/Dependency-Management-1b5bf845aa1f4ca7b9d57ea9ccd3fe63?p=f8968e809d634c0baa818470bcae824b&pm=s)

### CODE REVIEW

**Review by Nodonisko — CHANGES_REQUESTED** [review]
There must be something wrong because there should be no need to type slices, types should be infered automatically. I will try to investigate.

**Comment by Nodonisko** [comment]
Are you sure that TS errors for slices wasn't some kind of local only glitch? I checking diff between version and basically they did not touched slices API or types at all https://github.com/reduxjs/redux-toolkit/compare/v1.9.2...v1.9.3

**Comment by dahaca** [comment]
@Nodonisko can confirm that both upgrading `toolkit` only on `dev` and removing types on this branch yields no errors for me 🤔

**Comment by tomasklim** [comment]
Looks like some local glitch. I removed it and `type-check` had no problem today. I had this problem also in the past.

**Comment by tomasklim** [comment]
@SocketSecurity ignore electron@23.2.1
@SocketSecurity ignore esbuild@0.17.15

**Review by Nodonisko — APPROVED** [review]

**Pull request merged**
