### PR TITLE
Zoin coin graphics added

### PR DESCRIPTION
**Pull request by seopub**
## Description
Added Zoin coin images

Added zoin.svg, edited icons.ts
## Related Issue

Resolve

### CODE REVIEW

**Review by Nodonisko — DISMISSED** [review]
Fine by mobile

**Comment by mroz22** [comment]
What is zoin coin and why do we need it?

**Comment by Nodonisko** [comment]
Also logo seems to be different from one on official websites https://zoinofficial.com

**Comment by seopub** [comment]
Zoin is CPU only mining privacy coin, original project was abandoned, community takeover happened
Community web site 74.48.196.40
Team on Telegram  https://t.me/ZoinCommunity, 
https://t.me/+aG4q2apEvpVjOWJk
It possible to use same logo as original coin

**Comment by seopub** [comment]
> Also logo seems to be different from one on official websites https://zoinofficial.com

Zoin Zerocoin based fork, CPU mining, no premine
https://github.com/zoin/zoin
In 2019 rebranded to Noir updated Zerocoin version to Sigma that makes improvements over Zerocoin in areas
removal of trusted setup, reduction of proof size from 25 kB to 1.5 kB, improved security
https://github.com/noirofficial/noir/tree/master
In 2022 Sigma version abandoned and swapped to Algorand chain
Noir Standard Asset (ASA) on the Algorand-Chain with the name aNoir
Community version uses 2019 rebranded source code

**Comment by mroz22** [comment]
sorry this PR does not make any sense. Coin support needs to be built bottom-up. Graphics should come last

**Pull request closed without merging**
